# --- !Ups

UPDATE cf_element SET element_id='best_estimate_mean(air_temperature P1M)' WHERE element_id='best_estimate_mean(air_temperature 1M)';
UPDATE cf_element SET element_id='best_estimate_mean(air_temperature_anomaly P1M)' WHERE element_id='best_estimate_mean(air_temperature_anomaly 1M)';
UPDATE cf_element SET element_id='best_estimate_mean(air_temperature PT24H)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE cf_element SET element_id='best_estimate_sum(precipitation_amount P1M)' WHERE element_id='best_estimate_sum(precipitation_amount 1M)';
UPDATE cf_element SET element_id='best_estimate_sum(precipitation_amount_anomaly P1M)' WHERE element_id='best_estimate_sum(precipitation_amount_anomaly 1M)';
UPDATE cf_element SET element_id='boolean_clear_sky_weather(cloud_area_fraction PT24H)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='boolean_fair_weather(cloud_area_fraction PT24H)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='boolean_overcast_weather(cloud_area_fraction PT24H)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='change_over_time(surface_air_pressure PT1H)' WHERE element_id='change_over_time(surface_air_pressure T1H)';
UPDATE cf_element SET element_id='change_over_time(surface_air_pressure PT3H)' WHERE element_id='change_over_time(surface_air_pressure T3H)';
UPDATE cf_element SET element_id='change_over_time(surface_air_pressure PT6H)' WHERE element_id='change_over_time(surface_air_pressure T6H)';
UPDATE cf_element SET element_id='change_over_time(surface_snow_amount PT24H)' WHERE element_id='change_over_time(surface_snow_amount T24H)';
UPDATE cf_element SET element_id='change_over_time(surface_snow_thickness PT24H)' WHERE element_id='change_over_time(surface_snow_thickness T24H)';
UPDATE cf_element SET element_id='directional_spread(sea_surface_peak_period PT20M)' WHERE element_id='directional_spread(sea_surface_peak_period T20M)';
UPDATE cf_element SET element_id='directional_spread(sea_surface_wave_total_energy PT20M)' WHERE element_id='directional_spread(sea_surface_wave_total_energy T20M)';
UPDATE cf_element SET element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period PT10M)' WHERE element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)';
UPDATE cf_element SET element_id='from_direction_of_max(wind_speed_of_gust PT10M)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T10M)';
UPDATE cf_element SET element_id='from_direction_of_max(wind_speed_of_gust PT1H)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T1H)';
UPDATE cf_element SET element_id='from_direction_of_max(wind_speed PT1H)' WHERE element_id='from_direction_of_max(wind_speed T1H)';
UPDATE cf_element SET element_id='from_direction_of_max(wind_speed PT20M)' WHERE element_id='from_direction_of_max(wind_speed T20M)';
UPDATE cf_element SET element_id='from_direction_of_max(wind_speed PT3H)' WHERE element_id='from_direction_of_max(wind_speed T3H)';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_primary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T10M)';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_primary_wave PT20M)' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T20M)';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_secondary_wave T10M)';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T10M)';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT20M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T20M)';
UPDATE cf_element SET element_id='from_direction_of_peak(sea_surface_primary_wave PT20M)' WHERE element_id='from_direction_of_peak(sea_surface_primary_wave T20M)';
UPDATE cf_element SET element_id='from_direction_of_peak(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_secondary_wave T10M)';
UPDATE cf_element SET element_id='from_direction_of_peak(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_wave_total_energy T10M)';
UPDATE cf_element SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT10M)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T10M)';
UPDATE cf_element SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T3H)';
UPDATE cf_element SET element_id='from_direction(sea_surface_swell_wave_second_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_second_mean_height T3H)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) PT24H 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) PT24H 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT24H) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT24H) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE cf_element SET element_id='integral_of_excess_interpolated(mean(air_temperature PT24H) P1M P17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature PT1H) PT24H P17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature PT24H) P1M P17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE cf_element SET element_id='max(air_pressure_at_sea_level P1M)' WHERE element_id='max(air_pressure_at_sea_level 1M)';
UPDATE cf_element SET element_id='max(air_pressure_at_sea_level PT24H)' WHERE element_id='max(air_pressure_at_sea_level T24H)';
UPDATE cf_element SET element_id='max(air_temperature P1M)' WHERE element_id='max(air_temperature 1M)';
UPDATE cf_element SET element_id='max(air_temperature PT10M)' WHERE element_id='max(air_temperature T10M)';
UPDATE cf_element SET element_id='max(air_temperature PT12H)' WHERE element_id='max(air_temperature T12H)';
UPDATE cf_element SET element_id='max(air_temperature PT1H)' WHERE element_id='max(air_temperature T1H)';
UPDATE cf_element SET element_id='max(air_temperature PT24H)' WHERE element_id='max(air_temperature T24H)';
UPDATE cf_element SET element_id='max(beaufort_wind_force PT6H)' WHERE element_id='max(beaufort_wind_force T6H)';
UPDATE cf_element SET element_id='max(cloud_area_fraction P1M)' WHERE element_id='max(cloud_area_fraction 1M)';
UPDATE cf_element SET element_id='max(cloud_area_fraction PT24H)' WHERE element_id='max(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='max(grass_temperature PT1H)' WHERE element_id='max(grass_temperature T1H)';
UPDATE cf_element SET element_id='max(max(wind_speed PT1H) PT24H)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE cf_element SET element_id='max(max(wind_speed PT24H) P1M)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='max(min(grass_temperature PT1H) P1M)' WHERE element_id='max(min(grass_temperature T1H) 1M)';
UPDATE cf_element SET element_id='max(relative_humidity P1M)' WHERE element_id='max(relative_humidity 1M)';
UPDATE cf_element SET element_id='max(relative_humidity PT24H)' WHERE element_id='max(relative_humidity T24H)';
UPDATE cf_element SET element_id='max(sea_state P1M)' WHERE element_id='max(sea_state 1M)';
UPDATE cf_element SET element_id='max(sea_state PT24H)' WHERE element_id='max(sea_state T24H)';
UPDATE cf_element SET element_id='max(sea_surface_temperature P1M)' WHERE element_id='max(sea_surface_temperature 1M)';
UPDATE cf_element SET element_id='max(sea_surface_temperature PT1H)' WHERE element_id='max(sea_surface_temperature T1H)';
UPDATE cf_element SET element_id='max(sea_surface_wave_height PT10M)' WHERE element_id='max(sea_surface_wave_height T10M)';
UPDATE cf_element SET element_id='max(sea_surface_wave_height PT20M)' WHERE element_id='max(sea_surface_wave_height T20M)';
UPDATE cf_element SET element_id='max(sea_surface_wave_period_from_instrument P1M)' WHERE element_id='max(sea_surface_wave_period_from_instrument 1M)';
UPDATE cf_element SET element_id='max(sea_surface_wave_period_from_instrument PT24H)' WHERE element_id='max(sea_surface_wave_period_from_instrument T24H)';
UPDATE cf_element SET element_id='max(sea_surface_wave_period PT20M)' WHERE element_id='max(sea_surface_wave_period T20M)';
UPDATE cf_element SET element_id='max(sea_surface_wave_significant_height_from_instrument P1M)' WHERE element_id='max(sea_surface_wave_significant_height_from_instrument 1M)';
UPDATE cf_element SET element_id='max(sea_surface_wave_significant_height_from_instrument PT24H)' WHERE element_id='max(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE cf_element SET element_id='max(snow_coverage_type P1M)' WHERE element_id='max(snow_coverage_type 1M)';
UPDATE cf_element SET element_id='max(snow_temperature PT1H)' WHERE element_id='max(snow_temperature T1H)';
UPDATE cf_element SET element_id='max(sum(duration_of_sunshine PT24H) P1M)' WHERE element_id='max(sum(duration_of_sunshine T24H) 1M)';
UPDATE cf_element SET element_id='max(sum(precipitation_amount PT24H) P1M)' WHERE element_id='max(sum(precipitation_amount T24H) 1M)';
UPDATE cf_element SET element_id='max(surface_air_pressure P1M)' WHERE element_id='max(surface_air_pressure 1M)';
UPDATE cf_element SET element_id='max(surface_air_pressure PT1H)' WHERE element_id='max(surface_air_pressure T1H)';
UPDATE cf_element SET element_id='max(surface_air_pressure PT24H)' WHERE element_id='max(surface_air_pressure T24H)';
UPDATE cf_element SET element_id='max(surface_snow_thickness P1M)' WHERE element_id='max(surface_snow_thickness 1M)';
UPDATE cf_element SET element_id='max(surface_snow_thickness PT1H)' WHERE element_id='max(surface_snow_thickness T1H)';
UPDATE cf_element SET element_id='max(surface_temperature PT1H)' WHERE element_id='max(surface_temperature T1H)';
UPDATE cf_element SET element_id='max(timeperiod_weather_type_significance1 PT24H)' WHERE element_id='max(timeperiod_weather_type_significance1 T24H)';
UPDATE cf_element SET element_id='max(visibility_in_air_horizontal P1M)' WHERE element_id='max(visibility_in_air_horizontal 1M)';
UPDATE cf_element SET element_id='max(visibility_in_air_horizontal PT24H)' WHERE element_id='max(visibility_in_air_horizontal T24H)';
UPDATE cf_element SET element_id='max(wind_speed P1M)' WHERE element_id='max(wind_speed 1M)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust P1M)' WHERE element_id='max(wind_speed_of_gust 1M)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust PT10M)' WHERE element_id='max(wind_speed_of_gust T10M)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust PT1H)' WHERE element_id='max(wind_speed_of_gust T1H)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust PT24H)' WHERE element_id='max(wind_speed_of_gust T24H)';
UPDATE cf_element SET element_id='max(wind_speed PT10M)' WHERE element_id='max(wind_speed T10M)';
UPDATE cf_element SET element_id='max(wind_speed PT1H)' WHERE element_id='max(wind_speed T1H)';
UPDATE cf_element SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE cf_element SET element_id='max(wind_speed PT24H)' WHERE element_id='max(wind_speed T24H)';
UPDATE cf_element SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE cf_element SET element_id='max(wind_speed PT6H)' WHERE element_id='max(wind_speed T6H)';
UPDATE cf_element SET element_id='mean(air_pressure_at_sea_level P1M)' WHERE element_id='mean(air_pressure_at_sea_level 1M)';
UPDATE cf_element SET element_id='mean(air_pressure_at_sea_level PT24H)' WHERE element_id='mean(air_pressure_at_sea_level T24H)';
UPDATE cf_element SET element_id='mean(air_temperature P1M)' WHERE element_id='mean(air_temperature 1M)';
UPDATE cf_element SET element_id='mean(air_temperature_anomaly P1M)' WHERE element_id='mean(air_temperature_anomaly 1M)';
UPDATE cf_element SET element_id='mean(air_temperature PT1H)' WHERE element_id='mean(air_temperature T1H)';
UPDATE cf_element SET element_id='mean(air_temperature PT24H)' WHERE element_id='mean(air_temperature T24H)';
UPDATE cf_element SET element_id='mean(cloud_area_fraction P1M)' WHERE element_id='mean(cloud_area_fraction 1M)';
UPDATE cf_element SET element_id='mean(cloud_area_fraction PT24H)' WHERE element_id='mean(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='mean(dew_point_temperature P1M)' WHERE element_id='mean(dew_point_temperature 1M)';
UPDATE cf_element SET element_id='mean(dew_point_temperature PT24H)' WHERE element_id='mean(dew_point_temperature T24H)';
UPDATE cf_element SET element_id='mean(grass_temperature PT1H)' WHERE element_id='mean(grass_temperature T1H)';
UPDATE cf_element SET element_id='mean_k(air_temperature P1M)' WHERE element_id='mean_k(air_temperature 1M)';
UPDATE cf_element SET element_id='mean_k(air_temperature PT24H)' WHERE element_id='mean_k(air_temperature T24H)';
UPDATE cf_element SET element_id='mean(max(air_temperature PT24H) P1M)' WHERE element_id='mean(max(air_temperature T24H) 1M)';
UPDATE cf_element SET element_id='mean(max(wind_speed PT1H) PT24H)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE cf_element SET element_id='mean(max(wind_speed PT24H) P1M)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='mean(min(air_temperature PT24H) P1M)' WHERE element_id='mean(min(air_temperature T24H) 1M)';
UPDATE cf_element SET element_id='mean(min(grass_temperature PT1H) P1M)' WHERE element_id='mean(min(grass_temperature T1H) 1M)';
UPDATE cf_element SET element_id='mean(relative_humidity P1M)' WHERE element_id='mean(relative_humidity 1M)';
UPDATE cf_element SET element_id='mean(relative_humidity PT1H)' WHERE element_id='mean(relative_humidity T1H)';
UPDATE cf_element SET element_id='mean(relative_humidity PT24H)' WHERE element_id='mean(relative_humidity T24H)';
UPDATE cf_element SET element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE cf_element SET element_id='mean(sea_surface_temperature P1M)' WHERE element_id='mean(sea_surface_temperature 1M)';
UPDATE cf_element SET element_id='mean(sea_surface_temperature PT1H)' WHERE element_id='mean(sea_surface_temperature T1H)';
UPDATE cf_element SET element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE cf_element SET element_id='mean(sea_surface_wave_period_from_instrument P1M)' WHERE element_id='mean(sea_surface_wave_period_from_instrument 1M)';
UPDATE cf_element SET element_id='mean(sea_surface_wave_period_from_instrument PT24H)' WHERE element_id='mean(sea_surface_wave_period_from_instrument T24H)';
UPDATE cf_element SET element_id='mean(sea_surface_wave_significant_height_from_instrument P1M)' WHERE element_id='mean(sea_surface_wave_significant_height_from_instrument 1M)';
UPDATE cf_element SET element_id='mean(sea_surface_wave_significant_height_from_instrument PT24H)' WHERE element_id='mean(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE cf_element SET element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE cf_element SET element_id='mean(snow_coverage_type P1M)' WHERE element_id='mean(snow_coverage_type 1M)';
UPDATE cf_element SET element_id='mean(soil_temperature PT1H)' WHERE element_id='mean(soil_temperature T1H)';
UPDATE cf_element SET element_id='mean(specific_humidity P1M)' WHERE element_id='mean(specific_humidity 1M)';
UPDATE cf_element SET element_id='mean(surface_air_pressure P1M)' WHERE element_id='mean(surface_air_pressure 1M)';
UPDATE cf_element SET element_id='mean(surface_air_pressure PT1H)' WHERE element_id='mean(surface_air_pressure T1H)';
UPDATE cf_element SET element_id='mean(surface_air_pressure PT24H)' WHERE element_id='mean(surface_air_pressure T24H)';
UPDATE cf_element SET element_id='mean(surface_snow_thickness P1M)' WHERE element_id='mean(surface_snow_thickness 1M)';
UPDATE cf_element SET element_id='mean(surface_snow_thickness PT1H)' WHERE element_id='mean(surface_snow_thickness T1H)';
UPDATE cf_element SET element_id='mean(surface_temperature PT1H)' WHERE element_id='mean(surface_temperature T1H)';
UPDATE cf_element SET element_id='mean(wind_from_direction PT1H)' WHERE element_id='mean(wind_from_direction T1H)';
UPDATE cf_element SET element_id='mean(wind_speed P1M)' WHERE element_id='mean(wind_speed 1M)';
UPDATE cf_element SET element_id='mean(wind_speed_of_gust P1M)' WHERE element_id='mean(wind_speed_of_gust 1M)';
UPDATE cf_element SET element_id='mean(wind_speed_of_gust PT24H)' WHERE element_id='mean(wind_speed_of_gust T24H)';
UPDATE cf_element SET element_id='mean(wind_speed PT1H)' WHERE element_id='mean(wind_speed T1H)';
UPDATE cf_element SET element_id='mean(wind_speed PT24H)' WHERE element_id='mean(wind_speed T24H)';
UPDATE cf_element SET element_id='min(air_pressure_at_sea_level P1M)' WHERE element_id='min(air_pressure_at_sea_level 1M)';
UPDATE cf_element SET element_id='min(air_pressure_at_sea_level PT24H)' WHERE element_id='min(air_pressure_at_sea_level T24H)';
UPDATE cf_element SET element_id='min(air_temperature P1M)' WHERE element_id='min(air_temperature 1M)';
UPDATE cf_element SET element_id='min(air_temperature PT10M)' WHERE element_id='min(air_temperature T10M)';
UPDATE cf_element SET element_id='min(air_temperature PT12H)' WHERE element_id='min(air_temperature T12H)';
UPDATE cf_element SET element_id='min(air_temperature PT1H)' WHERE element_id='min(air_temperature T1H)';
UPDATE cf_element SET element_id='min(air_temperature PT24H)' WHERE element_id='min(air_temperature T24H)';
UPDATE cf_element SET element_id='min(cloud_area_fraction P1M)' WHERE element_id='min(cloud_area_fraction 1M)';
UPDATE cf_element SET element_id='min(cloud_area_fraction PT24H)' WHERE element_id='min(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='min(cloud_base_height PT1H)' WHERE element_id='min(cloud_base_height T1H)';
UPDATE cf_element SET element_id='min(grass_temperature PT12H)' WHERE element_id='min(grass_temperature T12H)';
UPDATE cf_element SET element_id='min(grass_temperature PT1H)' WHERE element_id='min(grass_temperature T1H)';
UPDATE cf_element SET element_id='min(grass_temperature PT24H)' WHERE element_id='min(grass_temperature T24H)';
UPDATE cf_element SET element_id='min(max(wind_speed PT1H) PT24H)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE cf_element SET element_id='min(max(wind_speed PT24H) P1M)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='min(min(grass_temperature PT1H) P1M)' WHERE element_id='min(min(grass_temperature T1H) 1M)';
UPDATE cf_element SET element_id='min(relative_humidity P1M)' WHERE element_id='min(relative_humidity 1M)';
UPDATE cf_element SET element_id='min(relative_humidity PT24H)' WHERE element_id='min(relative_humidity T24H)';
UPDATE cf_element SET element_id='min(sea_state P1M)' WHERE element_id='min(sea_state 1M)';
UPDATE cf_element SET element_id='min(sea_state PT24H)' WHERE element_id='min(sea_state T24H)';
UPDATE cf_element SET element_id='min(sea_surface_temperature P1M)' WHERE element_id='min(sea_surface_temperature 1M)';
UPDATE cf_element SET element_id='min(sea_surface_temperature PT1H)' WHERE element_id='min(sea_surface_temperature T1H)';
UPDATE cf_element SET element_id='min(sea_surface_wave_period_from_instrument P1M)' WHERE element_id='min(sea_surface_wave_period_from_instrument 1M)';
UPDATE cf_element SET element_id='min(sea_surface_wave_period_from_instrument PT24H)' WHERE element_id='min(sea_surface_wave_period_from_instrument T24H)';
UPDATE cf_element SET element_id='min(sea_surface_wave_significant_height_from_instrument P1M)' WHERE element_id='min(sea_surface_wave_significant_height_from_instrument 1M)';
UPDATE cf_element SET element_id='min(sea_surface_wave_significant_height_from_instrument PT24H)' WHERE element_id='min(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE cf_element SET element_id='min(snow_coverage_type P1M)' WHERE element_id='min(snow_coverage_type 1M)';
UPDATE cf_element SET element_id='min(snow_temperature PT1H)' WHERE element_id='min(snow_temperature T1H)';
UPDATE cf_element SET element_id='min(sum(duration_of_sunshine PT24H) P1M)' WHERE element_id='min(sum(duration_of_sunshine T24H) 1M)';
UPDATE cf_element SET element_id='min(surface_air_pressure P1M)' WHERE element_id='min(surface_air_pressure 1M)';
UPDATE cf_element SET element_id='min(surface_air_pressure PT1H)' WHERE element_id='min(surface_air_pressure T1H)';
UPDATE cf_element SET element_id='min(surface_air_pressure PT24H)' WHERE element_id='min(surface_air_pressure T24H)';
UPDATE cf_element SET element_id='min(surface_snow_thickness P1M)' WHERE element_id='min(surface_snow_thickness 1M)';
UPDATE cf_element SET element_id='min(surface_snow_thickness PT1H)' WHERE element_id='min(surface_snow_thickness T1H)';
UPDATE cf_element SET element_id='min(surface_temperature PT1H)' WHERE element_id='min(surface_temperature T1H)';
UPDATE cf_element SET element_id='min(visibility_in_air_horizontal P1M)' WHERE element_id='min(visibility_in_air_horizontal 1M)';
UPDATE cf_element SET element_id='min(visibility_in_air_horizontal PT24H)' WHERE element_id='min(visibility_in_air_horizontal T24H)';
UPDATE cf_element SET element_id='min(wind_speed P1M)' WHERE element_id='min(wind_speed 1M)';
UPDATE cf_element SET element_id='min(wind_speed_of_gust P1M)' WHERE element_id='min(wind_speed_of_gust 1M)';
UPDATE cf_element SET element_id='min(wind_speed_of_gust PT24H)' WHERE element_id='min(wind_speed_of_gust T24H)';
UPDATE cf_element SET element_id='min(wind_speed PT24H)' WHERE element_id='min(wind_speed T24H)';
UPDATE cf_element SET element_id='number_of_days_gte(sum(precipitation_amount PT24H) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE cf_element SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction PT24H) P1M)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE cf_element SET element_id='sum(boolean_fair_weather(cloud_area_fraction PT24H) P1M)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE cf_element SET element_id='sum(boolean_overcast_weather(cloud_area_fraction PT24H) P1M)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE cf_element SET element_id='sum(duration_of_sunshine P1M)' WHERE element_id='sum(duration_of_sunshine 1M)';
UPDATE cf_element SET element_id='sum(duration_of_sunshine PT1H)' WHERE element_id='sum(duration_of_sunshine T1H)';
UPDATE cf_element SET element_id='sum(duration_of_sunshine PT24H)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE cf_element SET element_id='sum_over_undefined_period(precipitation_amount P1M)' WHERE element_id='sum_over_undefined_period(precipitation_amount 1M)';
UPDATE cf_element SET element_id='sum_over_undefined_period(precipitation_amount PT1H)' WHERE element_id='sum_over_undefined_period(precipitation_amount T1H)';
UPDATE cf_element SET element_id='sum_over_undefined_period(precipitation_amount PT24H)' WHERE element_id='sum_over_undefined_period(precipitation_amount T24H)';
UPDATE cf_element SET element_id='sum(precipitation_amount P1M)' WHERE element_id='sum(precipitation_amount 1M)';
UPDATE cf_element SET element_id='sum(precipitation_amount_anomaly P1M)' WHERE element_id='sum(precipitation_amount_anomaly 1M)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT10M)' WHERE element_id='sum(precipitation_amount T10M)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT12H)' WHERE element_id='sum(precipitation_amount T12H)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT1H)' WHERE element_id='sum(precipitation_amount T1H)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT1M)' WHERE element_id='sum(precipitation_amount T1M)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT24H)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT3H)' WHERE element_id='sum(precipitation_amount T3H)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT6H)' WHERE element_id='sum(precipitation_amount T6H)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT720H)' WHERE element_id='sum(precipitation_amount T720H)';
UPDATE cf_element SET element_id='sum(water_evaporation_amount PT1H)' WHERE element_id='sum(water_evaporation_amount T1H)';
UPDATE cf_element SET element_id='sum(water_evaporation_amount PT24H)' WHERE element_id='sum(water_evaporation_amount T24H)';
UPDATE cf_element SET element_id='time_of_event_of_max(air_temperature P1M)' WHERE element_id='time_of_event_of_max(air_temperature 1M)';
UPDATE cf_element SET element_id='time_of_event_of_max(max(wind_speed PT24H) P1M)' WHERE element_id='time_of_event_of_max(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='time_of_event_of_max(sum(precipitation_amount PT24H) P1M)' WHERE element_id='time_of_event_of_max(sum(precipitation_amount T24H) 1M)';
UPDATE cf_element SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE cf_element SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE cf_element SET element_id='time_of_event_of_min(air_temperature P1M)' WHERE element_id='time_of_event_of_min(air_temperature 1M)';


# --- !Downs
