# --- !Ups

--1.1 update id's in element
UPDATE element SET id='mean(wind_from_direction PT1H)' WHERE id='mean(wind_from_direction T1H)';
UPDATE element SET id='from_direction_of_max(wind_speed_of_gust PT10M)' WHERE id='from_direction_of_max(wind_speed_of_gust T10M)';
UPDATE element SET id='from_direction_of_max(wind_speed_of_gust PT1H)' WHERE id='from_direction_of_max(wind_speed_of_gust T1H)';
UPDATE element SET id='from_direction_of_mean(sea_surface_primary_wave PT20M) ' WHERE id='from_direction_of_mean(sea_surface_primary_wave T20M) ';
UPDATE element SET id='from_direction_of_mean(sea_surface_wave_total_energy PT20M)' WHERE id='from_direction_of_mean(sea_surface_wave_total_energy T20M)';
UPDATE element SET id='from_direction_of_peak(sea_surface_primary_wave PT20M)' WHERE id='from_direction_of_peak(sea_surface_primary_wave T20M)';
UPDATE element SET id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE element SET id='from_direction(sea_surface_swell_wave_first_mean_height PT10M)' WHERE id='from_direction(sea_surface_swell_wave_first_mean_height T10M)';
UPDATE element SET id='from_direction(sea_surface_swell_wave_first_mean_height PT3H)' WHERE id='from_direction(sea_surface_swell_wave_first_mean_height T3H)';
UPDATE element SET id='from_direction(sea_surface_swell_wave_second_mean_height PT3H)' WHERE id='from_direction(sea_surface_swell_wave_second_mean_height T3H)';
UPDATE element SET id='from_direction_of_max(wind_speed PT1H)' WHERE id='from_direction_of_max(wind_speed T1H)';
UPDATE element SET id='from_direction_of_max(wind_speed PT3H)' WHERE id='from_direction_of_max(wind_speed T3H)';
UPDATE element SET id='sum(water_evaporation_amount PT1H)' WHERE id='sum(water_evaporation_amount T1H)';
UPDATE element SET id='max(wind_speed_of_gust PT10M)' WHERE id='max(wind_speed_of_gust T10M)';
UPDATE element SET id='max(wind_speed_of_gust PT20M)' WHERE id='max(wind_speed_of_gust T20M)';
UPDATE element SET id='max(wind_speed_of_gust PT20M)' WHERE id='max(wind_speed_of_gust T20M)';
UPDATE element SET id='max(wind_speed_of_gust PT1H)' WHERE id='max(wind_speed_of_gust T1H)';
UPDATE element SET id='mean(wind_speed PT1H)' WHERE id='mean(wind_speed T1H)';
UPDATE element SET id='max(wind_speed PT10M)' WHERE id='max(wind_speed T10M)';
UPDATE element SET id='max(wind_speed PT3H)' WHERE id='max(wind_speed T3H)';
UPDATE element SET id='max(wind_speed PT6H)' WHERE id='max(wind_speed T6H)';
UPDATE element SET id='max(wind_speed PT20M)' WHERE id='max(wind_speed T20M)';
UPDATE element SET id='max(beaufort_wind_force PT6H)' WHERE id='max(beaufort_wind_force T6H)';
UPDATE element SET id='max(wind_speed PT20M)' WHERE id='max(wind_speed T20M)';
UPDATE element SET id='max(wind_speed PT1H)' WHERE id='max(wind_speed T1H)';
UPDATE element SET id='max(wind_speed PT3H)' WHERE id='max(wind_speed T3H)';
UPDATE element SET id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element SET id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element SET id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element SET id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element SET id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE element SET id='min(cloud_base_height PT1H)' WHERE id='min(cloud_base_height T1H)';
UPDATE element SET id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE element SET id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE element SET id='time_of_event_of_max(wind_speed PT1H)' WHERE id='time_of_event_of_max(wind_speed T1H)';
UPDATE element SET id='time_of_event_of_max(wind_speed PT1H)' WHERE id='time_of_event_of_max(wind_speed T1H)';
UPDATE element SET id='sum(duration_of_sunshine PT1H)' WHERE id='sum(duration_of_sunshine T1H)';
UPDATE element SET id='mean(surface_air_pressure PT1H)' WHERE id='mean(surface_air_pressure T1H)';
UPDATE element SET id='min(surface_air_pressure PT1H)' WHERE id='min(surface_air_pressure T1H)';
UPDATE element SET id='max(surface_air_pressure PT1H)' WHERE id='max(surface_air_pressure T1H)';
UPDATE element SET id='change_over_time(surface_air_pressure PT1H)' WHERE id='change_over_time(surface_air_pressure T1H)';
UPDATE element SET id='change_over_time(surface_air_pressure PT3H)' WHERE id='change_over_time(surface_air_pressure T3H)';
UPDATE element SET id='change_over_time(surface_air_pressure PT6H)' WHERE id='change_over_time(surface_air_pressure T6H)';
UPDATE element SET id='sum(precipitation_amount PT1M)' WHERE id='sum(precipitation_amount T1M)';
UPDATE element SET id='sum(precipitation_amount PT10M)' WHERE id='sum(precipitation_amount T10M)';
UPDATE element SET id='sum(precipitation_amount PT1H)' WHERE id='sum(precipitation_amount T1H)';
UPDATE element SET id='sum(precipitation_amount PT12H)' WHERE id='sum(precipitation_amount T12H)';
UPDATE element SET id='sum(precipitation_amount PT3H)' WHERE id='sum(precipitation_amount T3H)';
UPDATE element SET id='sum(precipitation_amount PT6H)' WHERE id='sum(precipitation_amount T6H)';
UPDATE element SET id='sum_over_undefined_period(precipitation_amount PT1H)' WHERE id='sum_over_undefined_period(precipitation_amount T1H)';
UPDATE element SET id='mean(surface_snow_thickness PT1H)' WHERE id='mean(surface_snow_thickness T1H)';
UPDATE element SET id='min(surface_snow_thickness PT1H)' WHERE id='min(surface_snow_thickness T1H)';
UPDATE element SET id='max(surface_snow_thickness PT1H)' WHERE id='max(surface_snow_thickness T1H)';
UPDATE element SET id='directional_spread(sea_surface_wave_total_energy PT20M)' WHERE id='directional_spread(sea_surface_wave_total_energy T20M)';
UPDATE element SET id='directional_spread(sea_surface_peak_period PT20M)' WHERE id='directional_spread(sea_surface_peak_period T20M)';
UPDATE element SET id='mean(air_temperature PT1H)' WHERE id='mean(air_temperature T1H)';
UPDATE element SET id='min(air_temperature PT10M)' WHERE id='min(air_temperature T10M)';
UPDATE element SET id='min(air_temperature PT1H)' WHERE id='min(air_temperature T1H)';
UPDATE element SET id='min(air_temperature PT12H)' WHERE id='min(air_temperature T12H)';
UPDATE element SET id='max(air_temperature PT10M)' WHERE id='max(air_temperature T10M)';
UPDATE element SET id='max(air_temperature PT1H)' WHERE id='max(air_temperature T1H)';
UPDATE element SET id='max(air_temperature PT12H)' WHERE id='max(air_temperature T12H)';
UPDATE element SET id='mean(grass_temperature PT1H)' WHERE id='mean(grass_temperature T1H)';
UPDATE element SET id='min(grass_temperature PT1H)' WHERE id='min(grass_temperature T1H)';
UPDATE element SET id='min(grass_temperature PT12H)' WHERE id='min(grass_temperature T12H)';
UPDATE element SET id='max(grass_temperature PT1H)' WHERE id='max(grass_temperature T1H)';
UPDATE element SET id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period PT20M)' WHERE id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element SET id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period PT20M)' WHERE id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element SET id='mean(sea_surface_wave_from_direction_of_spectral_peak_period PT20M)' WHERE id='mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element SET id='mean(soil_temperature PT1H)' WHERE id='mean(soil_temperature T1H)';
UPDATE element SET id='max(sea_surface_wave_period PT20M) ' WHERE id='max(sea_surface_wave_period T20M) ';
UPDATE element SET id='mean(sea_surface_temperature PT1H)' WHERE id='mean(sea_surface_temperature T1H)';
UPDATE element SET id='min(sea_surface_temperature PT1H)' WHERE id='min(sea_surface_temperature T1H)';
UPDATE element SET id='max(sea_surface_temperature PT1H)' WHERE id='max(sea_surface_temperature T1H)';
UPDATE element SET id='precipitation_type_primary_significance' WHERE id='weather_type_primary_significance';
UPDATE element SET id='precipitation_type_secondary_significance' WHERE id='weather_type_secondary_significance';
UPDATE element SET id='precipitation_type_tertiary_significance' WHERE id='weather_type_tertiary_significance';
UPDATE element SET id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element SET id='over_time(weather_type_primary_significance PT3H)' WHERE id='over_time(weather_type_primary_significance_wmo T3H)';
UPDATE element SET id='over_time(weather_type_secondary_significance PT3H)' WHERE id='over_time(weather_type_secondary_significance_wmo T3H)';
UPDATE element SET id='over_time(weather_type_additional1 PT6H)' WHERE id='over_time(weather_type_manually_observed_additional1 T6H)';
UPDATE element SET id='over_time(weather_type_additional2 PT6H)' WHERE id='over_time(weather_type_manually_observed_additional2 T6H)';
UPDATE element SET id='over_time(weather_type_additional3 PT6H)' WHERE id='over_time(weather_type_manually_observed_additional3 T6H)';
UPDATE element SET id='from_direction_of_mean(sea_surface_primary_wave PT10M)' WHERE id='from_direction_of_mean(sea_surface_primary_wave T10M)';
UPDATE element SET id='from_direction_of_mean(sea_surface_secondary_wave PT10M)' WHERE id='from_direction_of_mean(sea_surface_secondary_wave T10M)';
UPDATE element SET id='from_direction_of_mean(sea_surface_wave_total_energy PT10M)' WHERE id='from_direction_of_mean(sea_surface_wave_total_energy T10M)';
UPDATE element SET id='from_direction_of_peak(sea_surface_secondary_wave PT10M)' WHERE id='from_direction_of_peak(sea_surface_secondary_wave T10M)';
UPDATE element SET id='from_direction_of_peak(sea_surface_wave_total_energy PT10M)' WHERE id='from_direction_of_peak(sea_surface_wave_total_energy T10M)';
UPDATE element SET id='max(sea_surface_wave_height PT10M)' WHERE id='max(sea_surface_wave_height T10M)';
UPDATE element SET id='max(sea_surface_wave_height PT20M)' WHERE id='max(sea_surface_wave_height T20M)';
UPDATE element SET id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period PT10M)' WHERE id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)';

--1.2 UPDATE element_name id's 
UPDATE element_name SET element_id='mean(wind_from_direction PT1H)' WHERE element_id='mean(wind_from_direction T1H)';
UPDATE element_name SET element_id='from_direction_of_max(wind_speed_of_gust PT10M)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T10M)';
UPDATE element_name SET element_id='from_direction_of_max(wind_speed_of_gust PT1H)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T1H)';
UPDATE element_name SET element_id='from_direction_of_mean(sea_surface_primary_wave PT20M) ' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T20M) ';
UPDATE element_name SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT20M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T20M)';
UPDATE element_name SET element_id='from_direction_of_peak(sea_surface_primary_wave PT20M)' WHERE element_id='from_direction_of_peak(sea_surface_primary_wave T20M)';
UPDATE element_name SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE element_name SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT10M)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T10M)';
UPDATE element_name SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T3H)';
UPDATE element_name SET element_id='from_direction(sea_surface_swell_wave_second_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_second_mean_height T3H)';
UPDATE element_name SET element_id='from_direction_of_max(wind_speed PT1H)' WHERE element_id='from_direction_of_max(wind_speed T1H)';
UPDATE element_name SET element_id='from_direction_of_max(wind_speed PT3H)' WHERE element_id='from_direction_of_max(wind_speed T3H)';
UPDATE element_name SET element_id='sum(water_evaporation_amount PT1H)' WHERE element_id='sum(water_evaporation_amount T1H)';
UPDATE element_name SET element_id='max(wind_speed_of_gust PT10M)' WHERE element_id='max(wind_speed_of_gust T10M)';
UPDATE element_name SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE element_name SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE element_name SET element_id='max(wind_speed_of_gust PT1H)' WHERE element_id='max(wind_speed_of_gust T1H)';
UPDATE element_name SET element_id='mean(wind_speed PT1H)' WHERE element_id='mean(wind_speed T1H)';
UPDATE element_name SET element_id='max(wind_speed PT10M)' WHERE element_id='max(wind_speed T10M)';
UPDATE element_name SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE element_name SET element_id='max(wind_speed PT6H)' WHERE element_id='max(wind_speed T6H)';
UPDATE element_name SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE element_name SET element_id='max(beaufort_wind_force PT6H)' WHERE element_id='max(beaufort_wind_force T6H)';
UPDATE element_name SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE element_name SET element_id='max(wind_speed PT1H)' WHERE element_id='max(wind_speed T1H)';
UPDATE element_name SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE element_name SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_name SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_name SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_name SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_name SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_name SET element_id='min(cloud_base_height PT1H)' WHERE element_id='min(cloud_base_height T1H)';
UPDATE element_name SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE element_name SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE element_name SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE element_name SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE element_name SET element_id='sum(duration_of_sunshine PT1H)' WHERE element_id='sum(duration_of_sunshine T1H)';
UPDATE element_name SET element_id='mean(surface_air_pressure PT1H)' WHERE element_id='mean(surface_air_pressure T1H)';
UPDATE element_name SET element_id='min(surface_air_pressure PT1H)' WHERE element_id='min(surface_air_pressure T1H)';
UPDATE element_name SET element_id='max(surface_air_pressure PT1H)' WHERE element_id='max(surface_air_pressure T1H)';
UPDATE element_name SET element_id='change_over_time(surface_air_pressure PT1H)' WHERE element_id='change_over_time(surface_air_pressure T1H)';
UPDATE element_name SET element_id='change_over_time(surface_air_pressure PT3H)' WHERE element_id='change_over_time(surface_air_pressure T3H)';
UPDATE element_name SET element_id='change_over_time(surface_air_pressure PT6H)' WHERE element_id='change_over_time(surface_air_pressure T6H)';
UPDATE element_name SET element_id='sum(precipitation_amount PT1M)' WHERE element_id='sum(precipitation_amount T1M)';
UPDATE element_name SET element_id='sum(precipitation_amount PT10M)' WHERE element_id='sum(precipitation_amount T10M)';
UPDATE element_name SET element_id='sum(precipitation_amount PT1H)' WHERE element_id='sum(precipitation_amount T1H)';
UPDATE element_name SET element_id='sum(precipitation_amount PT12H)' WHERE element_id='sum(precipitation_amount T12H)';
UPDATE element_name SET element_id='sum(precipitation_amount PT3H)' WHERE element_id='sum(precipitation_amount T3H)';
UPDATE element_name SET element_id='sum(precipitation_amount PT6H)' WHERE element_id='sum(precipitation_amount T6H)';
UPDATE element_name SET element_id='sum_over_undefined_period(precipitation_amount PT1H)' WHERE element_id='sum_over_undefined_period(precipitation_amount T1H)';
UPDATE element_name SET element_id='mean(surface_snow_thickness PT1H)' WHERE element_id='mean(surface_snow_thickness T1H)';
UPDATE element_name SET element_id='min(surface_snow_thickness PT1H)' WHERE element_id='min(surface_snow_thickness T1H)';
UPDATE element_name SET element_id='max(surface_snow_thickness PT1H)' WHERE element_id='max(surface_snow_thickness T1H)';
UPDATE element_name SET element_id='directional_spread(sea_surface_wave_total_energy PT20M)' WHERE element_id='directional_spread(sea_surface_wave_total_energy T20M)';
UPDATE element_name SET element_id='directional_spread(sea_surface_peak_period PT20M)' WHERE element_id='directional_spread(sea_surface_peak_period T20M)';
UPDATE element_name SET element_id='mean(air_temperature PT1H)' WHERE element_id='mean(air_temperature T1H)';
UPDATE element_name SET element_id='min(air_temperature PT10M)' WHERE element_id='min(air_temperature T10M)';
UPDATE element_name SET element_id='min(air_temperature PT1H)' WHERE element_id='min(air_temperature T1H)';
UPDATE element_name SET element_id='min(air_temperature PT12H)' WHERE element_id='min(air_temperature T12H)';
UPDATE element_name SET element_id='max(air_temperature PT10M)' WHERE element_id='max(air_temperature T10M)';
UPDATE element_name SET element_id='max(air_temperature PT1H)' WHERE element_id='max(air_temperature T1H)';
UPDATE element_name SET element_id='max(air_temperature PT12H)' WHERE element_id='max(air_temperature T12H)';
UPDATE element_name SET element_id='mean(grass_temperature PT1H)' WHERE element_id='mean(grass_temperature T1H)';
UPDATE element_name SET element_id='min(grass_temperature PT1H)' WHERE element_id='min(grass_temperature T1H)';
UPDATE element_name SET element_id='min(grass_temperature PT12H)' WHERE element_id='min(grass_temperature T12H)';
UPDATE element_name SET element_id='max(grass_temperature PT1H)' WHERE element_id='max(grass_temperature T1H)';
UPDATE element_name SET element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element_name SET element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element_name SET element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element_name SET element_id='mean(soil_temperature PT1H)' WHERE element_id='mean(soil_temperature T1H)';
UPDATE element_name SET element_id='max(sea_surface_wave_period PT20M) ' WHERE element_id='max(sea_surface_wave_period T20M) ';
UPDATE element_name SET element_id='mean(sea_surface_temperature PT1H)' WHERE element_id='mean(sea_surface_temperature T1H)';
UPDATE element_name SET element_id='min(sea_surface_temperature PT1H)' WHERE element_id='min(sea_surface_temperature T1H)';
UPDATE element_name SET element_id='max(sea_surface_temperature PT1H)' WHERE element_id='max(sea_surface_temperature T1H)';
UPDATE element_name SET element_id='precipitation_type_primary_significance' WHERE element_id='weather_type_primary_significance';
UPDATE element_name SET element_id='precipitation_type_secondary_significance' WHERE element_id='weather_type_secondary_significance';
UPDATE element_name SET element_id='precipitation_type_tertiary_significance' WHERE element_id='weather_type_tertiary_significance';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_name SET element_id='over_time(weather_type_primary_significance PT3H)' WHERE element_id='over_time(weather_type_primary_significance_wmo T3H)';
UPDATE element_name SET element_id='over_time(weather_type_secondary_significance PT3H)' WHERE element_id='over_time(weather_type_secondary_significance_wmo T3H)';
UPDATE element_name SET element_id='over_time(weather_type_additional1 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional1 T6H)';
UPDATE element_name SET element_id='over_time(weather_type_additional2 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional2 T6H)';
UPDATE element_name SET element_id='over_time(weather_type_additional3 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional3 T6H)';
UPDATE element_name SET element_id='from_direction_of_mean(sea_surface_primary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T10M)';
UPDATE element_name SET element_id='from_direction_of_mean(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_secondary_wave T10M)';
UPDATE element_name SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T10M)';
UPDATE element_name SET element_id='from_direction_of_peak(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_secondary_wave T10M)';
UPDATE element_name SET element_id='from_direction_of_peak(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_wave_total_energy T10M)';
UPDATE element_name SET element_id='max(sea_surface_wave_height PT10M)' WHERE element_id='max(sea_surface_wave_height T10M)';
UPDATE element_name SET element_id='max(sea_surface_wave_height PT20M)' WHERE element_id='max(sea_surface_wave_height T20M)';
UPDATE element_name SET element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period PT10M)' WHERE element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)';

--1.3 UPDATE element_description id's 
UPDATE element_description SET element_id='mean(wind_from_direction PT1H)' WHERE element_id='mean(wind_from_direction T1H)';
UPDATE element_description SET element_id='from_direction_of_max(wind_speed_of_gust PT10M)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T10M)';
UPDATE element_description SET element_id='from_direction_of_max(wind_speed_of_gust PT1H)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T1H)';
UPDATE element_description SET element_id='from_direction_of_mean(sea_surface_primary_wave PT20M) ' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T20M) ';
UPDATE element_description SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT20M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T20M)';
UPDATE element_description SET element_id='from_direction_of_peak(sea_surface_primary_wave PT20M)' WHERE element_id='from_direction_of_peak(sea_surface_primary_wave T20M)';
UPDATE element_description SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE element_description SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT10M)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T10M)';
UPDATE element_description SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T3H)';
UPDATE element_description SET element_id='from_direction(sea_surface_swell_wave_second_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_second_mean_height T3H)';
UPDATE element_description SET element_id='from_direction_of_max(wind_speed PT1H)' WHERE element_id='from_direction_of_max(wind_speed T1H)';
UPDATE element_description SET element_id='from_direction_of_max(wind_speed PT3H)' WHERE element_id='from_direction_of_max(wind_speed T3H)';
UPDATE element_description SET element_id='sum(water_evaporation_amount PT1H)' WHERE element_id='sum(water_evaporation_amount T1H)';
UPDATE element_description SET element_id='max(wind_speed_of_gust PT10M)' WHERE element_id='max(wind_speed_of_gust T10M)';
UPDATE element_description SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE element_description SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE element_description SET element_id='max(wind_speed_of_gust PT1H)' WHERE element_id='max(wind_speed_of_gust T1H)';
UPDATE element_description SET element_id='mean(wind_speed PT1H)' WHERE element_id='mean(wind_speed T1H)';
UPDATE element_description SET element_id='max(wind_speed PT10M)' WHERE element_id='max(wind_speed T10M)';
UPDATE element_description SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE element_description SET element_id='max(wind_speed PT6H)' WHERE element_id='max(wind_speed T6H)';
UPDATE element_description SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE element_description SET element_id='max(beaufort_wind_force PT6H)' WHERE element_id='max(beaufort_wind_force T6H)';
UPDATE element_description SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE element_description SET element_id='max(wind_speed PT1H)' WHERE element_id='max(wind_speed T1H)';
UPDATE element_description SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE element_description SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_description SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_description SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_description SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_description SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_description SET element_id='min(cloud_base_height PT1H)' WHERE element_id='min(cloud_base_height T1H)';
UPDATE element_description SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE element_description SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE element_description SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE element_description SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE element_description SET element_id='sum(duration_of_sunshine PT1H)' WHERE element_id='sum(duration_of_sunshine T1H)';
UPDATE element_description SET element_id='mean(surface_air_pressure PT1H)' WHERE element_id='mean(surface_air_pressure T1H)';
UPDATE element_description SET element_id='min(surface_air_pressure PT1H)' WHERE element_id='min(surface_air_pressure T1H)';
UPDATE element_description SET element_id='max(surface_air_pressure PT1H)' WHERE element_id='max(surface_air_pressure T1H)';
UPDATE element_description SET element_id='change_over_time(surface_air_pressure PT1H)' WHERE element_id='change_over_time(surface_air_pressure T1H)';
UPDATE element_description SET element_id='change_over_time(surface_air_pressure PT3H)' WHERE element_id='change_over_time(surface_air_pressure T3H)';
UPDATE element_description SET element_id='change_over_time(surface_air_pressure PT6H)' WHERE element_id='change_over_time(surface_air_pressure T6H)';
UPDATE element_description SET element_id='sum(precipitation_amount PT1M)' WHERE element_id='sum(precipitation_amount T1M)';
UPDATE element_description SET element_id='sum(precipitation_amount PT10M)' WHERE element_id='sum(precipitation_amount T10M)';
UPDATE element_description SET element_id='sum(precipitation_amount PT1H)' WHERE element_id='sum(precipitation_amount T1H)';
UPDATE element_description SET element_id='sum(precipitation_amount PT12H)' WHERE element_id='sum(precipitation_amount T12H)';
UPDATE element_description SET element_id='sum(precipitation_amount PT3H)' WHERE element_id='sum(precipitation_amount T3H)';
UPDATE element_description SET element_id='sum(precipitation_amount PT6H)' WHERE element_id='sum(precipitation_amount T6H)';
UPDATE element_description SET element_id='sum_over_undefined_period(precipitation_amount PT1H)' WHERE element_id='sum_over_undefined_period(precipitation_amount T1H)';
UPDATE element_description SET element_id='mean(surface_snow_thickness PT1H)' WHERE element_id='mean(surface_snow_thickness T1H)';
UPDATE element_description SET element_id='min(surface_snow_thickness PT1H)' WHERE element_id='min(surface_snow_thickness T1H)';
UPDATE element_description SET element_id='max(surface_snow_thickness PT1H)' WHERE element_id='max(surface_snow_thickness T1H)';
UPDATE element_description SET element_id='directional_spread(sea_surface_wave_total_energy PT20M)' WHERE element_id='directional_spread(sea_surface_wave_total_energy T20M)';
UPDATE element_description SET element_id='directional_spread(sea_surface_peak_period PT20M)' WHERE element_id='directional_spread(sea_surface_peak_period T20M)';
UPDATE element_description SET element_id='mean(air_temperature PT1H)' WHERE element_id='mean(air_temperature T1H)';
UPDATE element_description SET element_id='min(air_temperature PT10M)' WHERE element_id='min(air_temperature T10M)';
UPDATE element_description SET element_id='min(air_temperature PT1H)' WHERE element_id='min(air_temperature T1H)';
UPDATE element_description SET element_id='min(air_temperature PT12H)' WHERE element_id='min(air_temperature T12H)';
UPDATE element_description SET element_id='max(air_temperature PT10M)' WHERE element_id='max(air_temperature T10M)';
UPDATE element_description SET element_id='max(air_temperature PT1H)' WHERE element_id='max(air_temperature T1H)';
UPDATE element_description SET element_id='max(air_temperature PT12H)' WHERE element_id='max(air_temperature T12H)';
UPDATE element_description SET element_id='mean(grass_temperature PT1H)' WHERE element_id='mean(grass_temperature T1H)';
UPDATE element_description SET element_id='min(grass_temperature PT1H)' WHERE element_id='min(grass_temperature T1H)';
UPDATE element_description SET element_id='min(grass_temperature PT12H)' WHERE element_id='min(grass_temperature T12H)';
UPDATE element_description SET element_id='max(grass_temperature PT1H)' WHERE element_id='max(grass_temperature T1H)';
UPDATE element_description SET element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element_description SET element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element_description SET element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element_description SET element_id='mean(soil_temperature PT1H)' WHERE element_id='mean(soil_temperature T1H)';
UPDATE element_description SET element_id='max(sea_surface_wave_period PT20M) ' WHERE element_id='max(sea_surface_wave_period T20M) ';
UPDATE element_description SET element_id='mean(sea_surface_temperature PT1H)' WHERE element_id='mean(sea_surface_temperature T1H)';
UPDATE element_description SET element_id='min(sea_surface_temperature PT1H)' WHERE element_id='min(sea_surface_temperature T1H)';
UPDATE element_description SET element_id='max(sea_surface_temperature PT1H)' WHERE element_id='max(sea_surface_temperature T1H)';
UPDATE element_description SET element_id='precipitation_type_primary_significance' WHERE element_id='weather_type_primary_significance';
UPDATE element_description SET element_id='precipitation_type_secondary_significance' WHERE element_id='weather_type_secondary_significance';
UPDATE element_description SET element_id='precipitation_type_tertiary_significance' WHERE element_id='weather_type_tertiary_significance';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_description SET element_id='over_time(weather_type_primary_significance PT3H)' WHERE element_id='over_time(weather_type_primary_significance_wmo T3H)';
UPDATE element_description SET element_id='over_time(weather_type_secondary_significance PT3H)' WHERE element_id='over_time(weather_type_secondary_significance_wmo T3H)';
UPDATE element_description SET element_id='over_time(weather_type_additional1 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional1 T6H)';
UPDATE element_description SET element_id='over_time(weather_type_additional2 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional2 T6H)';
UPDATE element_description SET element_id='over_time(weather_type_additional3 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional3 T6H)';
UPDATE element_description SET element_id='from_direction_of_mean(sea_surface_primary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T10M)';
UPDATE element_description SET element_id='from_direction_of_mean(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_secondary_wave T10M)';
UPDATE element_description SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T10M)';
UPDATE element_description SET element_id='from_direction_of_peak(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_secondary_wave T10M)';
UPDATE element_description SET element_id='from_direction_of_peak(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_wave_total_energy T10M)';
UPDATE element_description SET element_id='max(sea_surface_wave_height PT10M)' WHERE element_id='max(sea_surface_wave_height T10M)';
UPDATE element_description SET element_id='max(sea_surface_wave_height PT20M)' WHERE element_id='max(sea_surface_wave_height T20M)';
UPDATE element_description SET element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period PT10M)' WHERE element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)';

--1.4 UPDATE element_codetable id's 
UPDATE element_codetable SET element_id='mean(wind_from_direction PT1H)' WHERE element_id='mean(wind_from_direction T1H)';
UPDATE element_codetable SET element_id='from_direction_of_max(wind_speed_of_gust PT10M)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T10M)';
UPDATE element_codetable SET element_id='from_direction_of_max(wind_speed_of_gust PT1H)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T1H)';
UPDATE element_codetable SET element_id='from_direction_of_mean(sea_surface_primary_wave PT20M) ' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T20M) ';
UPDATE element_codetable SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT20M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T20M)';
UPDATE element_codetable SET element_id='from_direction_of_peak(sea_surface_primary_wave PT20M)' WHERE element_id='from_direction_of_peak(sea_surface_primary_wave T20M)';
UPDATE element_codetable SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE element_codetable SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT10M)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T10M)';
UPDATE element_codetable SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T3H)';
UPDATE element_codetable SET element_id='from_direction(sea_surface_swell_wave_second_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_second_mean_height T3H)';
UPDATE element_codetable SET element_id='from_direction_of_max(wind_speed PT1H)' WHERE element_id='from_direction_of_max(wind_speed T1H)';
UPDATE element_codetable SET element_id='from_direction_of_max(wind_speed PT3H)' WHERE element_id='from_direction_of_max(wind_speed T3H)';
UPDATE element_codetable SET element_id='sum(water_evaporation_amount PT1H)' WHERE element_id='sum(water_evaporation_amount T1H)';
UPDATE element_codetable SET element_id='max(wind_speed_of_gust PT10M)' WHERE element_id='max(wind_speed_of_gust T10M)';
UPDATE element_codetable SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE element_codetable SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE element_codetable SET element_id='max(wind_speed_of_gust PT1H)' WHERE element_id='max(wind_speed_of_gust T1H)';
UPDATE element_codetable SET element_id='mean(wind_speed PT1H)' WHERE element_id='mean(wind_speed T1H)';
UPDATE element_codetable SET element_id='max(wind_speed PT10M)' WHERE element_id='max(wind_speed T10M)';
UPDATE element_codetable SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE element_codetable SET element_id='max(wind_speed PT6H)' WHERE element_id='max(wind_speed T6H)';
UPDATE element_codetable SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE element_codetable SET element_id='max(beaufort_wind_force PT6H)' WHERE element_id='max(beaufort_wind_force T6H)';
UPDATE element_codetable SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE element_codetable SET element_id='max(wind_speed PT1H)' WHERE element_id='max(wind_speed T1H)';
UPDATE element_codetable SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE element_codetable SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_codetable SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_codetable SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_codetable SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_codetable SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_codetable SET element_id='min(cloud_base_height PT1H)' WHERE element_id='min(cloud_base_height T1H)';
UPDATE element_codetable SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE element_codetable SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE element_codetable SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE element_codetable SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE element_codetable SET element_id='sum(duration_of_sunshine PT1H)' WHERE element_id='sum(duration_of_sunshine T1H)';
UPDATE element_codetable SET element_id='mean(surface_air_pressure PT1H)' WHERE element_id='mean(surface_air_pressure T1H)';
UPDATE element_codetable SET element_id='min(surface_air_pressure PT1H)' WHERE element_id='min(surface_air_pressure T1H)';
UPDATE element_codetable SET element_id='max(surface_air_pressure PT1H)' WHERE element_id='max(surface_air_pressure T1H)';
UPDATE element_codetable SET element_id='change_over_time(surface_air_pressure PT1H)' WHERE element_id='change_over_time(surface_air_pressure T1H)';
UPDATE element_codetable SET element_id='change_over_time(surface_air_pressure PT3H)' WHERE element_id='change_over_time(surface_air_pressure T3H)';
UPDATE element_codetable SET element_id='change_over_time(surface_air_pressure PT6H)' WHERE element_id='change_over_time(surface_air_pressure T6H)';
UPDATE element_codetable SET element_id='sum(precipitation_amount PT1M)' WHERE element_id='sum(precipitation_amount T1M)';
UPDATE element_codetable SET element_id='sum(precipitation_amount PT10M)' WHERE element_id='sum(precipitation_amount T10M)';
UPDATE element_codetable SET element_id='sum(precipitation_amount PT1H)' WHERE element_id='sum(precipitation_amount T1H)';
UPDATE element_codetable SET element_id='sum(precipitation_amount PT12H)' WHERE element_id='sum(precipitation_amount T12H)';
UPDATE element_codetable SET element_id='sum(precipitation_amount PT3H)' WHERE element_id='sum(precipitation_amount T3H)';
UPDATE element_codetable SET element_id='sum(precipitation_amount PT6H)' WHERE element_id='sum(precipitation_amount T6H)';
UPDATE element_codetable SET element_id='sum_over_undefined_period(precipitation_amount PT1H)' WHERE element_id='sum_over_undefined_period(precipitation_amount T1H)';
UPDATE element_codetable SET element_id='mean(surface_snow_thickness PT1H)' WHERE element_id='mean(surface_snow_thickness T1H)';
UPDATE element_codetable SET element_id='min(surface_snow_thickness PT1H)' WHERE element_id='min(surface_snow_thickness T1H)';
UPDATE element_codetable SET element_id='max(surface_snow_thickness PT1H)' WHERE element_id='max(surface_snow_thickness T1H)';
UPDATE element_codetable SET element_id='directional_spread(sea_surface_wave_total_energy PT20M)' WHERE element_id='directional_spread(sea_surface_wave_total_energy T20M)';
UPDATE element_codetable SET element_id='directional_spread(sea_surface_peak_period PT20M)' WHERE element_id='directional_spread(sea_surface_peak_period T20M)';
UPDATE element_codetable SET element_id='mean(air_temperature PT1H)' WHERE element_id='mean(air_temperature T1H)';
UPDATE element_codetable SET element_id='min(air_temperature PT10M)' WHERE element_id='min(air_temperature T10M)';
UPDATE element_codetable SET element_id='min(air_temperature PT1H)' WHERE element_id='min(air_temperature T1H)';
UPDATE element_codetable SET element_id='min(air_temperature PT12H)' WHERE element_id='min(air_temperature T12H)';
UPDATE element_codetable SET element_id='max(air_temperature PT10M)' WHERE element_id='max(air_temperature T10M)';
UPDATE element_codetable SET element_id='max(air_temperature PT1H)' WHERE element_id='max(air_temperature T1H)';
UPDATE element_codetable SET element_id='max(air_temperature PT12H)' WHERE element_id='max(air_temperature T12H)';
UPDATE element_codetable SET element_id='mean(grass_temperature PT1H)' WHERE element_id='mean(grass_temperature T1H)';
UPDATE element_codetable SET element_id='min(grass_temperature PT1H)' WHERE element_id='min(grass_temperature T1H)';
UPDATE element_codetable SET element_id='min(grass_temperature PT12H)' WHERE element_id='min(grass_temperature T12H)';
UPDATE element_codetable SET element_id='max(grass_temperature PT1H)' WHERE element_id='max(grass_temperature T1H)';
UPDATE element_codetable SET element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element_codetable SET element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element_codetable SET element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE element_codetable SET element_id='mean(soil_temperature PT1H)' WHERE element_id='mean(soil_temperature T1H)';
UPDATE element_codetable SET element_id='max(sea_surface_wave_period PT20M) ' WHERE element_id='max(sea_surface_wave_period T20M) ';
UPDATE element_codetable SET element_id='mean(sea_surface_temperature PT1H)' WHERE element_id='mean(sea_surface_temperature T1H)';
UPDATE element_codetable SET element_id='min(sea_surface_temperature PT1H)' WHERE element_id='min(sea_surface_temperature T1H)';
UPDATE element_codetable SET element_id='max(sea_surface_temperature PT1H)' WHERE element_id='max(sea_surface_temperature T1H)';
UPDATE element_codetable SET element_id='precipitation_type_primary_significance' WHERE element_id='weather_type_primary_significance';
UPDATE element_codetable SET element_id='precipitation_type_secondary_significance' WHERE element_id='weather_type_secondary_significance';
UPDATE element_codetable SET element_id='precipitation_type_tertiary_significance' WHERE element_id='weather_type_tertiary_significance';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_codetable SET element_id='over_time(weather_type_primary_significance PT3H)' WHERE element_id='over_time(weather_type_primary_significance_wmo T3H)';
UPDATE element_codetable SET element_id='over_time(weather_type_secondary_significance PT3H)' WHERE element_id='over_time(weather_type_secondary_significance_wmo T3H)';
UPDATE element_codetable SET element_id='over_time(weather_type_additional1 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional1 T6H)';
UPDATE element_codetable SET element_id='over_time(weather_type_additional2 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional2 T6H)';
UPDATE element_codetable SET element_id='over_time(weather_type_additional3 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional3 T6H)';
UPDATE element_codetable SET element_id='from_direction_of_mean(sea_surface_primary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T10M)';
UPDATE element_codetable SET element_id='from_direction_of_mean(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_secondary_wave T10M)';
UPDATE element_codetable SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T10M)';
UPDATE element_codetable SET element_id='from_direction_of_peak(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_secondary_wave T10M)';
UPDATE element_codetable SET element_id='from_direction_of_peak(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_wave_total_energy T10M)';
UPDATE element_codetable SET element_id='max(sea_surface_wave_height PT10M)' WHERE element_id='max(sea_surface_wave_height T10M)';
UPDATE element_codetable SET element_id='max(sea_surface_wave_height PT20M)' WHERE element_id='max(sea_surface_wave_height T20M)';
UPDATE element_codetable SET element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period PT10M)' WHERE element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)';

--1.5 UPDATE cf_element id's 
UPDATE cf_element SET element_id='mean(wind_from_direction PT1H)' WHERE element_id='mean(wind_from_direction T1H)';
UPDATE cf_element SET element_id='from_direction_of_max(wind_speed_of_gust PT10M)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T10M)';
UPDATE cf_element SET element_id='from_direction_of_max(wind_speed_of_gust PT1H)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T1H)';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_primary_wave PT20M) ' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T20M) ';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT20M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T20M)';
UPDATE cf_element SET element_id='from_direction_of_peak(sea_surface_primary_wave PT20M)' WHERE element_id='from_direction_of_peak(sea_surface_primary_wave T20M)';
UPDATE cf_element SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE cf_element SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT10M)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T10M)';
UPDATE cf_element SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T3H)';
UPDATE cf_element SET element_id='from_direction(sea_surface_swell_wave_second_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_second_mean_height T3H)';
UPDATE cf_element SET element_id='from_direction_of_max(wind_speed PT1H)' WHERE element_id='from_direction_of_max(wind_speed T1H)';
UPDATE cf_element SET element_id='from_direction_of_max(wind_speed PT3H)' WHERE element_id='from_direction_of_max(wind_speed T3H)';
UPDATE cf_element SET element_id='sum(water_evaporation_amount PT1H)' WHERE element_id='sum(water_evaporation_amount T1H)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust PT10M)' WHERE element_id='max(wind_speed_of_gust T10M)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust PT1H)' WHERE element_id='max(wind_speed_of_gust T1H)';
UPDATE cf_element SET element_id='mean(wind_speed PT1H)' WHERE element_id='mean(wind_speed T1H)';
UPDATE cf_element SET element_id='max(wind_speed PT10M)' WHERE element_id='max(wind_speed T10M)';
UPDATE cf_element SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE cf_element SET element_id='max(wind_speed PT6H)' WHERE element_id='max(wind_speed T6H)';
UPDATE cf_element SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE cf_element SET element_id='max(beaufort_wind_force PT6H)' WHERE element_id='max(beaufort_wind_force T6H)';
UPDATE cf_element SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE cf_element SET element_id='max(wind_speed PT1H)' WHERE element_id='max(wind_speed T1H)';
UPDATE cf_element SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE cf_element SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE cf_element SET element_id='min(cloud_base_height PT1H)' WHERE element_id='min(cloud_base_height T1H)';
UPDATE cf_element SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE cf_element SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE cf_element SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE cf_element SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE cf_element SET element_id='sum(duration_of_sunshine PT1H)' WHERE element_id='sum(duration_of_sunshine T1H)';
UPDATE cf_element SET element_id='mean(surface_air_pressure PT1H)' WHERE element_id='mean(surface_air_pressure T1H)';
UPDATE cf_element SET element_id='min(surface_air_pressure PT1H)' WHERE element_id='min(surface_air_pressure T1H)';
UPDATE cf_element SET element_id='max(surface_air_pressure PT1H)' WHERE element_id='max(surface_air_pressure T1H)';
UPDATE cf_element SET element_id='change_over_time(surface_air_pressure PT1H)' WHERE element_id='change_over_time(surface_air_pressure T1H)';
UPDATE cf_element SET element_id='change_over_time(surface_air_pressure PT3H)' WHERE element_id='change_over_time(surface_air_pressure T3H)';
UPDATE cf_element SET element_id='change_over_time(surface_air_pressure PT6H)' WHERE element_id='change_over_time(surface_air_pressure T6H)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT1M)' WHERE element_id='sum(precipitation_amount T1M)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT10M)' WHERE element_id='sum(precipitation_amount T10M)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT1H)' WHERE element_id='sum(precipitation_amount T1H)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT12H)' WHERE element_id='sum(precipitation_amount T12H)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT3H)' WHERE element_id='sum(precipitation_amount T3H)';
UPDATE cf_element SET element_id='sum(precipitation_amount PT6H)' WHERE element_id='sum(precipitation_amount T6H)';
UPDATE cf_element SET element_id='sum_over_undefined_period(precipitation_amount PT1H)' WHERE element_id='sum_over_undefined_period(precipitation_amount T1H)';
UPDATE cf_element SET element_id='mean(surface_snow_thickness PT1H)' WHERE element_id='mean(surface_snow_thickness T1H)';
UPDATE cf_element SET element_id='min(surface_snow_thickness PT1H)' WHERE element_id='min(surface_snow_thickness T1H)';
UPDATE cf_element SET element_id='max(surface_snow_thickness PT1H)' WHERE element_id='max(surface_snow_thickness T1H)';
UPDATE cf_element SET element_id='directional_spread(sea_surface_wave_total_energy PT20M)' WHERE element_id='directional_spread(sea_surface_wave_total_energy T20M)';
UPDATE cf_element SET element_id='directional_spread(sea_surface_peak_period PT20M)' WHERE element_id='directional_spread(sea_surface_peak_period T20M)';
UPDATE cf_element SET element_id='mean(air_temperature PT1H)' WHERE element_id='mean(air_temperature T1H)';
UPDATE cf_element SET element_id='min(air_temperature PT10M)' WHERE element_id='min(air_temperature T10M)';
UPDATE cf_element SET element_id='min(air_temperature PT1H)' WHERE element_id='min(air_temperature T1H)';
UPDATE cf_element SET element_id='min(air_temperature PT12H)' WHERE element_id='min(air_temperature T12H)';
UPDATE cf_element SET element_id='max(air_temperature PT10M)' WHERE element_id='max(air_temperature T10M)';
UPDATE cf_element SET element_id='max(air_temperature PT1H)' WHERE element_id='max(air_temperature T1H)';
UPDATE cf_element SET element_id='max(air_temperature PT12H)' WHERE element_id='max(air_temperature T12H)';
UPDATE cf_element SET element_id='mean(grass_temperature PT1H)' WHERE element_id='mean(grass_temperature T1H)';
UPDATE cf_element SET element_id='min(grass_temperature PT1H)' WHERE element_id='min(grass_temperature T1H)';
UPDATE cf_element SET element_id='min(grass_temperature PT12H)' WHERE element_id='min(grass_temperature T12H)';
UPDATE cf_element SET element_id='max(grass_temperature PT1H)' WHERE element_id='max(grass_temperature T1H)';
UPDATE cf_element SET element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE cf_element SET element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE cf_element SET element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE cf_element SET element_id='mean(soil_temperature PT1H)' WHERE element_id='mean(soil_temperature T1H)';
UPDATE cf_element SET element_id='max(sea_surface_wave_period PT20M) ' WHERE element_id='max(sea_surface_wave_period T20M) ';
UPDATE cf_element SET element_id='mean(sea_surface_temperature PT1H)' WHERE element_id='mean(sea_surface_temperature T1H)';
UPDATE cf_element SET element_id='min(sea_surface_temperature PT1H)' WHERE element_id='min(sea_surface_temperature T1H)';
UPDATE cf_element SET element_id='max(sea_surface_temperature PT1H)' WHERE element_id='max(sea_surface_temperature T1H)';
UPDATE cf_element SET element_id='precipitation_type_primary_significance' WHERE element_id='weather_type_primary_significance';
UPDATE cf_element SET element_id='precipitation_type_secondary_significance' WHERE element_id='weather_type_secondary_significance';
UPDATE cf_element SET element_id='precipitation_type_tertiary_significance' WHERE element_id='weather_type_tertiary_significance';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE cf_element SET element_id='over_time(weather_type_primary_significance PT3H)' WHERE element_id='over_time(weather_type_primary_significance_wmo T3H)';
UPDATE cf_element SET element_id='over_time(weather_type_secondary_significance PT3H)' WHERE element_id='over_time(weather_type_secondary_significance_wmo T3H)';
UPDATE cf_element SET element_id='over_time(weather_type_additional1 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional1 T6H)';
UPDATE cf_element SET element_id='over_time(weather_type_additional2 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional2 T6H)';
UPDATE cf_element SET element_id='over_time(weather_type_additional3 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional3 T6H)';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_primary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T10M)';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_secondary_wave T10M)';
UPDATE cf_element SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T10M)';
UPDATE cf_element SET element_id='from_direction_of_peak(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_secondary_wave T10M)';
UPDATE cf_element SET element_id='from_direction_of_peak(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_wave_total_energy T10M)';
UPDATE cf_element SET element_id='max(sea_surface_wave_height PT10M)' WHERE element_id='max(sea_surface_wave_height T10M)';
UPDATE cf_element SET element_id='max(sea_surface_wave_height PT20M)' WHERE element_id='max(sea_surface_wave_height T20M)';
UPDATE cf_element SET element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period PT10M)' WHERE element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)';

--1.6 UPDATE kdvh_element id's 
UPDATE kdvh_element SET element_id='mean(wind_from_direction PT1H)' WHERE element_id='mean(wind_from_direction T1H)';
UPDATE kdvh_element SET element_id='from_direction_of_max(wind_speed_of_gust PT10M)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T10M)';
UPDATE kdvh_element SET element_id='from_direction_of_max(wind_speed_of_gust PT1H)' WHERE element_id='from_direction_of_max(wind_speed_of_gust T1H)';
UPDATE kdvh_element SET element_id='from_direction_of_mean(sea_surface_primary_wave PT20M) ' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T20M) ';
UPDATE kdvh_element SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT20M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T20M)';
UPDATE kdvh_element SET element_id='from_direction_of_peak(sea_surface_primary_wave PT20M)' WHERE element_id='from_direction_of_peak(sea_surface_primary_wave T20M)';
UPDATE kdvh_element SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE kdvh_element SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT10M)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T10M)';
UPDATE kdvh_element SET element_id='from_direction(sea_surface_swell_wave_first_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_first_mean_height T3H)';
UPDATE kdvh_element SET element_id='from_direction(sea_surface_swell_wave_second_mean_height PT3H)' WHERE element_id='from_direction(sea_surface_swell_wave_second_mean_height T3H)';
UPDATE kdvh_element SET element_id='from_direction_of_max(wind_speed PT1H)' WHERE element_id='from_direction_of_max(wind_speed T1H)';
UPDATE kdvh_element SET element_id='from_direction_of_max(wind_speed PT3H)' WHERE element_id='from_direction_of_max(wind_speed T3H)';
UPDATE kdvh_element SET element_id='sum(water_evaporation_amount PT1H)' WHERE element_id='sum(water_evaporation_amount T1H)';
UPDATE kdvh_element SET element_id='max(wind_speed_of_gust PT10M)' WHERE element_id='max(wind_speed_of_gust T10M)';
UPDATE kdvh_element SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE kdvh_element SET element_id='max(wind_speed_of_gust PT20M)' WHERE element_id='max(wind_speed_of_gust T20M)';
UPDATE kdvh_element SET element_id='max(wind_speed_of_gust PT1H)' WHERE element_id='max(wind_speed_of_gust T1H)';
UPDATE kdvh_element SET element_id='mean(wind_speed PT1H)' WHERE element_id='mean(wind_speed T1H)';
UPDATE kdvh_element SET element_id='max(wind_speed PT10M)' WHERE element_id='max(wind_speed T10M)';
UPDATE kdvh_element SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE kdvh_element SET element_id='max(wind_speed PT6H)' WHERE element_id='max(wind_speed T6H)';
UPDATE kdvh_element SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE kdvh_element SET element_id='max(beaufort_wind_force PT6H)' WHERE element_id='max(beaufort_wind_force T6H)';
UPDATE kdvh_element SET element_id='max(wind_speed PT20M)' WHERE element_id='max(wind_speed T20M)';
UPDATE kdvh_element SET element_id='max(wind_speed PT1H)' WHERE element_id='max(wind_speed T1H)';
UPDATE kdvh_element SET element_id='max(wind_speed PT3H)' WHERE element_id='max(wind_speed T3H)';
UPDATE kdvh_element SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE kdvh_element SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE kdvh_element SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE kdvh_element SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE kdvh_element SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE kdvh_element SET element_id='min(cloud_base_height PT1H)' WHERE element_id='min(cloud_base_height T1H)';
UPDATE kdvh_element SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE kdvh_element SET element_id='time_of_event_of_max(wind_speed_of_gust PT1H)' WHERE element_id='time_of_event_of_max(wind_speed_of_gust T1H)';
UPDATE kdvh_element SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE kdvh_element SET element_id='time_of_event_of_max(wind_speed PT1H)' WHERE element_id='time_of_event_of_max(wind_speed T1H)';
UPDATE kdvh_element SET element_id='sum(duration_of_sunshine PT1H)' WHERE element_id='sum(duration_of_sunshine T1H)';
UPDATE kdvh_element SET element_id='mean(surface_air_pressure PT1H)' WHERE element_id='mean(surface_air_pressure T1H)';
UPDATE kdvh_element SET element_id='min(surface_air_pressure PT1H)' WHERE element_id='min(surface_air_pressure T1H)';
UPDATE kdvh_element SET element_id='max(surface_air_pressure PT1H)' WHERE element_id='max(surface_air_pressure T1H)';
UPDATE kdvh_element SET element_id='change_over_time(surface_air_pressure PT1H)' WHERE element_id='change_over_time(surface_air_pressure T1H)';
UPDATE kdvh_element SET element_id='change_over_time(surface_air_pressure PT3H)' WHERE element_id='change_over_time(surface_air_pressure T3H)';
UPDATE kdvh_element SET element_id='change_over_time(surface_air_pressure PT6H)' WHERE element_id='change_over_time(surface_air_pressure T6H)';
UPDATE kdvh_element SET element_id='sum(precipitation_amount PT1M)' WHERE element_id='sum(precipitation_amount T1M)';
UPDATE kdvh_element SET element_id='sum(precipitation_amount PT10M)' WHERE element_id='sum(precipitation_amount T10M)';
UPDATE kdvh_element SET element_id='sum(precipitation_amount PT1H)' WHERE element_id='sum(precipitation_amount T1H)';
UPDATE kdvh_element SET element_id='sum(precipitation_amount PT12H)' WHERE element_id='sum(precipitation_amount T12H)';
UPDATE kdvh_element SET element_id='sum(precipitation_amount PT3H)' WHERE element_id='sum(precipitation_amount T3H)';
UPDATE kdvh_element SET element_id='sum(precipitation_amount PT6H)' WHERE element_id='sum(precipitation_amount T6H)';
UPDATE kdvh_element SET element_id='sum_over_undefined_period(precipitation_amount PT1H)' WHERE element_id='sum_over_undefined_period(precipitation_amount T1H)';
UPDATE kdvh_element SET element_id='mean(surface_snow_thickness PT1H)' WHERE element_id='mean(surface_snow_thickness T1H)';
UPDATE kdvh_element SET element_id='min(surface_snow_thickness PT1H)' WHERE element_id='min(surface_snow_thickness T1H)';
UPDATE kdvh_element SET element_id='max(surface_snow_thickness PT1H)' WHERE element_id='max(surface_snow_thickness T1H)';
UPDATE kdvh_element SET element_id='directional_spread(sea_surface_wave_total_energy PT20M)' WHERE element_id='directional_spread(sea_surface_wave_total_energy T20M)';
UPDATE kdvh_element SET element_id='directional_spread(sea_surface_peak_period PT20M)' WHERE element_id='directional_spread(sea_surface_peak_period T20M)';
UPDATE kdvh_element SET element_id='mean(air_temperature PT1H)' WHERE element_id='mean(air_temperature T1H)';
UPDATE kdvh_element SET element_id='min(air_temperature PT10M)' WHERE element_id='min(air_temperature T10M)';
UPDATE kdvh_element SET element_id='min(air_temperature PT1H)' WHERE element_id='min(air_temperature T1H)';
UPDATE kdvh_element SET element_id='min(air_temperature PT12H)' WHERE element_id='min(air_temperature T12H)';
UPDATE kdvh_element SET element_id='max(air_temperature PT10M)' WHERE element_id='max(air_temperature T10M)';
UPDATE kdvh_element SET element_id='max(air_temperature PT1H)' WHERE element_id='max(air_temperature T1H)';
UPDATE kdvh_element SET element_id='max(air_temperature PT12H)' WHERE element_id='max(air_temperature T12H)';
UPDATE kdvh_element SET element_id='mean(grass_temperature PT1H)' WHERE element_id='mean(grass_temperature T1H)';
UPDATE kdvh_element SET element_id='min(grass_temperature PT1H)' WHERE element_id='min(grass_temperature T1H)';
UPDATE kdvh_element SET element_id='min(grass_temperature PT12H)' WHERE element_id='min(grass_temperature T12H)';
UPDATE kdvh_element SET element_id='max(grass_temperature PT1H)' WHERE element_id='max(grass_temperature T1H)';
UPDATE kdvh_element SET element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE kdvh_element SET element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE kdvh_element SET element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period PT20M)' WHERE element_id='mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)';
UPDATE kdvh_element SET element_id='mean(soil_temperature PT1H)' WHERE element_id='mean(soil_temperature T1H)';
UPDATE kdvh_element SET element_id='max(sea_surface_wave_period PT20M) ' WHERE element_id='max(sea_surface_wave_period T20M) ';
UPDATE kdvh_element SET element_id='mean(sea_surface_temperature PT1H)' WHERE element_id='mean(sea_surface_temperature T1H)';
UPDATE kdvh_element SET element_id='min(sea_surface_temperature PT1H)' WHERE element_id='min(sea_surface_temperature T1H)';
UPDATE kdvh_element SET element_id='max(sea_surface_temperature PT1H)' WHERE element_id='max(sea_surface_temperature T1H)';
UPDATE kdvh_element SET element_id='precipitation_type_primary_significance' WHERE element_id='weather_type_primary_significance';
UPDATE kdvh_element SET element_id='precipitation_type_secondary_significance' WHERE element_id='weather_type_secondary_significance';
UPDATE kdvh_element SET element_id='precipitation_type_tertiary_significance' WHERE element_id='weather_type_tertiary_significance';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE kdvh_element SET element_id='over_time(weather_type_primary_significance PT3H)' WHERE element_id='over_time(weather_type_primary_significance_wmo T3H)';
UPDATE kdvh_element SET element_id='over_time(weather_type_secondary_significance PT3H)' WHERE element_id='over_time(weather_type_secondary_significance_wmo T3H)';
UPDATE kdvh_element SET element_id='over_time(weather_type_additional1 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional1 T6H)';
UPDATE kdvh_element SET element_id='over_time(weather_type_additional2 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional2 T6H)';
UPDATE kdvh_element SET element_id='over_time(weather_type_additional3 PT6H)' WHERE element_id='over_time(weather_type_manually_observed_additional3 T6H)';
UPDATE kdvh_element SET element_id='from_direction_of_mean(sea_surface_primary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_primary_wave T10M)';
UPDATE kdvh_element SET element_id='from_direction_of_mean(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_secondary_wave T10M)';
UPDATE kdvh_element SET element_id='from_direction_of_mean(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_mean(sea_surface_wave_total_energy T10M)';
UPDATE kdvh_element SET element_id='from_direction_of_peak(sea_surface_secondary_wave PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_secondary_wave T10M)';
UPDATE kdvh_element SET element_id='from_direction_of_peak(sea_surface_wave_total_energy PT10M)' WHERE element_id='from_direction_of_peak(sea_surface_wave_total_energy T10M)';
UPDATE kdvh_element SET element_id='max(sea_surface_wave_height PT10M)' WHERE element_id='max(sea_surface_wave_height T10M)';
UPDATE kdvh_element SET element_id='max(sea_surface_wave_height PT20M)' WHERE element_id='max(sea_surface_wave_height T20M)';
UPDATE kdvh_element SET element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period PT10M)' WHERE element_id='estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)';

# --- !Downs

