# --- !Ups

--2.1 UPDATE id's in element
UPDATE element SET id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE element SET id='sum(water_evaporation_amount P1D)' WHERE id='sum(water_evaporation_amount T24H)';
UPDATE element SET id='mean(wind_speed P1D)' WHERE id='mean(wind_speed T24H)';
UPDATE element SET id='min(wind_speed P1D)' WHERE id='min(wind_speed T24H)';
UPDATE element SET id='max(wind_speed P1D)' WHERE id='max(wind_speed T24H)';
UPDATE element SET id='mean(wind_speed_of_gust P1D)' WHERE id='mean(wind_speed_of_gust T24H)';
UPDATE element SET id='min(wind_speed_of_gust P1D)' WHERE id='min(wind_speed_of_gust T24H)';
UPDATE element SET id='max(wind_speed_of_gust P1D)' WHERE id='max(wind_speed_of_gust T24H)';
UPDATE element SET id='mean(max(wind_speed P1D) P1M)' WHERE id='mean(max(wind_speed T1H) T24H)';
UPDATE element SET id='mean(max(wind_speed PT1H) P1D)' WHERE id='mean(max(wind_speed T1H) T24H)';
UPDATE element SET id='mean(max(wind_speed P1D) P1M)' WHERE id='mean(max(wind_speed T24H) 1M)';
UPDATE element SET id='mean(max(wind_speed PT1H) P1D)' WHERE id='mean(max(wind_speed T24H) 1M)';
UPDATE element SET id='min(max(wind_speed PT1H) P1D)' WHERE id='min(max(wind_speed T1H) T24H)';
UPDATE element SET id='min(max(wind_speed P1D) P1M)' WHERE id='min(max(wind_speed T1H) T24H)';
UPDATE element SET id='min(max(wind_speed P1D) P1M)' WHERE id='min(max(wind_speed T24H) 1M)';
UPDATE element SET id='min(max(wind_speed PT1H) P1D)' WHERE id='min(max(wind_speed T24H) 1M)';
UPDATE element SET id='max(max(wind_speed PT1H) P1D)' WHERE id='max(max(wind_speed T24H) 1M)';
UPDATE element SET id='max(max(wind_speed PT1H) P1D)' WHERE id='max(max(wind_speed T1H) T24H)';
UPDATE element SET id='max(max(wind_speed P1D) P1M)' WHERE id='max(max(wind_speed T1H) T24H)';
UPDATE element SET id='max(max(wind_speed P1D) P1M)' WHERE id='max(max(wind_speed T24H) 1M)';
UPDATE element SET id='time_of_event_of_max(max(wind_speed P1D) P1M)' WHERE id='time_of_event_of_max(max(wind_speed T24H) 1M)';
UPDATE element SET id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element SET id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element SET id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element SET id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element SET id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE element SET id='mean(sea_surface_wave_significant_height_from_instrument P1D)' WHERE id='mean(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element SET id='min(sea_surface_wave_significant_height_from_instrument P1D)' WHERE id='min(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element SET id='max(sea_surface_wave_significant_height_from_instrument P1D)' WHERE id='max(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element SET id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE element SET id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE element SET id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE element SET id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE element SET id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE element SET id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE element SET id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE element SET id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE element SET id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE element SET id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE element SET id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE element SET id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE element SET id='mean(cloud_area_fraction P1D)' WHERE id='mean(cloud_area_fraction T24H)';
UPDATE element SET id='min(cloud_area_fraction P1D)' WHERE id='min(cloud_area_fraction T24H)';
UPDATE element SET id='max(cloud_area_fraction P1D)' WHERE id='max(cloud_area_fraction T24H)';
UPDATE element SET id='sum(duration_of_sunshine P1D)' WHERE id='sum(duration_of_sunshine T24H)';
UPDATE element SET id='min(sum(duration_of_sunshine P1D) P1M)' WHERE id='min(sum(duration_of_sunshine T24H) 1M)';
UPDATE element SET id='max(sum(duration_of_sunshine P1D) P1M)' WHERE id='max(sum(duration_of_sunshine T24H) 1M)';
UPDATE element SET id='sum(duration_of_sunshine P1D)' WHERE id='sum(duration_of_sunshine T24H)';
UPDATE element SET id='mean(surface_air_pressure P1D)' WHERE id='mean(surface_air_pressure T24H)';
UPDATE element SET id='min(surface_air_pressure P1D)' WHERE id='min(surface_air_pressure T24H)';
UPDATE element SET id='max(surface_air_pressure P1D)' WHERE id='max(surface_air_pressure T24H)';
UPDATE element SET id='mean(air_pressure_at_sea_level P1D)' WHERE id='mean(air_pressure_at_sea_level T24H)';
UPDATE element SET id='min(air_pressure_at_sea_level P1D)' WHERE id='min(air_pressure_at_sea_level T24H)';
UPDATE element SET id='max(air_pressure_at_sea_level P1D)' WHERE id='max(air_pressure_at_sea_level T24H)';
UPDATE element SET id='mean(sea_surface_wave_period_from_instrument P1D)' WHERE id='mean(sea_surface_wave_period_from_instrument T24H)';
UPDATE element SET id='min(sea_surface_wave_period_from_instrument P1D)' WHERE id='min(sea_surface_wave_period_from_instrument T24H)';
UPDATE element SET id='max(sea_surface_wave_period_from_instrument P1D)' WHERE id='max(sea_surface_wave_period_from_instrument T24H)';
UPDATE element SET id='sum(precipitation_amount P1D)' WHERE id='sum(precipitation_amount T24H)';
UPDATE element SET id='sum_over_undefined_period(precipitation_amount P1D)' WHERE id='sum_over_undefined_period(precipitation_amount T24H)';
UPDATE element SET id='sum(precipitation_amount P1D)' WHERE id='sum(precipitation_amount T24H)';
UPDATE element SET id='sum(precipitation_amount P1D)' WHERE id='sum(precipitation_amount T24H)';
UPDATE element SET id='max(sum(precipitation_amount P1D) P1M)' WHERE id='max(sum(precipitation_amount T24H) 1M)';
UPDATE element SET id='time_of_event_of_max(sum(precipitation_amount P1D) P1M)' WHERE id='time_of_event_of_max(sum(precipitation_amount T24H) 1M)';
UPDATE element SET id='change_over_time(surface_snow_amount P1D)' WHERE id='change_over_time(surface_snow_amount T24H)';
UPDATE element SET id='min(sea_state P1D)' WHERE id='min(sea_state T24H)';
UPDATE element SET id='max(sea_state P1D)' WHERE id='max(sea_state T24H)';
UPDATE element SET id='over_time(precipitation_type_primary_significance P1D)' WHERE id='max(timeperiod_weather_type_significance1 T24H)';
UPDATE element SET id='change_over_time(surface_snow_thickness P1D)' WHERE id='change_over_time(surface_snow_thickness T24H)';
UPDATE element SET id='mean(air_temperature P1D)' WHERE id='mean(air_temperature T24H)';
UPDATE element SET id='best_estimate_mean(air_temperature P1D)' WHERE id='best_estimate_mean(air_temperature T24H)';
UPDATE element SET id='mean(air_temperature P1D)' WHERE id='best_estimate_mean(air_temperature T24H)';
UPDATE element SET id='best_estimate_mean(air_temperature P1D)' WHERE id='mean(air_temperature T24H)';
UPDATE element SET id='mean(air_temperature P1D)' WHERE id='mean(air_temperature T24H)';
UPDATE element SET id='mean_k(air_temperature P1D)' WHERE id='mean_k(air_temperature T24H)';
UPDATE element SET id='min(air_temperature P1D)' WHERE id='min(air_temperature T24H)';
UPDATE element SET id='min(air_temperature P1D)' WHERE id='min(air_temperature T24H)';
UPDATE element SET id='mean(min(air_temperature P1D) P1M)' WHERE id='mean(min(air_temperature T24H) 1M)';
UPDATE element SET id='min(air_temperature P1D)' WHERE id='min(air_temperature T24H)';
UPDATE element SET id='max(air_temperature P1D)' WHERE id='max(air_temperature T24H)';
UPDATE element SET id='max(air_temperature P1D)' WHERE id='max(air_temperature T24H)';
UPDATE element SET id='mean(max(air_temperature P1D) P1M)' WHERE id='mean(max(air_temperature T24H) 1M)';
UPDATE element SET id='max(air_temperature P1D)' WHERE id='max(air_temperature T24H)';
UPDATE element SET id='mean(dew_point_temperature P1D)' WHERE id='mean(dew_point_temperature T24H)';
UPDATE element SET id='min(grass_temperature P1D)' WHERE id='min(grass_temperature T24H)';
UPDATE element SET id='mean(relative_humidity P1D)' WHERE id='mean(relative_humidity T24H)';
UPDATE element SET id='min(relative_humidity P1D)' WHERE id='min(relative_humidity T24H)';
UPDATE element SET id='max(relative_humidity P1D)' WHERE id='max(relative_humidity T24H)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element SET id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element SET id='min(visibility_in_air_horizontal P1D)' WHERE id='min(visibility_in_air_horizontal T24H)';
UPDATE element SET id='max(visibility_in_air_horizontal P1D)' WHERE id='max(visibility_in_air_horizontal T24H)';

--2.2 UPDATE element_name element_id's 
UPDATE element_name SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE element_name SET element_id='sum(water_evaporation_amount P1D)' WHERE element_id='sum(water_evaporation_amount T24H)';
UPDATE element_name SET element_id='mean(wind_speed P1D)' WHERE element_id='mean(wind_speed T24H)';
UPDATE element_name SET element_id='min(wind_speed P1D)' WHERE element_id='min(wind_speed T24H)';
UPDATE element_name SET element_id='max(wind_speed P1D)' WHERE element_id='max(wind_speed T24H)';
UPDATE element_name SET element_id='mean(wind_speed_of_gust P1D)' WHERE element_id='mean(wind_speed_of_gust T24H)';
UPDATE element_name SET element_id='min(wind_speed_of_gust P1D)' WHERE element_id='min(wind_speed_of_gust T24H)';
UPDATE element_name SET element_id='max(wind_speed_of_gust P1D)' WHERE element_id='max(wind_speed_of_gust T24H)';
UPDATE element_name SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE element_name SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE element_name SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE element_name SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE element_name SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE element_name SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE element_name SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE element_name SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE element_name SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE element_name SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE element_name SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE element_name SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE element_name SET element_id='time_of_event_of_max(max(wind_speed P1D) P1M)' WHERE element_id='time_of_event_of_max(max(wind_speed T24H) 1M)';
UPDATE element_name SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_name SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_name SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_name SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_name SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_name SET element_id='mean(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element_name SET element_id='min(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element_name SET element_id='max(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element_name SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE element_name SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE element_name SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_name SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_name SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE element_name SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_name SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_name SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE element_name SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_name SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE element_name SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE element_name SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_name SET element_id='mean(cloud_area_fraction P1D)' WHERE element_id='mean(cloud_area_fraction T24H)';
UPDATE element_name SET element_id='min(cloud_area_fraction P1D)' WHERE element_id='min(cloud_area_fraction T24H)';
UPDATE element_name SET element_id='max(cloud_area_fraction P1D)' WHERE element_id='max(cloud_area_fraction T24H)';
UPDATE element_name SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE element_name SET element_id='min(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='min(sum(duration_of_sunshine T24H) 1M)';
UPDATE element_name SET element_id='max(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='max(sum(duration_of_sunshine T24H) 1M)';
UPDATE element_name SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE element_name SET element_id='mean(surface_air_pressure P1D)' WHERE element_id='mean(surface_air_pressure T24H)';
UPDATE element_name SET element_id='min(surface_air_pressure P1D)' WHERE element_id='min(surface_air_pressure T24H)';
UPDATE element_name SET element_id='max(surface_air_pressure P1D)' WHERE element_id='max(surface_air_pressure T24H)';
UPDATE element_name SET element_id='mean(air_pressure_at_sea_level P1D)' WHERE element_id='mean(air_pressure_at_sea_level T24H)';
UPDATE element_name SET element_id='min(air_pressure_at_sea_level P1D)' WHERE element_id='min(air_pressure_at_sea_level T24H)';
UPDATE element_name SET element_id='max(air_pressure_at_sea_level P1D)' WHERE element_id='max(air_pressure_at_sea_level T24H)';
UPDATE element_name SET element_id='mean(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_period_from_instrument T24H)';
UPDATE element_name SET element_id='min(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_period_from_instrument T24H)';
UPDATE element_name SET element_id='max(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_period_from_instrument T24H)';
UPDATE element_name SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE element_name SET element_id='sum_over_undefined_period(precipitation_amount P1D)' WHERE element_id='sum_over_undefined_period(precipitation_amount T24H)';
UPDATE element_name SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE element_name SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE element_name SET element_id='max(sum(precipitation_amount P1D) P1M)' WHERE element_id='max(sum(precipitation_amount T24H) 1M)';
UPDATE element_name SET element_id='time_of_event_of_max(sum(precipitation_amount P1D) P1M)' WHERE element_id='time_of_event_of_max(sum(precipitation_amount T24H) 1M)';
UPDATE element_name SET element_id='change_over_time(surface_snow_amount P1D)' WHERE element_id='change_over_time(surface_snow_amount T24H)';
UPDATE element_name SET element_id='min(sea_state P1D)' WHERE element_id='min(sea_state T24H)';
UPDATE element_name SET element_id='max(sea_state P1D)' WHERE element_id='max(sea_state T24H)';
UPDATE element_name SET element_id='over_time(precipitation_type_primary_significance P1D)' WHERE element_id='max(timeperiod_weather_type_significance1 T24H)';
UPDATE element_name SET element_id='change_over_time(surface_snow_thickness P1D)' WHERE element_id='change_over_time(surface_snow_thickness T24H)';
UPDATE element_name SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE element_name SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE element_name SET element_id='mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE element_name SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE element_name SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE element_name SET element_id='mean_k(air_temperature P1D)' WHERE element_id='mean_k(air_temperature T24H)';
UPDATE element_name SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE element_name SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE element_name SET element_id='mean(min(air_temperature P1D) P1M)' WHERE element_id='mean(min(air_temperature T24H) 1M)';
UPDATE element_name SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE element_name SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE element_name SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE element_name SET element_id='mean(max(air_temperature P1D) P1M)' WHERE element_id='mean(max(air_temperature T24H) 1M)';
UPDATE element_name SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE element_name SET element_id='mean(dew_point_temperature P1D)' WHERE element_id='mean(dew_point_temperature T24H)';
UPDATE element_name SET element_id='min(grass_temperature P1D)' WHERE element_id='min(grass_temperature T24H)';
UPDATE element_name SET element_id='mean(relative_humidity P1D)' WHERE element_id='mean(relative_humidity T24H)';
UPDATE element_name SET element_id='min(relative_humidity P1D)' WHERE element_id='min(relative_humidity T24H)';
UPDATE element_name SET element_id='max(relative_humidity P1D)' WHERE element_id='max(relative_humidity T24H)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_name SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_name SET element_id='min(visibility_in_air_horizontal P1D)' WHERE element_id='min(visibility_in_air_horizontal T24H)';
UPDATE element_name SET element_id='max(visibility_in_air_horizontal P1D)' WHERE element_id='max(visibility_in_air_horizontal T24H)';

--2.3 UPDATE element_description element_id's 
UPDATE element_description SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE element_description SET element_id='sum(water_evaporation_amount P1D)' WHERE element_id='sum(water_evaporation_amount T24H)';
UPDATE element_description SET element_id='mean(wind_speed P1D)' WHERE element_id='mean(wind_speed T24H)';
UPDATE element_description SET element_id='min(wind_speed P1D)' WHERE element_id='min(wind_speed T24H)';
UPDATE element_description SET element_id='max(wind_speed P1D)' WHERE element_id='max(wind_speed T24H)';
UPDATE element_description SET element_id='mean(wind_speed_of_gust P1D)' WHERE element_id='mean(wind_speed_of_gust T24H)';
UPDATE element_description SET element_id='min(wind_speed_of_gust P1D)' WHERE element_id='min(wind_speed_of_gust T24H)';
UPDATE element_description SET element_id='max(wind_speed_of_gust P1D)' WHERE element_id='max(wind_speed_of_gust T24H)';
UPDATE element_description SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE element_description SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE element_description SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE element_description SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE element_description SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE element_description SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE element_description SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE element_description SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE element_description SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE element_description SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE element_description SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE element_description SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE element_description SET element_id='time_of_event_of_max(max(wind_speed P1D) P1M)' WHERE element_id='time_of_event_of_max(max(wind_speed T24H) 1M)';
UPDATE element_description SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_description SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_description SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_description SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_description SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_description SET element_id='mean(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element_description SET element_id='min(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element_description SET element_id='max(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element_description SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE element_description SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE element_description SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_description SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_description SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE element_description SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_description SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_description SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE element_description SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_description SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE element_description SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE element_description SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_description SET element_id='mean(cloud_area_fraction P1D)' WHERE element_id='mean(cloud_area_fraction T24H)';
UPDATE element_description SET element_id='min(cloud_area_fraction P1D)' WHERE element_id='min(cloud_area_fraction T24H)';
UPDATE element_description SET element_id='max(cloud_area_fraction P1D)' WHERE element_id='max(cloud_area_fraction T24H)';
UPDATE element_description SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE element_description SET element_id='min(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='min(sum(duration_of_sunshine T24H) 1M)';
UPDATE element_description SET element_id='max(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='max(sum(duration_of_sunshine T24H) 1M)';
UPDATE element_description SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE element_description SET element_id='mean(surface_air_pressure P1D)' WHERE element_id='mean(surface_air_pressure T24H)';
UPDATE element_description SET element_id='min(surface_air_pressure P1D)' WHERE element_id='min(surface_air_pressure T24H)';
UPDATE element_description SET element_id='max(surface_air_pressure P1D)' WHERE element_id='max(surface_air_pressure T24H)';
UPDATE element_description SET element_id='mean(air_pressure_at_sea_level P1D)' WHERE element_id='mean(air_pressure_at_sea_level T24H)';
UPDATE element_description SET element_id='min(air_pressure_at_sea_level P1D)' WHERE element_id='min(air_pressure_at_sea_level T24H)';
UPDATE element_description SET element_id='max(air_pressure_at_sea_level P1D)' WHERE element_id='max(air_pressure_at_sea_level T24H)';
UPDATE element_description SET element_id='mean(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_period_from_instrument T24H)';
UPDATE element_description SET element_id='min(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_period_from_instrument T24H)';
UPDATE element_description SET element_id='max(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_period_from_instrument T24H)';
UPDATE element_description SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE element_description SET element_id='sum_over_undefined_period(precipitation_amount P1D)' WHERE element_id='sum_over_undefined_period(precipitation_amount T24H)';
UPDATE element_description SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE element_description SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE element_description SET element_id='max(sum(precipitation_amount P1D) P1M)' WHERE element_id='max(sum(precipitation_amount T24H) 1M)';
UPDATE element_description SET element_id='time_of_event_of_max(sum(precipitation_amount P1D) P1M)' WHERE element_id='time_of_event_of_max(sum(precipitation_amount T24H) 1M)';
UPDATE element_description SET element_id='change_over_time(surface_snow_amount P1D)' WHERE element_id='change_over_time(surface_snow_amount T24H)';
UPDATE element_description SET element_id='min(sea_state P1D)' WHERE element_id='min(sea_state T24H)';
UPDATE element_description SET element_id='max(sea_state P1D)' WHERE element_id='max(sea_state T24H)';
UPDATE element_description SET element_id='over_time(precipitation_type_primary_significance P1D)' WHERE element_id='max(timeperiod_weather_type_significance1 T24H)';
UPDATE element_description SET element_id='change_over_time(surface_snow_thickness P1D)' WHERE element_id='change_over_time(surface_snow_thickness T24H)';
UPDATE element_description SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE element_description SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE element_description SET element_id='mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE element_description SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE element_description SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE element_description SET element_id='mean_k(air_temperature P1D)' WHERE element_id='mean_k(air_temperature T24H)';
UPDATE element_description SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE element_description SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE element_description SET element_id='mean(min(air_temperature P1D) P1M)' WHERE element_id='mean(min(air_temperature T24H) 1M)';
UPDATE element_description SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE element_description SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE element_description SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE element_description SET element_id='mean(max(air_temperature P1D) P1M)' WHERE element_id='mean(max(air_temperature T24H) 1M)';
UPDATE element_description SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE element_description SET element_id='mean(dew_point_temperature P1D)' WHERE element_id='mean(dew_point_temperature T24H)';
UPDATE element_description SET element_id='min(grass_temperature P1D)' WHERE element_id='min(grass_temperature T24H)';
UPDATE element_description SET element_id='mean(relative_humidity P1D)' WHERE element_id='mean(relative_humidity T24H)';
UPDATE element_description SET element_id='min(relative_humidity P1D)' WHERE element_id='min(relative_humidity T24H)';
UPDATE element_description SET element_id='max(relative_humidity P1D)' WHERE element_id='max(relative_humidity T24H)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_description SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_description SET element_id='min(visibility_in_air_horizontal P1D)' WHERE element_id='min(visibility_in_air_horizontal T24H)';
UPDATE element_description SET element_id='max(visibility_in_air_horizontal P1D)' WHERE element_id='max(visibility_in_air_horizontal T24H)';

--2.4 UPDATE element_codetable element_id's 
UPDATE element_codetable SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE element_codetable SET element_id='sum(water_evaporation_amount P1D)' WHERE element_id='sum(water_evaporation_amount T24H)';
UPDATE element_codetable SET element_id='mean(wind_speed P1D)' WHERE element_id='mean(wind_speed T24H)';
UPDATE element_codetable SET element_id='min(wind_speed P1D)' WHERE element_id='min(wind_speed T24H)';
UPDATE element_codetable SET element_id='max(wind_speed P1D)' WHERE element_id='max(wind_speed T24H)';
UPDATE element_codetable SET element_id='mean(wind_speed_of_gust P1D)' WHERE element_id='mean(wind_speed_of_gust T24H)';
UPDATE element_codetable SET element_id='min(wind_speed_of_gust P1D)' WHERE element_id='min(wind_speed_of_gust T24H)';
UPDATE element_codetable SET element_id='max(wind_speed_of_gust P1D)' WHERE element_id='max(wind_speed_of_gust T24H)';
UPDATE element_codetable SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE element_codetable SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE element_codetable SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE element_codetable SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE element_codetable SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE element_codetable SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE element_codetable SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE element_codetable SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE element_codetable SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE element_codetable SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE element_codetable SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE element_codetable SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE element_codetable SET element_id='time_of_event_of_max(max(wind_speed P1D) P1M)' WHERE element_id='time_of_event_of_max(max(wind_speed T24H) 1M)';
UPDATE element_codetable SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_codetable SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_codetable SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_codetable SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE element_codetable SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE element_codetable SET element_id='mean(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element_codetable SET element_id='min(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element_codetable SET element_id='max(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE element_codetable SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE element_codetable SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE element_codetable SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_codetable SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_codetable SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE element_codetable SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_codetable SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_codetable SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE element_codetable SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_codetable SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE element_codetable SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE element_codetable SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE element_codetable SET element_id='mean(cloud_area_fraction P1D)' WHERE element_id='mean(cloud_area_fraction T24H)';
UPDATE element_codetable SET element_id='min(cloud_area_fraction P1D)' WHERE element_id='min(cloud_area_fraction T24H)';
UPDATE element_codetable SET element_id='max(cloud_area_fraction P1D)' WHERE element_id='max(cloud_area_fraction T24H)';
UPDATE element_codetable SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE element_codetable SET element_id='min(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='min(sum(duration_of_sunshine T24H) 1M)';
UPDATE element_codetable SET element_id='max(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='max(sum(duration_of_sunshine T24H) 1M)';
UPDATE element_codetable SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE element_codetable SET element_id='mean(surface_air_pressure P1D)' WHERE element_id='mean(surface_air_pressure T24H)';
UPDATE element_codetable SET element_id='min(surface_air_pressure P1D)' WHERE element_id='min(surface_air_pressure T24H)';
UPDATE element_codetable SET element_id='max(surface_air_pressure P1D)' WHERE element_id='max(surface_air_pressure T24H)';
UPDATE element_codetable SET element_id='mean(air_pressure_at_sea_level P1D)' WHERE element_id='mean(air_pressure_at_sea_level T24H)';
UPDATE element_codetable SET element_id='min(air_pressure_at_sea_level P1D)' WHERE element_id='min(air_pressure_at_sea_level T24H)';
UPDATE element_codetable SET element_id='max(air_pressure_at_sea_level P1D)' WHERE element_id='max(air_pressure_at_sea_level T24H)';
UPDATE element_codetable SET element_id='mean(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_period_from_instrument T24H)';
UPDATE element_codetable SET element_id='min(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_period_from_instrument T24H)';
UPDATE element_codetable SET element_id='max(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_period_from_instrument T24H)';
UPDATE element_codetable SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE element_codetable SET element_id='sum_over_undefined_period(precipitation_amount P1D)' WHERE element_id='sum_over_undefined_period(precipitation_amount T24H)';
UPDATE element_codetable SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE element_codetable SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE element_codetable SET element_id='max(sum(precipitation_amount P1D) P1M)' WHERE element_id='max(sum(precipitation_amount T24H) 1M)';
UPDATE element_codetable SET element_id='time_of_event_of_max(sum(precipitation_amount P1D) P1M)' WHERE element_id='time_of_event_of_max(sum(precipitation_amount T24H) 1M)';
UPDATE element_codetable SET element_id='change_over_time(surface_snow_amount P1D)' WHERE element_id='change_over_time(surface_snow_amount T24H)';
UPDATE element_codetable SET element_id='min(sea_state P1D)' WHERE element_id='min(sea_state T24H)';
UPDATE element_codetable SET element_id='max(sea_state P1D)' WHERE element_id='max(sea_state T24H)';
UPDATE element_codetable SET element_id='over_time(precipitation_type_primary_significance P1D)' WHERE element_id='max(timeperiod_weather_type_significance1 T24H)';
UPDATE element_codetable SET element_id='change_over_time(surface_snow_thickness P1D)' WHERE element_id='change_over_time(surface_snow_thickness T24H)';
UPDATE element_codetable SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE element_codetable SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE element_codetable SET element_id='mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE element_codetable SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE element_codetable SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE element_codetable SET element_id='mean_k(air_temperature P1D)' WHERE element_id='mean_k(air_temperature T24H)';
UPDATE element_codetable SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE element_codetable SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE element_codetable SET element_id='mean(min(air_temperature P1D) P1M)' WHERE element_id='mean(min(air_temperature T24H) 1M)';
UPDATE element_codetable SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE element_codetable SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE element_codetable SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE element_codetable SET element_id='mean(max(air_temperature P1D) P1M)' WHERE element_id='mean(max(air_temperature T24H) 1M)';
UPDATE element_codetable SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE element_codetable SET element_id='mean(dew_point_temperature P1D)' WHERE element_id='mean(dew_point_temperature T24H)';
UPDATE element_codetable SET element_id='min(grass_temperature P1D)' WHERE element_id='min(grass_temperature T24H)';
UPDATE element_codetable SET element_id='mean(relative_humidity P1D)' WHERE element_id='mean(relative_humidity T24H)';
UPDATE element_codetable SET element_id='min(relative_humidity P1D)' WHERE element_id='min(relative_humidity T24H)';
UPDATE element_codetable SET element_id='max(relative_humidity P1D)' WHERE element_id='max(relative_humidity T24H)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_codetable SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE element_codetable SET element_id='min(visibility_in_air_horizontal P1D)' WHERE element_id='min(visibility_in_air_horizontal T24H)';
UPDATE element_codetable SET element_id='max(visibility_in_air_horizontal P1D)' WHERE element_id='max(visibility_in_air_horizontal T24H)';

--2.5 UPDATE cf_element element_id's 
UPDATE cf_element SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE cf_element SET element_id='sum(water_evaporation_amount P1D)' WHERE element_id='sum(water_evaporation_amount T24H)';
UPDATE cf_element SET element_id='mean(wind_speed P1D)' WHERE element_id='mean(wind_speed T24H)';
UPDATE cf_element SET element_id='min(wind_speed P1D)' WHERE element_id='min(wind_speed T24H)';
UPDATE cf_element SET element_id='max(wind_speed P1D)' WHERE element_id='max(wind_speed T24H)';
UPDATE cf_element SET element_id='mean(wind_speed_of_gust P1D)' WHERE element_id='mean(wind_speed_of_gust T24H)';
UPDATE cf_element SET element_id='min(wind_speed_of_gust P1D)' WHERE element_id='min(wind_speed_of_gust T24H)';
UPDATE cf_element SET element_id='max(wind_speed_of_gust P1D)' WHERE element_id='max(wind_speed_of_gust T24H)';
UPDATE cf_element SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE cf_element SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE cf_element SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE cf_element SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE cf_element SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE cf_element SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE cf_element SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='time_of_event_of_max(max(wind_speed P1D) P1M)' WHERE element_id='time_of_event_of_max(max(wind_speed T24H) 1M)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE cf_element SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE cf_element SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE cf_element SET element_id='mean(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE cf_element SET element_id='min(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE cf_element SET element_id='max(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE cf_element SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE cf_element SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE cf_element SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE cf_element SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE cf_element SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE cf_element SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE cf_element SET element_id='mean(cloud_area_fraction P1D)' WHERE element_id='mean(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='min(cloud_area_fraction P1D)' WHERE element_id='min(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='max(cloud_area_fraction P1D)' WHERE element_id='max(cloud_area_fraction T24H)';
UPDATE cf_element SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE cf_element SET element_id='min(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='min(sum(duration_of_sunshine T24H) 1M)';
UPDATE cf_element SET element_id='max(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='max(sum(duration_of_sunshine T24H) 1M)';
UPDATE cf_element SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE cf_element SET element_id='mean(surface_air_pressure P1D)' WHERE element_id='mean(surface_air_pressure T24H)';
UPDATE cf_element SET element_id='min(surface_air_pressure P1D)' WHERE element_id='min(surface_air_pressure T24H)';
UPDATE cf_element SET element_id='max(surface_air_pressure P1D)' WHERE element_id='max(surface_air_pressure T24H)';
UPDATE cf_element SET element_id='mean(air_pressure_at_sea_level P1D)' WHERE element_id='mean(air_pressure_at_sea_level T24H)';
UPDATE cf_element SET element_id='min(air_pressure_at_sea_level P1D)' WHERE element_id='min(air_pressure_at_sea_level T24H)';
UPDATE cf_element SET element_id='max(air_pressure_at_sea_level P1D)' WHERE element_id='max(air_pressure_at_sea_level T24H)';
UPDATE cf_element SET element_id='mean(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_period_from_instrument T24H)';
UPDATE cf_element SET element_id='min(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_period_from_instrument T24H)';
UPDATE cf_element SET element_id='max(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_period_from_instrument T24H)';
UPDATE cf_element SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE cf_element SET element_id='sum_over_undefined_period(precipitation_amount P1D)' WHERE element_id='sum_over_undefined_period(precipitation_amount T24H)';
UPDATE cf_element SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE cf_element SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE cf_element SET element_id='max(sum(precipitation_amount P1D) P1M)' WHERE element_id='max(sum(precipitation_amount T24H) 1M)';
UPDATE cf_element SET element_id='time_of_event_of_max(sum(precipitation_amount P1D) P1M)' WHERE element_id='time_of_event_of_max(sum(precipitation_amount T24H) 1M)';
UPDATE cf_element SET element_id='change_over_time(surface_snow_amount P1D)' WHERE element_id='change_over_time(surface_snow_amount T24H)';
UPDATE cf_element SET element_id='min(sea_state P1D)' WHERE element_id='min(sea_state T24H)';
UPDATE cf_element SET element_id='max(sea_state P1D)' WHERE element_id='max(sea_state T24H)';
UPDATE cf_element SET element_id='over_time(precipitation_type_primary_significance P1D)' WHERE element_id='max(timeperiod_weather_type_significance1 T24H)';
UPDATE cf_element SET element_id='change_over_time(surface_snow_thickness P1D)' WHERE element_id='change_over_time(surface_snow_thickness T24H)';
UPDATE cf_element SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE cf_element SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE cf_element SET element_id='mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE cf_element SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE cf_element SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE cf_element SET element_id='mean_k(air_temperature P1D)' WHERE element_id='mean_k(air_temperature T24H)';
UPDATE cf_element SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE cf_element SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE cf_element SET element_id='mean(min(air_temperature P1D) P1M)' WHERE element_id='mean(min(air_temperature T24H) 1M)';
UPDATE cf_element SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE cf_element SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE cf_element SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE cf_element SET element_id='mean(max(air_temperature P1D) P1M)' WHERE element_id='mean(max(air_temperature T24H) 1M)';
UPDATE cf_element SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE cf_element SET element_id='mean(dew_point_temperature P1D)' WHERE element_id='mean(dew_point_temperature T24H)';
UPDATE cf_element SET element_id='min(grass_temperature P1D)' WHERE element_id='min(grass_temperature T24H)';
UPDATE cf_element SET element_id='mean(relative_humidity P1D)' WHERE element_id='mean(relative_humidity T24H)';
UPDATE cf_element SET element_id='min(relative_humidity P1D)' WHERE element_id='min(relative_humidity T24H)';
UPDATE cf_element SET element_id='max(relative_humidity P1D)' WHERE element_id='max(relative_humidity T24H)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE cf_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE cf_element SET element_id='min(visibility_in_air_horizontal P1D)' WHERE element_id='min(visibility_in_air_horizontal T24H)';
UPDATE cf_element SET element_id='max(visibility_in_air_horizontal P1D)' WHERE element_id='max(visibility_in_air_horizontal T24H)';

--2.6 UPDATE kdvh_element element_id's 
UPDATE kdvh_element SET element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 0.1)' WHERE element_id='number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)';
UPDATE kdvh_element SET element_id='sum(water_evaporation_amount P1D)' WHERE element_id='sum(water_evaporation_amount T24H)';
UPDATE kdvh_element SET element_id='mean(wind_speed P1D)' WHERE element_id='mean(wind_speed T24H)';
UPDATE kdvh_element SET element_id='min(wind_speed P1D)' WHERE element_id='min(wind_speed T24H)';
UPDATE kdvh_element SET element_id='max(wind_speed P1D)' WHERE element_id='max(wind_speed T24H)';
UPDATE kdvh_element SET element_id='mean(wind_speed_of_gust P1D)' WHERE element_id='mean(wind_speed_of_gust T24H)';
UPDATE kdvh_element SET element_id='min(wind_speed_of_gust P1D)' WHERE element_id='min(wind_speed_of_gust T24H)';
UPDATE kdvh_element SET element_id='max(wind_speed_of_gust P1D)' WHERE element_id='max(wind_speed_of_gust T24H)';
UPDATE kdvh_element SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE kdvh_element SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T1H) T24H)';
UPDATE kdvh_element SET element_id='mean(max(wind_speed P1D) P1M)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE kdvh_element SET element_id='mean(max(wind_speed PT1H) P1D)' WHERE element_id='mean(max(wind_speed T24H) 1M)';
UPDATE kdvh_element SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE kdvh_element SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T1H) T24H)';
UPDATE kdvh_element SET element_id='min(max(wind_speed P1D) P1M)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE kdvh_element SET element_id='min(max(wind_speed PT1H) P1D)' WHERE element_id='min(max(wind_speed T24H) 1M)';
UPDATE kdvh_element SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE kdvh_element SET element_id='max(max(wind_speed PT1H) P1D)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE kdvh_element SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T1H) T24H)';
UPDATE kdvh_element SET element_id='max(max(wind_speed P1D) P1M)' WHERE element_id='max(max(wind_speed T24H) 1M)';
UPDATE kdvh_element SET element_id='time_of_event_of_max(max(wind_speed P1D) P1M)' WHERE element_id='time_of_event_of_max(max(wind_speed T24H) 1M)';
UPDATE kdvh_element SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE kdvh_element SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T24H) 1M 17.0)';
UPDATE kdvh_element SET element_id='integral_of_excess(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE kdvh_element SET element_id='integral_of_excess(mean(air_temperature PT1H) P1D 17.0)' WHERE element_id='integral_of_excess(mean(air_temperature T1H) T24H 17.0)';
UPDATE kdvh_element SET element_id='integral_of_excess_interpolated(mean(air_temperature P1D) P1M 17.0)' WHERE element_id='integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)';
UPDATE kdvh_element SET element_id='mean(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE kdvh_element SET element_id='min(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE kdvh_element SET element_id='max(sea_surface_wave_significant_height_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_significant_height_from_instrument T24H)';
UPDATE kdvh_element SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE kdvh_element SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction T24H)';
UPDATE kdvh_element SET element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE kdvh_element SET element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)';
UPDATE kdvh_element SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE kdvh_element SET element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE kdvh_element SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)';
UPDATE kdvh_element SET element_id='boolean_fair_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_fair_weather(cloud_area_fraction T24H)';
UPDATE kdvh_element SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE kdvh_element SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE kdvh_element SET element_id='boolean_overcast_weather(cloud_area_fraction P1D)' WHERE element_id='boolean_overcast_weather(cloud_area_fraction T24H)';
UPDATE kdvh_element SET element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)';
UPDATE kdvh_element SET element_id='mean(cloud_area_fraction P1D)' WHERE element_id='mean(cloud_area_fraction T24H)';
UPDATE kdvh_element SET element_id='min(cloud_area_fraction P1D)' WHERE element_id='min(cloud_area_fraction T24H)';
UPDATE kdvh_element SET element_id='max(cloud_area_fraction P1D)' WHERE element_id='max(cloud_area_fraction T24H)';
UPDATE kdvh_element SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE kdvh_element SET element_id='min(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='min(sum(duration_of_sunshine T24H) 1M)';
UPDATE kdvh_element SET element_id='max(sum(duration_of_sunshine P1D) P1M)' WHERE element_id='max(sum(duration_of_sunshine T24H) 1M)';
UPDATE kdvh_element SET element_id='sum(duration_of_sunshine P1D)' WHERE element_id='sum(duration_of_sunshine T24H)';
UPDATE kdvh_element SET element_id='mean(surface_air_pressure P1D)' WHERE element_id='mean(surface_air_pressure T24H)';
UPDATE kdvh_element SET element_id='min(surface_air_pressure P1D)' WHERE element_id='min(surface_air_pressure T24H)';
UPDATE kdvh_element SET element_id='max(surface_air_pressure P1D)' WHERE element_id='max(surface_air_pressure T24H)';
UPDATE kdvh_element SET element_id='mean(air_pressure_at_sea_level P1D)' WHERE element_id='mean(air_pressure_at_sea_level T24H)';
UPDATE kdvh_element SET element_id='min(air_pressure_at_sea_level P1D)' WHERE element_id='min(air_pressure_at_sea_level T24H)';
UPDATE kdvh_element SET element_id='max(air_pressure_at_sea_level P1D)' WHERE element_id='max(air_pressure_at_sea_level T24H)';
UPDATE kdvh_element SET element_id='mean(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='mean(sea_surface_wave_period_from_instrument T24H)';
UPDATE kdvh_element SET element_id='min(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='min(sea_surface_wave_period_from_instrument T24H)';
UPDATE kdvh_element SET element_id='max(sea_surface_wave_period_from_instrument P1D)' WHERE element_id='max(sea_surface_wave_period_from_instrument T24H)';
UPDATE kdvh_element SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE kdvh_element SET element_id='sum_over_undefined_period(precipitation_amount P1D)' WHERE element_id='sum_over_undefined_period(precipitation_amount T24H)';
UPDATE kdvh_element SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE kdvh_element SET element_id='sum(precipitation_amount P1D)' WHERE element_id='sum(precipitation_amount T24H)';
UPDATE kdvh_element SET element_id='max(sum(precipitation_amount P1D) P1M)' WHERE element_id='max(sum(precipitation_amount T24H) 1M)';
UPDATE kdvh_element SET element_id='time_of_event_of_max(sum(precipitation_amount P1D) P1M)' WHERE element_id='time_of_event_of_max(sum(precipitation_amount T24H) 1M)';
UPDATE kdvh_element SET element_id='change_over_time(surface_snow_amount P1D)' WHERE element_id='change_over_time(surface_snow_amount T24H)';
UPDATE kdvh_element SET element_id='min(sea_state P1D)' WHERE element_id='min(sea_state T24H)';
UPDATE kdvh_element SET element_id='max(sea_state P1D)' WHERE element_id='max(sea_state T24H)';
UPDATE kdvh_element SET element_id='over_time(precipitation_type_primary_significance P1D)' WHERE element_id='max(timeperiod_weather_type_significance1 T24H)';
UPDATE kdvh_element SET element_id='change_over_time(surface_snow_thickness P1D)' WHERE element_id='change_over_time(surface_snow_thickness T24H)';
UPDATE kdvh_element SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE kdvh_element SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE kdvh_element SET element_id='mean(air_temperature P1D)' WHERE element_id='best_estimate_mean(air_temperature T24H)';
UPDATE kdvh_element SET element_id='best_estimate_mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE kdvh_element SET element_id='mean(air_temperature P1D)' WHERE element_id='mean(air_temperature T24H)';
UPDATE kdvh_element SET element_id='mean_k(air_temperature P1D)' WHERE element_id='mean_k(air_temperature T24H)';
UPDATE kdvh_element SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE kdvh_element SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE kdvh_element SET element_id='mean(min(air_temperature P1D) P1M)' WHERE element_id='mean(min(air_temperature T24H) 1M)';
UPDATE kdvh_element SET element_id='min(air_temperature P1D)' WHERE element_id='min(air_temperature T24H)';
UPDATE kdvh_element SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE kdvh_element SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE kdvh_element SET element_id='mean(max(air_temperature P1D) P1M)' WHERE element_id='mean(max(air_temperature T24H) 1M)';
UPDATE kdvh_element SET element_id='max(air_temperature P1D)' WHERE element_id='max(air_temperature T24H)';
UPDATE kdvh_element SET element_id='mean(dew_point_temperature P1D)' WHERE element_id='mean(dew_point_temperature T24H)';
UPDATE kdvh_element SET element_id='min(grass_temperature P1D)' WHERE element_id='min(grass_temperature T24H)';
UPDATE kdvh_element SET element_id='mean(relative_humidity P1D)' WHERE element_id='mean(relative_humidity T24H)';
UPDATE kdvh_element SET element_id='min(relative_humidity P1D)' WHERE element_id='min(relative_humidity T24H)';
UPDATE kdvh_element SET element_id='max(relative_humidity P1D)' WHERE element_id='max(relative_humidity T24H)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 5.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 5.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 5.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T1H) T24H 0.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature P1D) P1M 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE kdvh_element SET element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 0.0)' WHERE element_id='integral_of_deficit(mean(air_temperature T24H) 1M 0.0)';
UPDATE kdvh_element SET element_id='min(visibility_in_air_horizontal P1D)' WHERE element_id='min(visibility_in_air_horizontal T24H)';
UPDATE kdvh_element SET element_id='max(visibility_in_air_horizontal P1D)' WHERE element_id='max(visibility_in_air_horizontal T24H)';

# --- !Downs

