# --- !Ups

Insert into ELEMENT (ID,UNIT) values ('air_pressure_at_sea_level','hPa');
Insert into ELEMENT (ID,UNIT) values ('air_temperature','degC');
Insert into ELEMENT (ID,UNIT) values ('beaufort_wind_force','code');
Insert into ELEMENT (ID,UNIT) values ('best_estimate_mean(air_temperature 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('best_estimate_mean(air_temperature T24H)','degC');
Insert into ELEMENT (ID,UNIT) values ('best_estimate_mean(air_temperature_anomaly 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('best_estimate_sum(precipitation_amount 1M)','mm');
Insert into ELEMENT (ID,UNIT) values ('best_estimate_sum(precipitation_amount_anomaly 1M)','percent');
Insert into ELEMENT (ID,UNIT) values ('boolean_clear_sky_weather(cloud_area_fraction T24H)','sum');
Insert into ELEMENT (ID,UNIT) values ('boolean_fair_weather(cloud_area_fraction T24H)','sum');
Insert into ELEMENT (ID,UNIT) values ('boolean_overcast_weather(cloud_area_fraction T24H)','sum');
Insert into ELEMENT (ID,UNIT) values ('change_over_time(surface_air_pressure T1H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('change_over_time(surface_air_pressure T3H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('change_over_time(surface_air_pressure T6H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('change_over_time(surface_snow_amount T24H)','cm');
Insert into ELEMENT (ID,UNIT) values ('change_over_time(surface_snow_thickness T24H)','cm');
Insert into ELEMENT (ID,UNIT) values ('cloud_area_fraction','octas');
Insert into ELEMENT (ID,UNIT) values ('cloud_area_fraction1','code');
Insert into ELEMENT (ID,UNIT) values ('cloud_area_fraction2','code');
Insert into ELEMENT (ID,UNIT) values ('cloud_area_fraction3','code');
Insert into ELEMENT (ID,UNIT) values ('cloud_area_fraction4','code');
Insert into ELEMENT (ID,UNIT) values ('cloud_base_height','meters');
Insert into ELEMENT (ID,UNIT) values ('cloud_base_height1','meters');
Insert into ELEMENT (ID,UNIT) values ('cloud_base_height2','meter');
Insert into ELEMENT (ID,UNIT) values ('cloud_base_height3','meters');
Insert into ELEMENT (ID,UNIT) values ('cloud_base_height4','meters');
Insert into ELEMENT (ID,UNIT) values ('dew_point_temperature','degC');
Insert into ELEMENT (ID,UNIT) values ('diffuse_downwelling_shortwave_flux_in_air','W/m2');
Insert into ELEMENT (ID,UNIT) values ('directional_spread(sea_surface_peak_period T20M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('directional_spread(sea_surface_wave_total_energy T20M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)','seconds');
Insert into ELEMENT (ID,UNIT) values ('from_direction(sea_surface_swell_wave_first_mean_height T10M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction(sea_surface_swell_wave_first_mean_height T3H)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction(sea_surface_swell_wave_second_mean_height T3H)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_max(wind_speed T1H)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_max(wind_speed T20M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_max(wind_speed T3H)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_max(wind_speed_of_gust T10M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_max(wind_speed_of_gust T1H)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_mean(sea_surface_primary_wave T10M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_mean(sea_surface_primary_wave T20M) ','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_mean(sea_surface_secondary_wave T10M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_mean(sea_surface_wave_total_energy T10M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_mean(sea_surface_wave_total_energy T20M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_peak(sea_surface_primary_wave T20M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_peak(sea_surface_primary_wave)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_peak(sea_surface_secondary_wave T10M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('from_direction_of_peak(sea_surface_wave_total_energy T10M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('grass_temperature','degC');
Insert into ELEMENT (ID,UNIT) values ('high_type_cloud','code');
Insert into ELEMENT (ID,UNIT) values ('instant_weather_type','code');
Insert into ELEMENT (ID,UNIT) values ('instant_weather_type_from_instrument','code');
Insert into ELEMENT (ID,UNIT) values ('instant_weather_type_significance1','code');
Insert into ELEMENT (ID,UNIT) values ('instant_weather_type_significance2','code');
Insert into ELEMENT (ID,UNIT) values ('instant_weather_type_significance3','code');
Insert into ELEMENT (ID,UNIT) values ('integral_of_deficit(mean(air_temperature T1H) T24H 0.0)','degree-day');
Insert into ELEMENT (ID,UNIT) values ('integral_of_deficit(mean(air_temperature T1H) T24H 5.0)','degree-day');
Insert into ELEMENT (ID,UNIT) values ('integral_of_deficit(mean(air_temperature T24H) 1M 0.0)','degree-day');
Insert into ELEMENT (ID,UNIT) values ('integral_of_deficit(mean(air_temperature T24H) 1M 5.0)','degree-day');
Insert into ELEMENT (ID,UNIT) values ('integral_of_excess(mean(air_temperature T1H) T24H 17.0)','degree-day');
Insert into ELEMENT (ID,UNIT) values ('integral_of_excess(mean(air_temperature T24H) 1M 17.0)','degree-day');
Insert into ELEMENT (ID,UNIT) values ('integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)','degree-day');
Insert into ELEMENT (ID,UNIT) values ('latitude','degrees');
Insert into ELEMENT (ID,UNIT) values ('liquid_water_content_of_surface_snow','mm');
Insert into ELEMENT (ID,UNIT) values ('longitude','degrees');
Insert into ELEMENT (ID,UNIT) values ('low_type_cloud','code');
Insert into ELEMENT (ID,UNIT) values ('low_type_cloud_area_fraction','octas');
Insert into ELEMENT (ID,UNIT) values ('max(air_pressure_at_sea_level 1M)','hPa');
Insert into ELEMENT (ID,UNIT) values ('max(air_pressure_at_sea_level T24H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('max(air_temperature 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(air_temperature T10M)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(air_temperature T12H)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(air_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(air_temperature T24H)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(beaufort_wind_force T6H)','code');
Insert into ELEMENT (ID,UNIT) values ('max(cloud_area_fraction 1M)','octas');
Insert into ELEMENT (ID,UNIT) values ('max(cloud_area_fraction T24H)','octas');
Insert into ELEMENT (ID,UNIT) values ('max(grass_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(max(wind_speed T1H) T24H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(max(wind_speed T24H) 1M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(min(grass_temperature T1H) 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(relative_humidity 1M)','percent');
Insert into ELEMENT (ID,UNIT) values ('max(relative_humidity T24H)','percent');
Insert into ELEMENT (ID,UNIT) values ('max(sea_state 1M)','code');
Insert into ELEMENT (ID,UNIT) values ('max(sea_state T24H)','code');
Insert into ELEMENT (ID,UNIT) values ('max(sea_surface_temperature 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(sea_surface_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(sea_surface_wave_height T10M)','meters');
Insert into ELEMENT (ID,UNIT) values ('max(sea_surface_wave_height T20M)','meters');
Insert into ELEMENT (ID,UNIT) values ('max(sea_surface_wave_period T20M) ','seconds');
Insert into ELEMENT (ID,UNIT) values ('max(sea_surface_wave_period_from_instrument 1M)','seconds');
Insert into ELEMENT (ID,UNIT) values ('max(sea_surface_wave_period_from_instrument T24H)','seconds');
Insert into ELEMENT (ID,UNIT) values ('max(sea_surface_wave_significant_height_from_instrument 1M)','meters');
Insert into ELEMENT (ID,UNIT) values ('max(sea_surface_wave_significant_height_from_instrument T24H)','meters');
Insert into ELEMENT (ID,UNIT) values ('max(snow_coverage_type 1M)','code');
Insert into ELEMENT (ID,UNIT) values ('max(snow_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(sum(duration_of_sunshine T24H) 1M)','hours');
Insert into ELEMENT (ID,UNIT) values ('max(sum(precipitation_amount T24H) 1M)','mm');
Insert into ELEMENT (ID,UNIT) values ('max(surface_air_pressure 1M)','hPa');
Insert into ELEMENT (ID,UNIT) values ('max(surface_air_pressure T1H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('max(surface_air_pressure T24H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('max(surface_snow_thickness 1M)','cm');
Insert into ELEMENT (ID,UNIT) values ('max(surface_snow_thickness T1H)','cm');
Insert into ELEMENT (ID,UNIT) values ('max(surface_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('max(timeperiod_weather_type_significance1 T24H)','code');
Insert into ELEMENT (ID,UNIT) values ('max(visibility_in_air_horizontal 1M)','meters');
Insert into ELEMENT (ID,UNIT) values ('max(visibility_in_air_horizontal T24H)','meters');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed 1M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed T10M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed T1H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed T20M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed T24H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed T3H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed T6H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed_of_gust 1M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed_of_gust T10M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed_of_gust T1H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed_of_gust T20M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('max(wind_speed_of_gust T24H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('mean(air_pressure_at_sea_level 1M)','hPa');
Insert into ELEMENT (ID,UNIT) values ('mean(air_pressure_at_sea_level T24H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('mean(air_temperature 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(air_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(air_temperature T24H)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(air_temperature_anomaly 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(cloud_area_fraction 1M)','octas');
Insert into ELEMENT (ID,UNIT) values ('mean(cloud_area_fraction T24H)','octas');
Insert into ELEMENT (ID,UNIT) values ('mean(dew_point_temperature 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(dew_point_temperature T24H)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(grass_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(max(air_temperature T24H) 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(max(wind_speed T1H) T24H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('mean(max(wind_speed T24H) 1M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('mean(min(air_temperature T24H) 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(min(grass_temperature T1H) 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(relative_humidity 1M)','percent');
Insert into ELEMENT (ID,UNIT) values ('mean(relative_humidity T1H)','percent');
Insert into ELEMENT (ID,UNIT) values ('mean(relative_humidity T24H)','percent');
Insert into ELEMENT (ID,UNIT) values ('mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('mean(sea_surface_temperature 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(sea_surface_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('mean(sea_surface_wave_period_from_instrument 1M)','seconds');
Insert into ELEMENT (ID,UNIT) values ('mean(sea_surface_wave_period_from_instrument T24H)','seconds');
Insert into ELEMENT (ID,UNIT) values ('mean(sea_surface_wave_significant_height_from_instrument 1M)','meters');
Insert into ELEMENT (ID,UNIT) values ('mean(sea_surface_wave_significant_height_from_instrument T24H)','meters');
Insert into ELEMENT (ID,UNIT) values ('mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)','degrees');
Insert into ELEMENT (ID,UNIT) values ('mean(snow_coverage_type 1M)','code');
Insert into ELEMENT (ID,UNIT) values ('mean(soil_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(specific_humidity 1M)','gr/kg');
Insert into ELEMENT (ID,UNIT) values ('mean(surface_air_pressure 1M)','hPa');
Insert into ELEMENT (ID,UNIT) values ('mean(surface_air_pressure T1H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('mean(surface_air_pressure T24H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('mean(surface_snow_thickness 1M)','cm');
Insert into ELEMENT (ID,UNIT) values ('mean(surface_snow_thickness T1H)','cm');
Insert into ELEMENT (ID,UNIT) values ('mean(surface_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean(wind_from_direction T1H)','degrees');
Insert into ELEMENT (ID,UNIT) values ('mean(wind_speed 1M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('mean(wind_speed T1H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('mean(wind_speed T24H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('mean(wind_speed_of_gust 1M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('mean(wind_speed_of_gust T24H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('mean_k(air_temperature 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('mean_k(air_temperature T24H)','degC');
Insert into ELEMENT (ID,UNIT) values ('medium_type_cloud','code');
Insert into ELEMENT (ID,UNIT) values ('min(air_pressure_at_sea_level 1M)','hPa');
Insert into ELEMENT (ID,UNIT) values ('min(air_pressure_at_sea_level T24H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('min(air_temperature 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(air_temperature T10M)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(air_temperature T12H)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(air_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(air_temperature T24H)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(cloud_area_fraction 1M)','octas');
Insert into ELEMENT (ID,UNIT) values ('min(cloud_area_fraction T24H)','octas');
Insert into ELEMENT (ID,UNIT) values ('min(cloud_base_height T1H)','meters');
Insert into ELEMENT (ID,UNIT) values ('min(grass_temperature T12H)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(grass_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(grass_temperature T24H)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(max(wind_speed T1H) T24H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('min(max(wind_speed T24H) 1M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('min(min(grass_temperature T1H) 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(relative_humidity 1M)','percent');
Insert into ELEMENT (ID,UNIT) values ('min(relative_humidity T24H)','percent');
Insert into ELEMENT (ID,UNIT) values ('min(sea_state 1M)','code');
Insert into ELEMENT (ID,UNIT) values ('min(sea_state T24H)','code');
Insert into ELEMENT (ID,UNIT) values ('min(sea_surface_temperature 1M)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(sea_surface_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(sea_surface_wave_period_from_instrument 1M)','seconds');
Insert into ELEMENT (ID,UNIT) values ('min(sea_surface_wave_period_from_instrument T24H)','seconds');
Insert into ELEMENT (ID,UNIT) values ('min(sea_surface_wave_significant_height_from_instrument 1M)','meters');
Insert into ELEMENT (ID,UNIT) values ('min(sea_surface_wave_significant_height_from_instrument T24H)','meters');
Insert into ELEMENT (ID,UNIT) values ('min(snow_coverage_type 1M)','code');
Insert into ELEMENT (ID,UNIT) values ('min(snow_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(sum(duration_of_sunshine T24H) 1M)','hours');
Insert into ELEMENT (ID,UNIT) values ('min(surface_air_pressure 1M)','hPa');
Insert into ELEMENT (ID,UNIT) values ('min(surface_air_pressure T1H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('min(surface_air_pressure T24H)','hPa');
Insert into ELEMENT (ID,UNIT) values ('min(surface_snow_thickness 1M)','cm');
Insert into ELEMENT (ID,UNIT) values ('min(surface_snow_thickness T1H)','cm');
Insert into ELEMENT (ID,UNIT) values ('min(surface_temperature T1H)','degC');
Insert into ELEMENT (ID,UNIT) values ('min(visibility_in_air_horizontal 1M)','meters');
Insert into ELEMENT (ID,UNIT) values ('min(visibility_in_air_horizontal T24H)','meters');
Insert into ELEMENT (ID,UNIT) values ('min(wind_speed 1M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('min(wind_speed T24H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('min(wind_speed_of_gust 1M)','m/s');
Insert into ELEMENT (ID,UNIT) values ('min(wind_speed_of_gust T24H)','m/s');
Insert into ELEMENT (ID,UNIT) values ('number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)','number of');
Insert into ELEMENT (ID,UNIT) values ('precipitation_amount','mm');
Insert into ELEMENT (ID,UNIT) values ('qnh_air_pressure','hPa');
Insert into ELEMENT (ID,UNIT) values ('relative_humidity','percent');
Insert into ELEMENT (ID,UNIT) values ('sea_state','code');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_height','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_height_above_lowest_astronomical_tide','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_primary_wave_spectral_density','m*m/H');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_swell_wave_first_mean_height','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_swell_wave_first_mean_period','seconds');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_swell_wave_second_mean_height','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_swell_wave_second_mean_period','seconds');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_swell_wave_significant_height','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_temperature','degC');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_mean_height','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_mean_steepness','degrees');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_period','seconds');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_period_at_variance_spectral_density_maximum','seconds');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_period_at_variance_spectral_density_second_maximum','seconds');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_period_from_instrument','seconds');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_period_of_maximum_height','seconds');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_significant_height','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_significant_height_from_instrument','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_significant_height_from_spectrum','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_steepest_height','meters');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_steepness_of_highest_wave','degrees');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_steepness_of_steepest_wave','degrees');
Insert into ELEMENT (ID,UNIT) values ('sea_surface_wave_zero_upcrossing_period','seconds');
Insert into ELEMENT (ID,UNIT) values ('sea_water_speed','m/s');
Insert into ELEMENT (ID,UNIT) values ('sea_water_to_direction','degrees');
Insert into ELEMENT (ID,UNIT) values ('snow_coverage_type','code');
Insert into ELEMENT (ID,UNIT) values ('snow_temperature','degC');
Insert into ELEMENT (ID,UNIT) values ('soil_temperature','degC');
Insert into ELEMENT (ID,UNIT) values ('specific_humidity','gr/kg');
Insert into ELEMENT (ID,UNIT) values ('state_of_ground','code');
Insert into ELEMENT (ID,UNIT) values ('sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)','sum');
Insert into ELEMENT (ID,UNIT) values ('sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)','sum');
Insert into ELEMENT (ID,UNIT) values ('sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)','sum');
Insert into ELEMENT (ID,UNIT) values ('sum(duration_of_sunshine 1M)','hours');
Insert into ELEMENT (ID,UNIT) values ('sum(duration_of_sunshine T1H)','minutes');
Insert into ELEMENT (ID,UNIT) values ('sum(duration_of_sunshine T24H)','hours');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount 1M)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount T10M)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount T12H)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount T1H)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount T1M)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount T24H)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount T3H)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount T6H)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount T720H)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(precipitation_amount_anomaly 1M)','percent');
Insert into ELEMENT (ID,UNIT) values ('sum(water_evaporation_amount T1H)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum(water_evaporation_amount T24H)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum_over_undefined_period(precipitation_amount 1M)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum_over_undefined_period(precipitation_amount T1H)','mm');
Insert into ELEMENT (ID,UNIT) values ('sum_over_undefined_period(precipitation_amount T24H)','mm');
Insert into ELEMENT (ID,UNIT) values ('surface_air_pressure','hPa');
Insert into ELEMENT (ID,UNIT) values ('surface_albedo','minutes');
Insert into ELEMENT (ID,UNIT) values ('surface_downwelling_longwave_flux_in_air','W/m2');
Insert into ELEMENT (ID,UNIT) values ('surface_downwelling_photosynthetic_radiative_flux_in_air','W/m2');
Insert into ELEMENT (ID,UNIT) values ('surface_downwelling_shortwave_flux_in_air','W/m2');
Insert into ELEMENT (ID,UNIT) values ('surface_net_downward_radiative_flux','W/m2');
Insert into ELEMENT (ID,UNIT) values ('surface_snow_thickness','cm');
Insert into ELEMENT (ID,UNIT) values ('surface_temperature','degC');
Insert into ELEMENT (ID,UNIT) values ('surface_upwelling_longwave_flux_in_air','W/m2');
Insert into ELEMENT (ID,UNIT) values ('surface_upwelling_shortwave_flux_in_air','W/m2');
Insert into ELEMENT (ID,UNIT) values ('temperature_in_surface_snow','degC');
Insert into ELEMENT (ID,UNIT) values ('time_of_event_of_max(air_temperature 1M)','Date');
Insert into ELEMENT (ID,UNIT) values ('time_of_event_of_max(max(wind_speed T24H) 1M)','Date');
Insert into ELEMENT (ID,UNIT) values ('time_of_event_of_max(sum(precipitation_amount T24H) 1M)','Date');
Insert into ELEMENT (ID,UNIT) values ('time_of_event_of_max(wind_speed T1H)','time');
Insert into ELEMENT (ID,UNIT) values ('time_of_event_of_max(wind_speed_of_gust T1H)','time');
Insert into ELEMENT (ID,UNIT) values ('time_of_event_of_min(air_temperature 1M)','Date');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_from_instrument','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_significance1','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_significance1_intensity','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_significance2','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_significance2_intensity','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_significance3','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_significance3_intensity','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_significance4','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_wmo_additional1','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_wmo_additional2','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_wmo_additional3','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_wmo_significance1','code');
Insert into ELEMENT (ID,UNIT) values ('timeperiod_weather_type_wmo_significance2','code');
Insert into ELEMENT (ID,UNIT) values ('visibility_in_air_horizontal','meters');
Insert into ELEMENT (ID,UNIT) values ('volume_fraction_of_water_in_soil','percent');
Insert into ELEMENT (ID,UNIT) values ('water_vapor_partial_pressure_in_air','hPa');
Insert into ELEMENT (ID,UNIT) values ('wind_from_direction','degrees');
Insert into ELEMENT (ID,UNIT) values ('wind_from_direction_of_gust','degrees');
Insert into ELEMENT (ID,UNIT) values ('wind_speed','m/s');
Insert into ELEMENT (ID,UNIT) values ('wind_speed_of_gust','m/s');



# --- !Downs

DELETE FROM ELEMENT;
