# --- !Ups

Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(air_pressure_at_sea_level T24H)','PT24H','Pa','air_pressure_at_sea_level','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(air_pressure_at_sea_level 1M) 1M)','P1M','Pa','air_pressure_at_sea_level','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(air_temperature 1M)','P1M','K','air_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(air_temperature 1M) 1M)','P1M','K','air_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('homogenized(mean(air_temperature_anomaly 1M) 1M)','P1M','K','air_temperature_anomaly','homogenized');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(cloud_area_fraction 1M)','P1M','1','cloud_area_fraction','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('boolean_overcast_weather(cloud_area_fraction T24H)','PT0H0M0S','1','cloud_area_fraction','boolean_overcast_weather');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(cloud_area_fraction 1M) 1M)','P1M','1','cloud_area_fraction','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum_over_undefined_period(precipitation_amount T24H)','PT24H','kg m-2','precipitation_amount','sum_over_undefined_period');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('time_of_event_of_max(sum(precipitation_amount T24H) 1M)','P1M','kg m-2','precipitation_amount','time_of_event_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount T3H)','PT3H','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(time_of_event_of_max(sum(precipitation_amount T24H) 1M) 1M)','P1M','kg m-2','precipitation_amount','time_of_event_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(surface_air_pressure T24H)','PT24H','Pa','surface_air_pressure','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(surface_air_pressure 1M) 1M)','P1M','Pa','surface_air_pressure','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_swell_wave_significant_height','PT0H0M0S','m','sea_surface_swell_wave_significant_height',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(sea_surface_temperature T1H)','PT1H','K','sea_surface_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)','PT10M','s','sea_surface_wave_zero_upcrossing_period','estimated_by_spectral_moments_1');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(surface_temperature T1H)','PT1H','K','surface_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_temperature','PT0H0M0S','K','surface_temperature',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(surface_temperature T12H)','PT12H','K','surface_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(wind_speed 1M)','P1M','m s-1','wind_speed','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(max(wind_speed T1H) T24H)','PT24H','m s-1','wind_speed','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(max(wind_speed T1H) T24H)','PT24H','m s-1','wind_speed','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(max(wind_speed T24H) 1M) 1M)','P1M','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('wind_speed_of_gust','PT0H0M0S','m s-1','wind_speed_of_gust',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed_of_gust T24H)','PT24H','m s-1','wind_speed_of_gust','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed_of_gust T20M)','PT10M','m s-1','wind_speed_of_gust','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_wmo_significance2','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_primary_wave_spectral_density','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_surface_wave_height T10M)','PT10M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_mean(sea_surface_secondary_wave T10M)','PT10M',null,null,'from_direction_of_mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(timeperiod_weather_type_significance1 T24H)','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_significance1','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_mean_height','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(snow_coverage_type 1M)','P1M',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_significance3','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('visibility_in_air_horizontal','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(visibility_in_air_horizontal 1M) 1M)','P1M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('air_pressure_at_sea_level','PT0H0M0S','Pa','air_pressure_at_sea_level',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(air_pressure_at_sea_level 1M)','P1M','Pa','air_pressure_at_sea_level','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(air_pressure_at_sea_level 1M)','P1M','Pa','air_pressure_at_sea_level','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(air_temperature T24H)','PT24H','K','air_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(air_temperature T1H)','PT1H','K','air_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('liquid_water_content_of_surface_snow','PT0H0M0S','kg m-2','liquid_water_content_of_surface_snow',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)','PT24H','1','cloud_area_fraction','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)','PT24H','1','cloud_area_fraction','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(dew_point_temperature 1M)','P1M','K','dew_point_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(dew_point_temperature T24H) 1M)','P1M','K','dew_point_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(duration_of_sunshine 1M) 1M)','P1M','s','duration_of_sunshine','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('homogenized(precipitation_amount 1M)','P1M','kg m-2','precipitation_amount','homogenized');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount T720H)','PT720H','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount T1M)','PT0H0M0S','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(relative_humidity 1M)','P1M','1','relative_humidity','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(relative_humidity T24H)','PT1H','1','relative_humidity','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(relative_humidity 1M)','P1M','1','relative_humidity','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(relative_humidity 1M) 1M)','P1M','1','relative_humidity','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(sea_surface_temperature T1H)','P1M','K','sea_surface_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_downwelling_longwave_flux_in_air','PT0H0M0S','W m-2','surface_downwelling_longwave_flux_in_air',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(surface_snow_thickness 1M)','P1M','m','surface_snow_thickness','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(surface_snow_thickness 1M) 1M)','P1M','m','surface_snow_thickness','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(surface_snow_thickness 1M) 1M)','P1M','m','surface_snow_thickness','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(surface_temperature T1H)','PT1H','K','surface_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('time_of_event_of_max(max(wind_speed T24H) 1M)','P1M','m s-1','wind_speed','time_of_event_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('time_of_event_of_max(wind_speed T1H)','PT0H0M0S','m s-1','wind_speed','time_of_event_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed T6H)','PT6H','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_max(wind_speed T20M)','PT20M','m s-1','wind_speed','from_direction_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed_of_gust T10M)','PT10M','m s-1','wind_speed_of_gust','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(wind_speed_of_gust 1M) 1M)','P1M','m s-1','wind_speed_of_gust','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_peak(sea_surface_primary_wave T20M)','PT20M',null,null,'from_direction_of_peak');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('high_type_cloud','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('low_type_cloud','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_base_height','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_steepness_of_highest_wave','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_base_height2','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(sea_surface_wave_significant_height_from_instrument T24H)','PT24H',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(sea_surface_wave_significant_height_from_instrument 1M) 1M)','P1M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('instant_weather_type_from_instrument','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('change_over_time_in_surface_air_pressure','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('homogenized(sum(precipitation_amount_anomaly 1M) 1M)','P1M',null,null,'homogenized');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('wind_from_direction_of_gust','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_swell_wave_first_mean_height','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('snow_coverage_type','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(snow_coverage_type 1M)','P1M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(visibility_in_air_horizontal 1M)','P1M',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(beaufort_wind_force T6H)','PT6H','1','beaufort_wind_force','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(air_pressure_at_sea_level T24H)','PT24H','Pa','air_pressure_at_sea_level','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('integral_of_excess(mean(air_temperature T24H) 1M 17.0)','P1M','K','air_temperature','integral_of_excess');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(air_temperature T12H)','PT12H','K','air_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(air_temperature T24H)','PT12H','K','air_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(air_temperature T10M)','PT10M','K','air_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(integral_of_deficit(mean(air_temperature T24H) 1M 5.0) 1M)','P1M','K','air_temperature','integral_of_deficit');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum_over_undefined_period(precipitation_amount T1H)','PT1H','kg m-2','precipitation_amount','sum_over_undefined_period');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)','P1M','kg m-2','precipitation_amount','number_of_days_gte');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(sum(precipitation_amount T24H) 1M)','P1M','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(specific_humidity 1M)','P1M','1','specific_humidity','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('specific_humidity','PT0H0M0S','1','specific_humidity',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_air_pressure','PT0H0M0S','Pa','surface_air_pressure',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(surface_air_pressure 1M)','P1M','Pa','surface_air_pressure','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(relative_humidity T24H)','PT1H','1','relative_humidity','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(relative_humidity T24H)','PT24H','1','relative_humidity','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(relative_humidity 1M) 1M)','P1M','1','relative_humidity','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_period_at_variance_spectral_density_maximum','PT0H0M0S','s','sea_surface_wave_period_at_variance_spectral_density_maximum',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(surface_snow_thickness T1H)','PT1H','m','surface_snow_thickness','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(surface_snow_thickness 1M)','P1M','m','surface_snow_thickness','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(wind_speed T24H)','PT24H','m s-1','wind_speed','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed T20M)','PT20M','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('time_of_event_of_max(wind_speed_of_gust T1H)','PT0H0M0S','m s-1','wind_speed_of_gust','time_of_event_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(wind_speed_of_gust 1M)','P1M','m s-1','wind_speed_of_gust','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_base_height4','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('instant_weather_type_significance3','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_area_fraction1','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_surface_wave_period_from_instrument T24H)','PT24H',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_surface_wave_period_from_instrument 1M)','P1M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(sea_surface_wave_significant_height_from_instrument T24H)','PT24H',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(sea_surface_wave_significant_height_from_instrument 1M) 1M)','P1M',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(snow_temperature T1H)','PT1H',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_base_height1','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_area_fraction3','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount_anomaly 1M)','P1M',null,null,'sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_state 1M)','PT0H0M0S',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_state','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('snow_coverage_type','PT24H',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('air_temperature','PT0H0M0S','K','air_temperature',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('homogenized(mean(air_temperature T1H) T24H)','PT24H','K','air_temperature','homogenized');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(air_temperature T1H)','PT1H','K','air_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(max(air_temperature T24H) 1M)','P1M','K','air_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('integral_of_deficit(mean(air_temperature T24H) 1M 0.0)','P1M','K','air_temperature','integral_of_deficit');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(air_temperature 1M) 1M)','P1M','K','air_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(air_temperature_anomaly 1M) 1M)','P1M','K','air_temperature_anomaly','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('low_type_cloud_area_fraction','PT0H0M0S','1','low_type_cloud_area_fraction',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)','PT24H','1','cloud_area_fraction','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('boolean_fair_weather(cloud_area_fraction T24H)','PT0H0M0S','1','cloud_area_fraction','boolean_fair_weather');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(dew_point_temperature T24H)','PT24H','K','dew_point_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(duration_of_sunshine 1M)','P1M','s','duration_of_sunshine','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(duration_of_sunshine 1M) 1M)','P1M','s','duration_of_sunshine','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount T1H)','PT1H','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum_over_undefined_period(precipitation_amount T24H)','P1M','kg m-2','precipitation_amount','sum_over_undefined_period');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount T10M)','PT0H0M0S','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(specific_humidity 1M) 1M)','P1M','1','specific_humidity','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(surface_air_pressure T1H)','PT1H','Pa','surface_air_pressure','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(surface_air_pressure 1M) 1M)','P1M','Pa','surface_air_pressure','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(surface_air_pressure 1M) 1M)','P1M','Pa','surface_air_pressure','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_temperature','PT0H0M0S','K','sea_surface_temperature',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_surface_temperature T1H)','P1M','K','sea_surface_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(sea_surface_temperature T1H)','PT1H','K','sea_surface_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_zero_upcrossing_period','PT0H0M0S','s','sea_surface_wave_zero_upcrossing_period',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('soil_temperature','PT1H','K','soil_temperature',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_upwelling_longwave_flux_in_air','PT0H0M0S','W m-2','surface_upwelling_longwave_flux_in_air',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_snow_thickness','PT0H0M0S','m','surface_snow_thickness',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(surface_snow_thickness T1H)','PT1H','m','surface_snow_thickness','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(surface_temperature T24H)','PT24H','K','surface_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(min(surface_temperature T1H) 1M)','P1M','K','surface_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(min(surface_temperature T1H) 1M) 1M)','P1M','K','surface_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(wind_from_direction T1H)','PT1H','degree','wind_from_direction','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(wind_speed T1H)','PT1H','m s-1','wind_speed','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed T3H)','PT3H','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed T1H)','PT1H','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(max(wind_speed T24H) 1M)','P1M','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('beaufort_wind_force','PT0H0M0S','m s-1','wind_speed',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(max(wind_speed T24H) 1M) 1M)','P1M','m s-1','wind_speed','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(wind_speed 1M) 1M)','P1M','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(wind_speed 1M) 1M)','P1M','m s-1','wind_speed','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed_of_gust T1H)','PT1H','m s-1','wind_speed_of_gust','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed_of_gust 1M)','P1M','m s-1','wind_speed_of_gust','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(wind_speed_of_gust 1M) 1M)','P1M','m s-1','wind_speed_of_gust','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction(sea_surface_swell_wave_second_mean_height T3H)','PT3H',null,null,'from_direction');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_area_fraction2','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_period_at_variance_spectral_density_second_maximum','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_significance1_intensity','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('instant_weather_type_significance1','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('volume_fraction_of_water_in_soil','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_surface_wave_period T20M) ','PT20M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_period','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('qnh_air_pressure','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_period_from_instrument','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(sea_surface_wave_period_from_instrument 1M)','P1M',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(sea_surface_wave_period_from_instrument 1M) 1M)','P1M',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_significance2_intensity','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('instant_weather_type','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_mean(sea_surface_wave_total_energy T20M)','PT20M',null,null,'from_direction_of_mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_wmo_additional3','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(sea_state T24H)','PT0H0M0S',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(snow_coverage_type 1M) 1M)','P1M',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(visibility_in_air_horizontal T24H)','PT24H',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('homogenized(mean(air_temperature 1M) 1M)','P1M','K','air_temperature','homogenized');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('time_of_event_of_min(air_temperature 1M)','P1M','K','air_temperature','time_of_event_of_min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(air_temperature T24H)','PT24H','K','air_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean_k(air_temperature T24H)','PT24H','K','air_temperature','mean_k');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('time_of_event_of_max(air_temperature 1M)','P1M','K','air_temperature','time_of_event_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(air_temperature 1M)','P1M','K','air_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(integral_of_deficit(mean(air_temperature T24H) 1M 0.0) 1M)','P1M','K','air_temperature','integral_of_deficit');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0) 1M)','P1M','K','air_temperature','integral_of_excess_interpolated');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(max(air_temperature T24H) 1M) 1M)','P1M','K','air_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(time_of_event_of_min(air_temperature 1M) 1M)','P1M','K','air_temperature','time_of_event_of_min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(cloud_area_fraction T24H)','PT24H','1','cloud_area_fraction','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('diffuse_downwelling_shortwave_flux_in_air','PT0H0M0S','W m-2','diffuse_downwelling_shortwave_flux_in_air',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('duration_of_sunshine','PT0H0M0S','s','duration_of_sunshine',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(surface_air_pressure T24H)','PT24H','Pa','surface_air_pressure','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(surface_air_pressure T1H)','PT1H','Pa','surface_air_pressure','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_albedo','PT0H0M0S','1','surface_albedo',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('relative_humidity','PT0H0M0S','1','relative_humidity',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(relative_humidity T1H)','PT1H','1','relative_humidity','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(relative_humidity T24H)','PT1H','1','relative_humidity','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(sea_surface_temperature T1H) 1M)','P1M','K','sea_surface_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('temperature_in_surface_snow','PT0H0M0S','K','temperature_in_surface_snow',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(min(surface_temperature T1H) 1M) 1M)','P1M','K','surface_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_net_downward_radiative_flux','PT0H0M0S','W m-2','surface_net_downward_radiative_flux',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('water_vapor_partial_pressure_in_air','PT0H0M0S','Pa','water_vapor_partial_pressure_in_air',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(wind_speed 1M)','P1M','m s-1','wind_speed','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(max(wind_speed T24H) 1M)','P1M','m s-1','wind_speed','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(time_of_event_of_max(max(wind_speed T24H) 1M) 1M)','P1M','m s-1','wind_speed','time_of_event_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(wind_speed_of_gust 1M)','P1M','m s-1','wind_speed_of_gust','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(wind_speed_of_gust 1M) 1M)','P1M','m s-1','wind_speed_of_gust','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_swell_wave_second_mean_height','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_mean(sea_surface_primary_wave T20M) ','PT20M',null,null,'from_direction_of_mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_peak(sea_surface_primary_wave)','PT10M',null,null,'from_direction_of_peak');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_significant_height_from_spectrum','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_surface_wave_height T20M)','PT20M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(sea_surface_wave_period_from_instrument 1M) 1M)','P1M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(sea_surface_wave_significant_height_from_instrument 1M)','P1M',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_surface_wave_significant_height_from_instrument 1M)','P1M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_surface_wave_significant_height_from_instrument T24H)','PT24H',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('weather_symbol(instant_weather_type cloud_area_fraction T1H)','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_mean(sea_surface_wave_total_energy T10M)','PT10M',null,null,'from_direction_of_mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_height','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_significance2','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_significance3_intensity','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction(sea_surface_swell_wave_first_mean_height T3H)','PT3H',null,null,'from_direction');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(sea_state 1M)','PT0H0M0S',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_state T24H)','PT0H0M0S',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(sea_state T24H) 1M)','PT0H0M0S',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(snow_coverage_type 1M) 1M)','P1M',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('directional_spread(sea_surface_peak_period T20M)','PT20M',null,null,'directional_spread');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(visibility_in_air_horizontal 1M) 1M)','P1M',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(air_pressure_at_sea_level 1M)','P1M','Pa','air_pressure_at_sea_level','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(air_pressure_at_sea_level 1M) 1M)','P1M','Pa','air_pressure_at_sea_level','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(air_pressure_at_sea_level 1M) 1M)','P1M','Pa','air_pressure_at_sea_level','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('integral_of_excess(mean(air_temperature T1H) T24H 17.0)','PT24H','K','air_temperature','integral_of_excess');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(air_temperature T12H)','PT12H','K','air_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(air_temperature T1H)','PT1H','K','air_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(air_temperature 1M)','P1M','K','air_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(air_temperature T10M)','PT10M','K','air_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(air_temperature 1M) 1M)','P1M','K','air_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(cloud_area_fraction T24H)','PT24H','1','cloud_area_fraction','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('boolean_clear_sky_weather(cloud_area_fraction T24H)','PT0H0M0S','1','cloud_area_fraction','boolean_clear_sky_weather');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('dew_point_temperature','PT0H0M0S','K','dew_point_temperature',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(sum(precipitation_amount T24H) 1M) 1M)','P1M','kg m-2','precipitation_amount','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(surface_air_pressure T1H)','PT1H','Pa','surface_air_pressure','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(surface_air_pressure 1M)','P1M','Pa','surface_air_pressure','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(surface_air_pressure T24H)','PT24H','Pa','surface_air_pressure','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(surface_air_pressure 1M)','P1M','Pa','surface_air_pressure','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(relative_humidity T24H)','PT24H','1','relative_humidity','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(relative_humidity T24H)','PT24H','1','relative_humidity','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(relative_humidity 1M) 1M)','P1M','1','relative_humidity','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sea_surface_temperature T1H)','PT1H','K','sea_surface_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(soil_temperature T1H)','PT1H','K','soil_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_downwelling_photosynthetic_radiative_flux_in_air','PT0H0M0S','W m-2','surface_downwelling_photosynthetic_radiative_flux_in_air',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(surface_snow_thickness 1M)','P1M','m','surface_snow_thickness','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(surface_snow_thickness 1M) 1M)','P1M','m','surface_snow_thickness','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(min(surface_temperature T1H) 1M) 1M)','P1M','K','surface_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(water_vapor_partial_pressure_in_air 1M 1M)','P1M','Pa','water_vapor_partial_pressure_in_air',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_max(wind_speed T3H)','PT3H','m s-1','wind_speed','from_direction_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(wind_speed T24H)','PT24H','m s-1','wind_speed','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed T24H)','PT24H','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(wind_speed 1M) 1M)','P1M','m s-1','wind_speed','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(max(wind_speed T1H) T24H)','PT24H','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_max(wind_speed_of_gust T1H)','PT1H','m s-1','wind_speed_of_gust','from_direction_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed_of_gust T20M)','PT20M','m s-1','wind_speed_of_gust','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_max(wind_speed_of_gust T10M)','PT10M','m s-1','wind_speed_of_gust','from_direction_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_steepness_of_steepest_wave','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_wmo_significance1','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_significance4','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_peak(sea_surface_secondary_wave T10M)','PT10M',null,null,'from_direction_of_peak');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_swell_wave_second_mean_period','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_wmo_additional2','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('directional_spread(sea_surface_wave_total_energy T20M)','PT20M',null,null,'directional_spread');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_peak(sea_surface_wave_total_energy T10M)','PT10M',null,null,'from_direction_of_peak');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('snow_temperature','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)','PT20M',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_steepest_height','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_swell_wave_first_mean_period','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction(sea_surface_swell_wave_first_mean_height T10M)','PT10M',null,null,'from_direction');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(sea_state T24H) 1M)','PT0H0M0S',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(snow_coverage_type 1M)','P1M',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(air_pressure_at_sea_level T24H)','PT24H','Pa','air_pressure_at_sea_level','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('integral_of_deficit(mean(air_temperature T1H) T24H 5.0)','PT24H','K','air_temperature','integral_of_deficit');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)','P1M','K','air_temperature','integral_of_excess_interpolated');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean_k(air_temperature 1M) 1M)','P1M','K','air_temperature','mean_k');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(min(air_temperature T24H) 1M) 1M)','P1M','K','air_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(air_temperature_anomaly 1M)','PT0H0M0S','K','air_temperature_anomaly','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(cloud_area_fraction 1M)','P1M','1','cloud_area_fraction','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(cloud_area_fraction 1M)','P1M','1','cloud_area_fraction','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_area_fraction','PT0H0M0S','1','cloud_area_fraction',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(cloud_area_fraction 1M) 1M)','P1M','1','cloud_area_fraction','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount 1M)','P1M','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('precipitation_amount','PT0H0M0S','kg m-2','precipitation_amount',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount T24H)','PT24H','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount T12H)','PT12H','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1) 1M)','P1M','kg m-2','precipitation_amount','number_of_days_gte');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(sum(precipitation_amount 1M) 1M)','P1M','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(sea_surface_temperature T1H) 1M)','P1M','K','sea_surface_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(max(sea_surface_temperature T1H) 1M)','P1M','K','sea_surface_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_downwelling_shortwave_flux_in_air','PT0H0M0S','W m-2','surface_downwelling_shortwave_flux_in_air',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('change_over_timespan(surface_snow_thickness T24H)','PT24H','m','surface_snow_thickness','change_over_timespan');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(surface_snow_thickness T1H)','PT1H','m','surface_snow_thickness','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(min(surface_temperature T1H) 1M)','P1M','K','surface_temperature','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(min(surface_temperature T1H) 1M)','P1M','K','surface_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(water_evaporation_amount T1H)','PT0H0M0S','kg m-2','water_evaporation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_max(wind_speed T1H)','PT1H','m s-1','wind_speed','from_direction_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('wind_speed','PT0H0M0S','m s-1','wind_speed',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed 1M)','P1M','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(max(wind_speed T24H) 1M) 1M)','P1M','m s-1','wind_speed','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_max(wind_speed_of_gust T10M)','PT20M','m s-1','wind_speed_of_gust','from_direction_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(wind_speed_of_gust T24H)','PT24H','m s-1','wind_speed_of_gust','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_wmo_additional1','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_mean_steepness','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_base_height3','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('instant_weather_type_significance2','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)','PT20M',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(sea_surface_wave_period_from_instrument T24H)','PT24H',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(sea_surface_wave_period_from_instrument 1M)','P1M',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_water_to_direction','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(sea_surface_wave_significant_height_from_instrument 1M) 1M)','P1M',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(snow_temperature T1H)','PT1H',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('cloud_area_fraction4','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(sum(precipitation_amount_anomaly 1M) 1M)','P1M',null,null,'sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('state_of_ground','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_height_above_lowest_astronomical_tide','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(visibility_in_air_horizontal T24H)','PT24H',null,null,'max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('integral_of_deficit(mean(air_temperature T24H) 1M 5.0)','P1M','K','air_temperature','integral_of_deficit');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(air_temperature T24H)','PT24H','K','air_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean_k(air_temperature 1M)','P1M','K','air_temperature','mean_k');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(min(air_temperature T24H) 1M)','P1M','K','air_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('integral_of_deficit(mean(air_temperature T1H) T24H 0.0)','PT24H','K','air_temperature','integral_of_deficit');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(integral_of_excess(mean(air_temperature T24H) 1M 17.0) 1M)','P1M','K','air_temperature','integral_of_excess');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(time_of_event_of_max(air_temperature 1M) 1M)','P1M','K','air_temperature','time_of_event_of_max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('latitude','PT0H0M0S','degree_north','latitude',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('longitude','PT0H0M0S','degree_east','longitude',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('change_over_time_in_surface_snow_amount','PT0H0M0S','kg m-2','change_over_time_in_surface_snow_amount',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(cloud_area_fraction T24H)','PT24H','1','cloud_area_fraction','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(mean(cloud_area_fraction 1M) 1M)','P1M','1','cloud_area_fraction','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(duration_of_sunshine 1M)','P1M','s','duration_of_sunshine','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(duration_of_sunshine 1M)','P1M','s','duration_of_sunshine',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(sum(precipitation_amount T24H) 1M)','P1M','kg m-2','precipitation_amount','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(precipitation_amount T6H)','PT6H','kg m-2','precipitation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(relative_humidity 1M)','P1M','1','relative_humidity','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(sea_surface_temperature T1H)','P1M','K','sea_surface_temperature','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_significant_height','PT0H0M0S','m','sea_surface_wave_significant_height',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_water_speed','PT0H0M0S','m s-1','sea_water_speed',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('surface_upwelling_shortwave_flux_in_air','PT0H0M0S','W m-2','surface_upwelling_shortwave_flux_in_air',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(surface_temperature T1H)','PT1H','K','surface_temperature','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sum(water_evaporation_amount T24H)','PT0H0M0S','kg m-2','water_evaporation_amount','sum');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('wind_from_direction','PT0H0M0S','degree','wind_from_direction',null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(max(wind_speed T24H) 1M)','P1M','m s-1','wind_speed','mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(wind_speed T10M)','PT10M','m s-1','wind_speed','max');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(wind_speed_of_gust T24H)','PT24H','m s-1','wind_speed_of_gust','min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('from_direction_of_mean(sea_surface_primary_wave T10M)','PT10M',null,null,'from_direction_of_mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(cloud_base_height T1H)','PT1H',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(sea_surface_wave_period_from_instrument T24H)','PT24H',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(sea_surface_wave_period_from_instrument 1M) 1M)','P1M',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('medium_type_cloud','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_significant_height_from_instrument','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('min(sea_surface_wave_significant_height_from_instrument 1M)','P1M',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(snow_temperature T1H)','PT1H',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('sea_surface_wave_period_of_maximum_height','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('percent_coverage(min(snow_coverage_type 1M) 1M)','P1M',null,null,'min');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('timeperiod_weather_type_from_instrument','PT0H0M0S',null,null,null);
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)','PT20M',null,null,'mean');
Insert into ELEMENT (NAME,TIMESPAN,UNIT,CF_STANDARD_NAME,CF_CELL_METHOD) values ('max(visibility_in_air_horizontal 1M)','P1M',null,null,'max');

# --- !Downs

SELECT 1;