# --- !Ups

CREATE TABLE metno_element (
  element_id TEXT NOT NULL,
  metno_name TEXT NOT NULL
);

insert into metno_element (element_id, metno_name) values ('from_direction_of_mean(sea_surface_wave_total_energy PT20M)', 'sea_surface_wave_total_energy');
insert into metno_element (element_id, metno_name) values ('cloud_base_height1', 'cloud_base_height1');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_steepest_height', 'sea_surface_wave_steepest_height');
insert into metno_element (element_id, metno_name) values ('sea_surface_swell_wave_second_mean_period', 'sea_surface_swell_wave_second_mean_period');
insert into metno_element (element_id, metno_name) values ('timeperiod_weather_type_from_instrument', 'timeperiod_weather_type_from_instrument');
insert into metno_element (element_id, metno_name) values ('medium_type_cloud', 'medium_type_cloud');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_tertiary_significance_intensity P1D)', 'precipitation_type_tertiary_significance_intensity');
insert into metno_element (element_id, metno_name) values ('sea_water_to_direction', 'sea_water_to_direction');
insert into metno_element (element_id, metno_name) values ('wind_from_direction_of_gust', 'wind_from_direction_of_gust');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_mean_steepness', 'sea_surface_wave_mean_steepness');
insert into metno_element (element_id, metno_name) values ('cloud_base_height', 'cloud_base_height');
insert into metno_element (element_id, metno_name) values ('precipitation_type_secondary_significance', 'precipitation_type_secondary_significance');
insert into metno_element (element_id, metno_name) values ('min(sea_surface_wave_significant_height_from_instrument P1D)', 'sea_surface_wave_significant_height_from_instrument');
insert into metno_element (element_id, metno_name) values ('max(sea_surface_wave_period_from_instrument P1D)', 'sea_surface_wave_period_from_instrument');
insert into metno_element (element_id, metno_name) values ('min(sea_state P1D)', 'sea_state');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_primary_significance_intensity P1D)', 'precipitation_type_primary_significance_intensity');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_steepness_of_steepest_wave', 'sea_surface_wave_steepness_of_steepest_wave');
insert into metno_element (element_id, metno_name) values ('mean(sea_surface_wave_significant_height_from_instrument P1M)', 'sea_surface_wave_significant_height_from_instrument');
insert into metno_element (element_id, metno_name) values ('min(grass_temperature P1D)', 'grass_temperature');
insert into metno_element (element_id, metno_name) values ('cloud_area_fraction4', 'cloud_area_fraction4');
insert into metno_element (element_id, metno_name) values ('directional_spread(sea_surface_wave_total_energy PT20M)', 'sea_surface_wave_total_energy');
insert into metno_element (element_id, metno_name) values ('from_direction_of_mean(sea_surface_wave_total_energy PT10M)', 'sea_surface_wave_total_energy');
insert into metno_element (element_id, metno_name) values ('max(visibility_in_air_horizontal P1D)', 'visibility_in_air_horizontal');
insert into metno_element (element_id, metno_name) values ('mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period PT20M)', 'sea_surface_wind_wave_from_direction_of_spectral_peak_period');
insert into metno_element (element_id, metno_name) values ('max(sea_surface_wave_period PT20M) ', 'sea_surface_wave_period');
insert into metno_element (element_id, metno_name) values ('over_time(weather_type_additional1 PT6H)', 'weather_type_additional1');
insert into metno_element (element_id, metno_name) values ('max(sea_surface_wave_significant_height_from_instrument P1M)', 'sea_surface_wave_significant_height_from_instrument');
insert into metno_element (element_id, metno_name) values ('max(snow_coverage_type P1M)', 'snow_coverage_type');
insert into metno_element (element_id, metno_name) values ('max(visibility_in_air_horizontal P1M)', 'visibility_in_air_horizontal');
insert into metno_element (element_id, metno_name) values ('over_time(weather_type_primary_significance PT3H)', 'weather_type_primary_significance');
insert into metno_element (element_id, metno_name) values ('mean(sea_surface_wave_significant_height_from_instrument P1D)', 'sea_surface_wave_significant_height_from_instrument');
insert into metno_element (element_id, metno_name) values ('max(sea_state P1M)', 'sea_state');
insert into metno_element (element_id, metno_name) values ('weather_type_automatic', 'weather_type_automatic');
insert into metno_element (element_id, metno_name) values ('mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period PT20M)', 'sea_surface_swell_wave_from_direction_of_spectral_peak_period');
insert into metno_element (element_id, metno_name) values ('from_direction(sea_surface_swell_wave_first_mean_height PT10M)', 'sea_surface_swell_wave_first_mean_height');
insert into metno_element (element_id, metno_name) values ('from_direction_of_peak(sea_surface_primary_wave PT20M)', 'sea_surface_primary_wave');
insert into metno_element (element_id, metno_name) values ('sea_surface_primary_wave_spectral_density', 'sea_surface_primary_wave_spectral_density');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_primary_significance PT6H)', 'precipitation_type_primary_significance');
insert into metno_element (element_id, metno_name) values ('mean(sea_surface_wave_period_from_instrument P1M)', 'sea_surface_wave_period_from_instrument');
insert into metno_element (element_id, metno_name) values ('volume_fraction_of_water_in_soil', 'volume_fraction_of_water_in_soil');
insert into metno_element (element_id, metno_name) values ('min(cloud_base_height PT1H)', 'cloud_base_height');
insert into metno_element (element_id, metno_name) values ('over_time(weather_type_additional3 PT6H)', 'weather_type_additional3');
insert into metno_element (element_id, metno_name) values ('from_direction_of_mean(sea_surface_primary_wave PT10M)', 'sea_surface_primary_wave');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_period_at_variance_spectral_density_second_maximum', 'sea_surface_wave_period_at_variance_spectral_density_second_maximum');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_steepness_of_highest_wave', 'sea_surface_wave_steepness_of_highest_wave');
insert into metno_element (element_id, metno_name) values ('max(sea_surface_wave_height PT20M)', 'sea_surface_wave_height');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_period', 'sea_surface_wave_period');
insert into metno_element (element_id, metno_name) values ('weather_type', 'weather_type');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_mean_height', 'sea_surface_wave_mean_height');
insert into metno_element (element_id, metno_name) values ('sea_wave_spectrum_peak_energy', 'sea_wave_spectrum_peak_energy');
insert into metno_element (element_id, metno_name) values ('mean(min(grass_temperature P1D) P1M)', 'grass_temperature');
insert into metno_element (element_id, metno_name) values ('max(sea_surface_wave_significant_height_from_instrument P1D)', 'sea_surface_wave_significant_height_from_instrument');
insert into metno_element (element_id, metno_name) values ('min(min(grass_temperature P1D) P1M)', 'grass_temperature');
insert into metno_element (element_id, metno_name) values ('min(grass_temperature PT1H)', 'grass_temperature');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_secondary_significance P1D)', 'precipitation_type_secondary_significance');
insert into metno_element (element_id, metno_name) values ('over_time(weather_type_secondary_significance PT3H)', 'weather_type_secondary_significance');
insert into metno_element (element_id, metno_name) values ('min(visibility_in_air_horizontal P1D)', 'visibility_in_air_horizontal');
insert into metno_element (element_id, metno_name) values ('min(visibility_in_air_horizontal P1M)', 'visibility_in_air_horizontal');
insert into metno_element (element_id, metno_name) values ('min(snow_coverage_type P1M)', 'snow_coverage_type');
insert into metno_element (element_id, metno_name) values ('from_direction_of_peak(sea_surface_primary_wave)', 'sea_surface_primary_wave');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_significant_height_from_spectrum', 'sea_surface_wave_significant_height_from_spectrum');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_secondary_significance_intensity P1D)', 'precipitation_type_secondary_significance_intensity');
insert into metno_element (element_id, metno_name) values ('snow_coverage_type', 'snow_coverage_type');
insert into metno_element (element_id, metno_name) values ('high_type_cloud', 'high_type_cloud');
insert into metno_element (element_id, metno_name) values ('state_of_ground', 'state_of_ground');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_significant_height_from_instrument', 'sea_surface_wave_significant_height_from_instrument');
insert into metno_element (element_id, metno_name) values ('grass_temperature', 'grass_temperature');
insert into metno_element (element_id, metno_name) values ('max(sea_state P1D)', 'sea_state');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_tertiary_significance PT6H)', 'precipitation_type_tertiary_significance');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_tertiary_significance P1D)', 'precipitation_type_tertiary_significance');
insert into metno_element (element_id, metno_name) values ('directional_spread(sea_surface_peak_period PT20M)', 'sea_surface_peak_period');
insert into metno_element (element_id, metno_name) values ('cloud_area_fraction2', 'cloud_area_fraction2');
insert into metno_element (element_id, metno_name) values ('cloud_area_fraction3', 'cloud_area_fraction3');
insert into metno_element (element_id, metno_name) values ('cloud_base_height3', 'cloud_base_height3');
insert into metno_element (element_id, metno_name) values ('cloud_base_height4', 'cloud_base_height4');
insert into metno_element (element_id, metno_name) values ('sea_surface_swell_wave_first_mean_height', 'sea_surface_swell_wave_first_mean_height');
insert into metno_element (element_id, metno_name) values ('from_direction(sea_surface_swell_wave_second_mean_height PT3H)', 'sea_surface_swell_wave_second_mean_height');
insert into metno_element (element_id, metno_name) values ('max(grass_temperature PT1H)', 'grass_temperature');
insert into metno_element (element_id, metno_name) values ('max(sea_surface_wave_period_from_instrument P1M)', 'sea_surface_wave_period_from_instrument');
insert into metno_element (element_id, metno_name) values ('precipitation_type_primary_significance', 'precipitation_type_primary_significance');
insert into metno_element (element_id, metno_name) values ('over_time(weather_type_primary_significance PT6H)', 'weather_type_primary_significance');
insert into metno_element (element_id, metno_name) values ('over_time(weather_type_additional2 PT6H)', 'weather_type_additional2');
insert into metno_element (element_id, metno_name) values ('mean(snow_coverage_type P1M)', 'snow_coverage_type');
insert into metno_element (element_id, metno_name) values ('mean(grass_temperature PT1H)', 'grass_temperature');
insert into metno_element (element_id, metno_name) values ('sea_surface_swell_wave_second_mean_height', 'sea_surface_swell_wave_second_mean_height');
insert into metno_element (element_id, metno_name) values ('visibility_in_air_horizontal', 'visibility_in_air_horizontal');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_secondary_significance PT6H)', 'precipitation_type_secondary_significance');
insert into metno_element (element_id, metno_name) values ('precipitation_type_tertiary_significance', 'precipitation_type_tertiary_significance');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_primary_significance P1D)', 'precipitation_type_primary_significance');
insert into metno_element (element_id, metno_name) values ('cloud_area_fraction1', 'cloud_area_fraction1');
insert into metno_element (element_id, metno_name) values ('cloud_base_height2', 'cloud_base_height2');
insert into metno_element (element_id, metno_name) values ('max(sea_surface_wave_height PT10M)', 'sea_surface_wave_height');
insert into metno_element (element_id, metno_name) values ('sea_surface_swell_wave_first_mean_period', 'sea_surface_swell_wave_first_mean_period');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_period_of_maximum_height', 'sea_surface_wave_period_of_maximum_height');
insert into metno_element (element_id, metno_name) values ('from_direction(sea_surface_swell_wave_first_mean_height PT3H)', 'sea_surface_swell_wave_first_mean_height');
insert into metno_element (element_id, metno_name) values ('from_direction_of_peak(sea_surface_secondary_wave PT10M)', 'sea_surface_secondary_wave');
insert into metno_element (element_id, metno_name) values ('qnh_air_pressure', 'qnh_air_pressure');
insert into metno_element (element_id, metno_name) values ('instant_weather_type_from_instrument', 'instant_weather_type_from_instrument');
insert into metno_element (element_id, metno_name) values ('min(grass_temperature PT12H)', 'grass_temperature');
insert into metno_element (element_id, metno_name) values ('sea_state', 'sea_state');
insert into metno_element (element_id, metno_name) values ('low_type_cloud', 'low_type_cloud');
insert into metno_element (element_id, metno_name) values ('min(sea_surface_wave_period_from_instrument P1D)', 'sea_surface_wave_period_from_instrument');
insert into metno_element (element_id, metno_name) values ('mean(sea_surface_wave_period_from_instrument P1D)', 'sea_surface_wave_period_from_instrument');
insert into metno_element (element_id, metno_name) values ('over_time(precipitation_type_quaternary_significance PT6H)', 'precipitation_type_quaternary_significance');
insert into metno_element (element_id, metno_name) values ('mean(sea_surface_wave_from_direction_of_spectral_peak_period PT20M)', 'sea_surface_wave_from_direction_of_spectral_peak_period');
insert into metno_element (element_id, metno_name) values ('min(sea_surface_wave_significant_height_from_instrument P1M)', 'sea_surface_wave_significant_height_from_instrument');
insert into metno_element (element_id, metno_name) values ('over_time(weather_type_secondary_significance PT6H)', 'weather_type_secondary_significance');
insert into metno_element (element_id, metno_name) values ('sea_surface_height', 'sea_surface_height');
insert into metno_element (element_id, metno_name) values ('from_direction_of_mean(sea_surface_secondary_wave PT10M)', 'sea_surface_secondary_wave');
insert into metno_element (element_id, metno_name) values ('from_direction_of_peak(sea_surface_wave_total_energy PT10M)', 'sea_surface_wave_total_energy');
insert into metno_element (element_id, metno_name) values ('sea_surface_height_above_lowest_astronomical_tide', 'sea_surface_height_above_lowest_astronomical_tide');
insert into metno_element (element_id, metno_name) values ('sea_surface_wave_period_from_instrument', 'sea_surface_wave_period_from_instrument');
insert into metno_element (element_id, metno_name) values ('weather_symbol(instant_weather_type cloud_area_fraction PT6H)', 'instant_weather_type');
insert into metno_element (element_id, metno_name) values ('max(min(grass_temperature P1D) P1M)', 'grass_temperature');
insert into metno_element (element_id, metno_name) values ('sum(precipitation_amount_anomaly P1M)', 'precipitation_amount_anomaly');
insert into metno_element (element_id, metno_name) values ('min(sea_state P1M)', 'sea_state');
insert into metno_element (element_id, metno_name) values ('best_estimate_sum(precipitation_amount_anomaly P1M)', 'precipitation_amount_anomaly');
insert into metno_element (element_id, metno_name) values ('from_direction_of_mean(sea_surface_primary_wave PT20M) ', 'sea_surface_primary_wave');
insert into metno_element (element_id, metno_name) values ('min(sea_surface_wave_period_from_instrument P1M)', 'sea_surface_wave_period_from_instrument');

# --- !Downs
