# --- !Ups

--update calculation_methods after a check of the text
Update calculation_method set description='Beste estimimerte sum er homogeniserte sum-verdier. Det betyr et datasett med høy kvalitet hvor alle fysikalske brudd og uregelmessigheter i tidsserien er korrigert slik at den representerer klimatologien mest mulig korrekt.' where method_id='best_estimate_sum' and description_locale='nb-NO';
Update calculation_method set description='Beste estimerte middelverdier er homogeniserte middelverider. Det betyr et datasett med høy kvalitet hvor alle fysikalske brudd og uregelmessigheter i tidsserien er korrigert slik at den representerer klimatologien mest mulig korrekt.' where method_id='best_estimate_mean' and description_locale='nb-NO';
Update calculation_method set description='Værsymbol er et tall som korresponderer til visualiseringen av været som et ikon. Værsymbolet er avledet av kombinasjonen av skydekke (colud_area_fraction) og værtypen (weather_type).' where method_id='weather_symbol' and description_locale='nb-NO';
Update calculation_method set description='En metode for å beskrive været siden forrige observasjon, altså det som har skjedd over tid. Metoden er oftest brukt ved observasjon av værtype.' where method_id='over_time' and description_locale='nb-NO';
Update calculation_method set description='Akkumulert verdi siden forrige observasjon, over en udefinert og varierende tidsperiode, større eller lik (gte) den oppgitte perioden. F.eks. nedbørmengder fra uregelmessige observasjonstidspunkter.' where method_id='sum_over_undefined_period' and description_locale='nb-NO';
Update calculation_method set description='Antall dager med en måleverdi større enn eller lik en terskelverdi.' where method_id='number_of_days_gte' and description_locale='nb-NO';
Update calculation_method set description='Akkumulert avvik under en terskelverdi, over tid. Man tar f.eks. temperatur-terskelverdien minus døgnmiddel-lufttemperaturer og summerer opp for de dagene lufttemperaturen ligger under terskelverdien. Enheten kalles ofte graddager.' where method_id='integral_of_deficit' and description_locale='nb-NO';
Update calculation_method set description='Akkumulert avvik over en terskelverdi, over tid. Man tar f.eks. døgnmiddel-lufttemperaturer minus temperatur-terskelverdien, og summerer opp for de dagene lufttemperaturen ligger over terskelverdien. Enheten kalles vanligvis graddager.' where method_id='integral_of_excess' and description_locale='nb-NO';
Update calculation_method set description='Endringer i verdi for elementet med hensyn til (over) tid. F.eks. for P1D gjelder endringer siden i går.' where method_id='change_over_time' and description_locale='nb-NO';
Update calculation_method set description='Vektoren "from_direction" (fra-retningen) er brukt i konstruksjonen X_from_direction og angir hvilken retning hastighetsvektoren X kommer fra.' where method_id='from_direction' and description_locale='nb-NO';
Update calculation_method set description='Prosentvis datadekning av elementet over den gitte perioden.' where method_id='percent_coverage' and description_locale='nb-NO';
Update calculation_method set description='Minimumsverdien observert eller beregnet i den gitte perioden.' where method_id='min' and description_locale='nb-NO';
Update calculation_method set description='Maksimumsverdien observert eller beregnet i den gitte perioden.' where method_id='max' and description_locale='nb-NO';
Update calculation_method set description='Standard aritmetiske gjennomsnittsverdi for den gitte perioden.' where method_id='mean' and description_locale='nb-NO';
Update calculation_method set description='Middelverdi beregnet med Køppens formel.' where method_id='mean_k' and description_locale='nb-NO';
Update calculation_method set description='Akkumulert avvik under en terskelverdi, over tid. I stedet for observasjoner, brukes punktverdier fra interpolerte geografiske grid. Man tar f.eks. temperatur-terskelverdien minus geografisk interpolert lufttemperatur, og summerer opp for de dagene den interpolerte lufttemperaturen ligger under terskelverdien. Enheten kalles vanligvis graddager.' where method_id='integral_of_deficit_interpolated' and description_locale='nb-NO';
Update calculation_method set description='Summen av verdier eller en akkumulert verdi for en periode.' where method_id='sum' and description_locale='nb-NO';
Update calculation_method set description='Dato og eller klokkeslettet som følger maksimumsverdien for det gitte element i den gitte perioden.' where method_id='time_of_event_of_max' and description_locale='nb-NO';
Update calculation_method set description='Dato og eller klokkeslettet som følger minimumsverdien for det gitte element i den gitte perioden.' where method_id='time_of_event_of_min' and description_locale='nb-NO';
Update calculation_method set description='Vektoren "from_direction" (fra-retningen) er brukt i konstruksjonen X_from_direction og angir hvilken retning hastighetsvektoren X (her middelverdien) kommer fra.' where method_id='from_direction_of_mean' and description_locale='nb-NO';
Update calculation_method set description='Vektoren "from_direction" (fra-retningen) er brukt i konstruksjonen X_from_direction og angir hvilken retning hastighetsvektoren X (her peak-verdien) kommer fra.' where method_id='from_direction_of_peak' and description_locale='nb-NO';
Update calculation_method set description='Vektoren "from_direction" (fra-retningen) er brukt i konstruksjonen X_from_direction og angir hvilken retning hastighetsvektoren X (her maksimums-verdien) kommer fra.' where method_id='from_direction_of_max' and description_locale='nb-NO';
Update calculation_method set description='Estimat av gjennomsnittleg bølgeperiode for individuelle bølger ved bruk av bølgemomenter ved m0/m1' where method_id='estimated_by_spectral_moments_1' and description_locale='nb-NO';
Update calculation_method set description='Retningsvariasjonen (standardavviket)' where method_id='directional_spread' and description_locale='nb-NO';
Update calculation_method set description='Summen av observasjonstallene vil bli et tall mellom 0 (helt klart vær ved alle observasjonene) og 24 (helt overskyet ved alle). Dersom summen er 9 (maks 24 ved helt overskyet) eller mindre og ikke høyere enn 4 ved noen enkelt observasjon, betegnes dagen som en penværsdag (=1), ellers 0.' where method_id='boolean_fair_weather' and description_locale='nb-NO';
Update calculation_method set description='Summen av observasjonstallene vil bli et tall mellom 0 (helt klart vær ved alle observasjonene) og 24 (helt overskyet ved alle). Dersom summen er 4 (maks 24 ved helt overskyet) eller mindre, betegnes dagen som en klarværsdag.' where method_id='boolean_clear_sky_weather' and description_locale='nb-NO';
Update calculation_method set description='Summen av observasjonstallene vil bli et tall mellom 0 (helt klart vær ved alle observasjonene) og 24 (helt overskyet ved alle). Dersom summen er 20 eller høyere, betegnes dagen som en overskyet dag.' where method_id='boolean_overcast_weather' and description_locale='nb-NO';

--nynorsk
Update calculation_method set description='Beste estimimerte sum er homogeniserte sumverdiar. Det vil seie eit datasett med høg kvalitet der alle fysikalske brot og uregelmessigheiter i tidsserien er korrigerte slik at han representerer klimatologien mest mogleg korrekt.' where method_id='best_estimate_sum' and description_locale='nn-NO';
Update calculation_method set description='Beste estimerte middelverdiar er homogeniserte middelverdiar. Det vil seie eit datasett med høg kvalitet der alle fysikalske brot og uregelmessigheiter i tidsserien er korrigerte slik at han representerer klimatologien mest mogleg korrekt.' where method_id='best_estimate_mean' and description_locale='nn-NO';
Update calculation_method set description='Vêrsymbol er eit tal som korresponderer til visualiseringa av vêret som eit ikon. Vêrsymbolet er leidd ut av kombinasjonen av skydekke (colud_area_fraction) og vêrtypen (weather_type).' where method_id='weather_symbol' and description_locale='nn-NO';
Update calculation_method set description='Ein metode for å skildre vêret sidan førre observasjon, altså det som har skjedd over tid. Metoden er oftast brukt ved observasjon av vêrtype.' where method_id='over_time' and description_locale='nn-NO';
Update calculation_method set description='Akkumulert verdi sidan førre observasjon, over ein udefinert og varierande tidsperiode, større eller lik (gte) den oppgitte perioden. F.eks. nedbørmengder frå uregelmessige observasjonstidspunkt.' where method_id='sum_over_undefined_period' and description_locale='nn-NO';
Update calculation_method set description='Talet på dagar med måleverdi større enn eller lik ein terskelverdi.' where method_id='number_of_days_gte' and description_locale='nn-NO';
Update calculation_method set description='Akkumulert avvik under ein terskelverdi, over tid. Ein tek f.eks. temperatur-terskelverdien minus døgnmiddel-lufttemperaturar, og summerer opp for dei dagane lufttemperaturen ligg under terskelverdien. Eininga kallas vanlegvis graddagar.' where method_id='integral_of_deficit' and description_locale='nn-NO';
Update calculation_method set description='Akkumulert avvik over ein terskelverdi, over tid. Ein tek f.eks. døgnmiddel-lufttemperaturar minus temperatur-terskelverdien, og summerer opp for dei dagane lufttemperaturen ligg over terskelverdien. Eininga kallas vanlegvis graddagar.' where method_id='integral_of_excess' and description_locale='nn-NO';
Update calculation_method set description='Endringar i verdi for elementet med omsyn til (over) tid. F.eks. gjeld P1D endringar sidan i går.' where method_id='change_over_time' and description_locale='nn-NO';
Update calculation_method set description='Vektoren "from_direction" (frå-retninga) er brukt i konstruksjonen X_from_direction og viser kva i for retning hastigheitsvektoren X kjem frå.' where method_id='from_direction' and description_locale='nn-NO';
Update calculation_method set description='Prosentvis datadekking av elementet over den gitte perioden.' where method_id='percent_coverage' and description_locale='nn-NO';
Update calculation_method set description='Minimumsverdien observert eller berekna i den gitte perioden.' where method_id='min' and description_locale='nn-NO';
Update calculation_method set description='Maksimumsverdien observert eller berekna i den gitte perioden.' where method_id='max' and description_locale='nn-NO';
Update calculation_method set description='Standard aritmetiske gjennomsnittsverdi for den gitte perioden.' where method_id='mean' and description_locale='nn-NO';
Update calculation_method set description='Middelverdi berekna med Køppens formel.' where method_id='mean_k' and description_locale='nn-NO';
Update calculation_method set description='Akkumulert avvik under ein terskelverdi, over tid. I staden for observasjonar, blir punktverdiar frå interpolerte geografiske grid brukt. Ein tek f.eks. temperatur-terskelverdien minus geografisk interpolert lufttemperatur, og summerer opp for dei dagane den interpolerte lufttemperaturen ligger under terskelverdien. Eininga kallas vanlegvis graddagar.' where method_id='integral_of_deficit_interpolated' and description_locale='nn-NO';
Update calculation_method set description='Summen av verdiar i ein periode, det vil seie den akkumlerte verdien.' where method_id='sum' and description_locale='nn-NO';
Update calculation_method set description='Datoen og eller klokkeslettet som følger maksimumsverdien for det gitte elementet i den gitte perioden.' where method_id='time_of_event_of_max' and description_locale='nn-NO';
Update calculation_method set description='Datoen og eller klokkeslettet som følger minimumsverdien for det gitte elementet i den gitte perioden.' where method_id='time_of_event_of_min' and description_locale='nn-NO';
Update calculation_method set description='Vektoren "from_direction" (frå-retninga) er brukt i konstruksjonen X_from_direction og viser i kva retning hastigheitsvektoren X (her middelverdien) kjem frå.' where method_id='from_direction_of_mean' and description_locale='nn-NO';
Update calculation_method set description='Vektoren "from_direction" (frå-retninga) er brukt i konstruksjonen X_from_direction og viser i kva retning hastigheitsvektoren X (her peak-verdien) kjem frå.' where method_id='from_direction_of_peak' and description_locale='nn-NO';
Update calculation_method set description='Vektoren "from_direction" (frå-retninga) er brukt i konstruksjonen X_from_direction og viser i kva retning hastigheitsvektoren X (her maksimums-verdien) kjem frå.' where method_id='from_direction_of_max' and description_locale='nn-NO';
Update calculation_method set description='Estimat av gjennomsnittleg bølgeperiode for individuelle bølger ved bruk av bølgemoment ved m0/m1' where method_id='estimated_by_spectral_moments_1' and description_locale='nn-NO';
Update calculation_method set description='Retningsvariasjonen (standardavviket)' where method_id='directional_spread' and description_locale='nn-NO';
Update calculation_method set description='Summen av observasjonstala vil bli eit tall mellom 0 (heilt klart vêr ved alle observasjonane) og 24 (heilt overskya ved alle). Dersom summen er 9 (maks 24 ved heilt overskya) eller mindre og ikkje høgare enn 4 ved nokon enkeltobservasjon, blir dagen rekna for å vere ein penvêrsdag (=1), eller 0.' where method_id='boolean_fair_weather' and description_locale='nn-NO';
Update calculation_method set description='Summen av observasjonstala vil bli eit tal mellom 0 (heilt klart vêr ved alle observasjonane) og 24 (heilt overskya ved alle). Dersom summen er 4 (maks 24 ved heilt overskya) eller mindre, vert dagen rekna for å vere ein klarvêrsdag.' where method_id='boolean_clear_sky_weather' and description_locale='nn-NO';
Update calculation_method set description='Summen av observasjonstala vil bli eit tal mellom 0 (heilt klart vêr ved alle observasjonane) og 24 (heilt overskya ved alle). Dersom summen er 20 eller høgare, vert dagen rekna for å vere ein overskya dag.' where method_id='boolean_overcast_weather' and description_locale='nn-NO';

--english
Update calculation_method set description='Best estimimate sum values are homogenized sum values. This means a high quality dataset of sums with no kind of breaks in the timeseries.' where method_id='best_estimate_sum' and description_locale='en-US';
Update calculation_method set description='Best estimimate mean values are homogenized mean values. This means a high quality dataset of mean values with no kind of breaks in the timeseries.' where method_id='best_estimate_mean' and description_locale='en-US';
Update calculation_method set description='Count of days with a measurement exceeding a given threshold.' where method_id='weather_symbol' and description_locale='en-US';
Update calculation_method set description='Accumulated deviation below a threshold over time. Temperature deficit is defined as the sum over days, of temperature threshold minus the daily mean air temperatures, taking only into account the temperatures below the threshold. This metric is often named after a specification and "degree-days", e.g. heating degree-days.' where method_id='over_time' and description_locale='en-US';
Update calculation_method set description='Accumulated deviation above a threshold over time. Temperature excess is defined as the sum over days, of the daily mean air temperatures minus the temperature threshold, taking only into account the temperatures above the threshold. This metric is often named after a specification and "degree-days", e.g. growing degree-days.' where method_id='sum_over_undefined_period' and description_locale='en-US';
Update calculation_method set description='The time difference of a variable. E.g. P1D is the difference between one day and the previous day.' where method_id='number_of_days_gte' and description_locale='en-US';
Update calculation_method set description='Weather symbol is a number corresponding to the visualization of the weather as an icon. Weather symbol is derived from a combination of cloud cover (colud_area_fraction) and type of weather (weather_type).' where method_id='integral_of_deficit' and description_locale='en-US';
Update calculation_method set description='A method to describe the observation of what has happened since last observation, often used for type of weather.' where method_id='integral_of_excess' and description_locale='en-US';
Update calculation_method set description='Indicates the direction of the flow. The vector "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X is coming from.' where method_id='change_over_time' and description_locale='en-US';
Update calculation_method set description='Accumulated value since last observation, over undefined time periods greater than or equal (gte) the given time period. E.g. precipitation amounts from observations at irregular intervals.' where method_id='from_direction' and description_locale='en-US';
Update calculation_method set description='A measure of completeness of the observations over a given period in percent' where method_id='percent_coverage' and description_locale='en-US';
Update calculation_method set description='Minimum value observed or calculated in the given period' where method_id='min' and description_locale='en-US';
Update calculation_method set description='Maximum value observed or calculated in the given period' where method_id='max' and description_locale='en-US';
Update calculation_method set description='Standard arithmetic mean value for the given period' where method_id='mean' and description_locale='en-US';
Update calculation_method set description='Mean value calculated with the Køppen formula.' where method_id='mean_k' and description_locale='en-US';
Update calculation_method set description='Accumulated deviation below a threshold over time. Interpolated temperature deficit is defined as the temperature threshold minus geographically interpolated air temperatures, taking only into account the temperatures below the threshold. This metric is often named after a specification and "degree-days", e.g. heating degree-days"' where method_id='integral_of_deficit_interpolated' and description_locale='en-US';
Update calculation_method set description='The arithmetic sum of data values or accumulated value in a given period.' where method_id='sum' and description_locale='en-US';
Update calculation_method set description='The time or date for the maximum value of the given element in the given period.' where method_id='time_of_event_of_max' and description_locale='en-US';
Update calculation_method set description='The time or date for the minimum value of the given element in the given period.' where method_id='time_of_event_of_min' and description_locale='en-US';
Update calculation_method set description='Indicates the direction of the flow. The vector "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X (here the mean value) is coming.' where method_id='from_direction_of_mean' and description_locale='en-US';
Update calculation_method set description='Indicates the direction of the flow. The vector "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X (here the peak value) is coming.' where method_id='from_direction_of_peak' and description_locale='en-US';
Update calculation_method set description='Indicates the direction of the flow. The vector "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X (here the max value) is coming.' where method_id='from_direction_of_max' and description_locale='en-US';
Update calculation_method set description='Estimate of the average period of individual waves using moments using m0/m1' where method_id='estimated_by_spectral_moments_1' and description_locale='en-US';
Update calculation_method set description='Directional spread (standard deviation).' where method_id='directional_spread' and description_locale='en-US';
Update calculation_method set description='The sum of the cloud cover observations at 06 and 12 UTC where no single values above 4, (and at 18 utc is 9 or lower?). The sum should be below 9 (max 24 if all overcast), then it is fair weather and boolean is true, that means 1, else 0 (false).' where method_id='boolean_fair_weather' and description_locale='en-US';
Update calculation_method set description='The sum of the cloud cover observations at 06, 12 and 18 UTC. The sum should be below 4 (max 24 if all overcast), then it is clear sky weather and boolean is true, that means 1, else 0 (false).' where method_id='boolean_clear_sky_weather' and description_locale='en-US';
Update calculation_method set description='The sum of the cloud cover observations at 06, 12 and 18 UTC. The sum should be 20 or more (max 24 if all overcast), then it is overcast weather and boolean is true, that means 1, else 0 (false).' where method_id='boolean_overcast_weather' and description_locale='en-US';

--new method:
Insert into calculation_method (METHOD_ID, DESCRIPTION, METHOD_UNIT, DESCRIPTION_LOCALE) Values   
('accumulated', 'Accumulated from 0, which means the sum during a nunknown period.', NULL, 'en-US');
 
Insert into calculation_method (METHOD_ID, DESCRIPTION, METHOD_UNIT, DESCRIPTION_LOCALE) Values   
('accumulated', 'Akkumulert opp fra 0, det vil si en oppsummert verdi over en ukjent tidsperiode.', NULL, 'nb-NO');
 
Insert into calculation_method (METHOD_ID, DESCRIPTION, METHOD_UNIT, DESCRIPTION_LOCALE) Values   
('accumulated', 'Akkumulert frå 0, det vil si ein oppsummert verdi over ei ukjend tidsperiode.', NULL, 'nn-NO');

# --- !Downs
