# --- !Ups

CREATE TABLE timeoffset(id text NOT NULL);

INSERT INTO timeoffset (id) VALUES ('PT20M');
INSERT INTO timeoffset (id) VALUES ('PT00H');
INSERT INTO timeoffset (id) VALUES ('PT18H');
INSERT INTO timeoffset (id) VALUES ('PT12H');
INSERT INTO timeoffset (id) VALUES ('PT06H');


CREATE TABLE element_timeoffset (element_id text, values text[]);

INSERT INTO element_timeoffset VALUES('air_temperature','{''PT00H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('air_temperature_vertical_difference','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_mean(air_temperature P1D)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_mean(air_temperature P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_mean(air_temperature P1Y)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_mean(air_temperature P3M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_mean(air_temperature_anomaly P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_mean(air_temperature_anomaly P1Y)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_mean(air_temperature_anomaly P3M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_sum(precipitation_amount P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_sum(precipitation_amount P1Y)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_sum(precipitation_amount P3M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_sum(precipitation_amount_anomaly P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_sum(precipitation_amount_anomaly P1Y)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('best_estimate_sum(precipitation_amount_anomaly P3M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('boolean_clear_sky_weather(cloud_area_fraction P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('boolean_fair_weather(cloud_area_fraction P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('boolean_overcast_weather(cloud_area_fraction P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('cloud_area_fraction1','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_area_fraction2','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_area_fraction3','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_area_fraction4','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_base_height1','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_base_height2','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_base_height3','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_base_height4','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_type_icao1','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_type_icao2','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('cloud_type_icao3','{''PT20M''}');
INSERT INTO element_timeoffset VALUES('dew_point_temperature','{''PT00H'',''PT06H''}');
INSERT INTO element_timeoffset VALUES('integral_of_deficit(mean(air_temperature P1D) P1M 17.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('integral_of_deficit(mean(air_temperature P1D) P1Y 17.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('integral_of_deficit(mean(air_temperature P1D) P3M 17.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('integral_of_deficit(mean(air_temperature P1D) P6M 17.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('integral_of_deficit(mean(air_temperature PT1H) P1D 17.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('integral_of_excess(mean(air_temperature P1D) P1M 0.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('integral_of_excess(mean(air_temperature P1D) P1M 5.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('integral_of_excess(mean(air_temperature PT1H) P1D 0.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('integral_of_excess(mean(air_temperature PT1H) P1D 5.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(air_pressure_at_sea_level P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(air_pressure_at_sea_level P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(air_temperature P1D)','{''PT00H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('max(air_temperature P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('max(air_temperature P1Y)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('max(air_temperature P3M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('max(air_temperature P6M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('max(air_temperature PT10M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('max(air_temperature PT12H)','{''PT00H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('max(air_temperature PT1H)','{''PT00H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('max(cloud_area_fraction P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(cloud_area_fraction P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(max(wind_speed P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(max(wind_speed PT1H) P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(relative_humidity P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(relative_humidity P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(relative_humidity PT1H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(sea_state P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(sea_state P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(sea_surface_wave_period_from_instrument P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(sea_surface_wave_period_from_instrument P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(sea_surface_wave_significant_height_from_instrument P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(sea_surface_wave_significant_height_from_instrument P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(sum(duration_of_sunshine P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(sum(precipitation_amount P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(surface_air_pressure P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(surface_air_pressure P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(surface_air_pressure PT1H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(visibility_in_air_poorest_direction P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(visibility_in_air_poorest_direction P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(wind_speed P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(wind_speed P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(wind_speed_of_gust P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('max(wind_speed_of_gust P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(air_pressure_at_sea_level P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(air_pressure_at_sea_level P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(air_pressure_at_sea_level P1Y)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature P1D)','{''PT06H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature P1M)','{''PT06H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature P1Y)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature P3M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature P6M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature PT1H)','{''PT00H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature_anomaly P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature_anomaly P1Y)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature_anomaly P3M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(air_temperature_anomaly P6M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(cloud_area_fraction P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(cloud_area_fraction P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(cloud_area_fraction P1Y)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(cloud_area_fraction P3M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(cloud_area_fraction P6M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(dew_point_temperature P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(dew_point_temperature P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(max(air_temperature P1D) P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(max(air_temperature P1D) P1Y)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(max(wind_speed P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(max(wind_speed PT1H) P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(min(air_temperature P1D) P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(min(air_temperature P1D) P1Y)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean(relative_humidity P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(relative_humidity P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(relative_humidity PT1H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(sea_surface_wave_period_from_instrument P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(sea_surface_wave_period_from_instrument P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(sea_surface_wave_significant_height_from_instrument P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(sea_surface_wave_significant_height_from_instrument P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(surface_air_pressure P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(surface_air_pressure P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(surface_air_pressure P1Y)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(surface_air_pressure PT1H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(wind_speed P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(wind_speed P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(wind_speed_of_gust P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean(wind_speed_of_gust P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('mean_k(air_temperature P1D)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('mean_k(air_temperature P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('min(air_pressure_at_sea_level P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(air_pressure_at_sea_level P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(air_temperature P1D)','{''PT00H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('min(air_temperature P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('min(air_temperature P1Y)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('min(air_temperature P3M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('min(air_temperature P6M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('min(air_temperature PT10M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('min(air_temperature PT12H)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('min(air_temperature PT1H)','{''PT00H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('min(cloud_area_fraction P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(cloud_area_fraction P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(max(wind_speed P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(max(wind_speed PT1H) P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(relative_humidity P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(relative_humidity P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(relative_humidity PT1H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(sea_state P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(sea_state P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(sea_surface_wave_period_from_instrument P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(sea_surface_wave_period_from_instrument P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(sea_surface_wave_significant_height_from_instrument P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(sea_surface_wave_significant_height_from_instrument P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(sum(duration_of_sunshine P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(surface_air_pressure P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(surface_air_pressure P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(surface_air_pressure PT1H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(visibility_in_air_poorest_direction P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(visibility_in_air_poorest_direction P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(wind_speed P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(wind_speed P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(wind_speed_of_gust P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('min(wind_speed_of_gust P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('number_of_days_gte(sum(precipitation_amount P1D) P1M 1.0)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('over_time(change_in_surface_snow_thickness P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('over_time(precipitation_type_primary_significance P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('over_time(sum(time_of_maximum_precipitation_amount P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('over_time(thickness_of_snowfall_amount P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('over_time(time_of_maximum_air_temperature P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('over_time(time_of_minimum_air_temperature P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('precipitation_amount','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sea_surface_temperature','{''PT00H'',''PT06H''}');
INSERT INTO element_timeoffset VALUES('snow_coverage_type','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('specific_humidity','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('state_of_ground','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(duration_of_sunshine P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(duration_of_sunshine P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(duration_of_sunshine P1Y)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(duration_of_sunshine PT1H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount P1D)','{''PT06H'',''PT18H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount P1M)','{''PT18H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount P1Y)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount P30D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount P3M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount P6M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount PT12H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount PT1H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount PT3H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount PT6H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount_anomaly P1M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount_anomaly P1Y)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount_anomaly P3M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum(precipitation_amount_anomaly P6M)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum_over_undefined_period(precipitation_amount P1D)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('sum_over_undefined_period(precipitation_amount PT1H)','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('surface_snow_thickness','{''PT06H''}');
INSERT INTO element_timeoffset VALUES('wind_from_direction','{''PT00H'',''PT06H'', ''PT12H'', ''PT18H''}');

# --- !Downs
