# --- !Ups

UPDATE element_timeoffset SET values='{PT00H,PT18H}' WHERE element_id='air_temperature';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='air_temperature_vertical_difference';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='best_estimate_mean(air_temperature_anomaly P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='best_estimate_mean(air_temperature_anomaly P1Y)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='best_estimate_mean(air_temperature_anomaly P3M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='best_estimate_mean(air_temperature P1D)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='best_estimate_mean(air_temperature P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='best_estimate_mean(air_temperature P1Y)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='best_estimate_mean(air_temperature P3M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='best_estimate_sum(precipitation_amount_anomaly P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='best_estimate_sum(precipitation_amount_anomaly P1Y)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='best_estimate_sum(precipitation_amount_anomaly P3M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='best_estimate_sum(precipitation_amount P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='best_estimate_sum(precipitation_amount P1Y)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='best_estimate_sum(precipitation_amount P3M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='boolean_clear_sky_weather(cloud_area_fraction P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='boolean_fair_weather(cloud_area_fraction P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='boolean_overcast_weather(cloud_area_fraction P1D)';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_area_fraction1';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_area_fraction2';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_area_fraction3';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_area_fraction4';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_base_height1';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_base_height2';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_base_height3';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_base_height4';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_type_icao1';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_type_icao2';
UPDATE element_timeoffset SET values='{PT20M}' WHERE element_id='cloud_type_icao3';
UPDATE element_timeoffset SET values='{PT00H,PT06H}' WHERE element_id='dew_point_temperature';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='integral_of_deficit(mean(air_temperature P1D) P1M 17.0)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='integral_of_deficit(mean(air_temperature P1D) P1Y 17.0)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='integral_of_deficit(mean(air_temperature P1D) P3M 17.0)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='integral_of_deficit(mean(air_temperature P1D) P6M 17.0)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='integral_of_deficit(mean(air_temperature PT1H) P1D 17.0)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='integral_of_excess(mean(air_temperature P1D) P1M 0.0)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='integral_of_excess(mean(air_temperature P1D) P1M 5.0)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(air_pressure_at_sea_level P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(air_pressure_at_sea_level P1M)';
UPDATE element_timeoffset SET values='{PT00H,PT18H}' WHERE element_id='max(air_temperature P1D)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='max(air_temperature P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='max(air_temperature P1Y)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='max(air_temperature P3M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='max(air_temperature P6M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='max(air_temperature PT10M)';
UPDATE element_timeoffset SET values='{PT00H,PT18H}' WHERE element_id='max(air_temperature PT12H)';
UPDATE element_timeoffset SET values='{PT00H,PT18H}' WHERE element_id='max(air_temperature PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(cloud_area_fraction P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(cloud_area_fraction P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(max(wind_speed P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(max(wind_speed PT1H) P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(relative_humidity P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(relative_humidity P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(relative_humidity PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(sea_state P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(sea_state P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(sea_surface_wave_period_from_instrument P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(sea_surface_wave_period_from_instrument P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(sea_surface_wave_significant_height_from_instrument P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(sea_surface_wave_significant_height_from_instrument P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(sum(duration_of_sunshine P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(sum(precipitation_amount P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(surface_air_pressure P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(surface_air_pressure P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(surface_air_pressure PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(visibility_in_air_poorest_direction P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(visibility_in_air_poorest_direction P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(wind_speed_of_gust P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(wind_speed_of_gust P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(wind_speed P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='max(wind_speed P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(air_pressure_at_sea_level P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(air_pressure_at_sea_level P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(air_pressure_at_sea_level P1Y)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(air_temperature_anomaly P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(air_temperature_anomaly P1Y)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(air_temperature_anomaly P3M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(air_temperature_anomaly P6M)';
UPDATE element_timeoffset SET values='{PT06H,PT18H}' WHERE element_id='mean(air_temperature P1D)';
UPDATE element_timeoffset SET values='{PT06H,PT18H}' WHERE element_id='mean(air_temperature P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(air_temperature P1Y)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(air_temperature P3M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(air_temperature P6M)';
UPDATE element_timeoffset SET values='{PT00H,PT18H}' WHERE element_id='mean(air_temperature PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(cloud_area_fraction P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(cloud_area_fraction P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(cloud_area_fraction P1Y)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(cloud_area_fraction P3M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(cloud_area_fraction P6M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(dew_point_temperature P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(dew_point_temperature P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean_k(air_temperature P1D)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean_k(air_temperature P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(max(air_temperature P1D) P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(max(air_temperature P1D) P1Y)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(max(wind_speed P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(max(wind_speed PT1H) P1D)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(min(air_temperature P1D) P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='mean(min(air_temperature P1D) P1Y)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(relative_humidity P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(relative_humidity P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(relative_humidity PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(sea_surface_wave_period_from_instrument P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(sea_surface_wave_period_from_instrument P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(sea_surface_wave_significant_height_from_instrument P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(sea_surface_wave_significant_height_from_instrument P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(surface_air_pressure P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(surface_air_pressure P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(surface_air_pressure P1Y)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(surface_air_pressure PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(wind_speed_of_gust P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(wind_speed_of_gust P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(wind_speed P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='mean(wind_speed P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(air_pressure_at_sea_level P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(air_pressure_at_sea_level P1M)';
UPDATE element_timeoffset SET values='{PT00H,PT18H}' WHERE element_id='min(air_temperature P1D)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='min(air_temperature P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='min(air_temperature P1Y)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='min(air_temperature P3M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='min(air_temperature P6M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='min(air_temperature PT10M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='min(air_temperature PT12H)';
UPDATE element_timeoffset SET values='{PT00H,PT18H}' WHERE element_id='min(air_temperature PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(cloud_area_fraction P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(cloud_area_fraction P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(max(wind_speed P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(max(wind_speed PT1H) P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(relative_humidity P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(relative_humidity P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(relative_humidity PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(sea_state P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(sea_state P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(sea_surface_wave_period_from_instrument P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(sea_surface_wave_period_from_instrument P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(sea_surface_wave_significant_height_from_instrument P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(sea_surface_wave_significant_height_from_instrument P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(sum(duration_of_sunshine P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(surface_air_pressure P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(surface_air_pressure P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(surface_air_pressure PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(visibility_in_air_poorest_direction P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(visibility_in_air_poorest_direction P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(wind_speed_of_gust P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(wind_speed_of_gust P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(wind_speed P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='min(wind_speed P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='number_of_days_gte(sum(precipitation_amount P1D) P1M 1.0)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='over_time(change_in_surface_snow_thickness P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='over_time(precipitation_type_primary_significance P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='over_time(sum(time_of_maximum_precipitation_amount P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='over_time(thickness_of_snowfall_amount P1D)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='over_time(time_of_maximum_air_temperature P1M)';
UPDATE element_timeoffset SET values='{PT18H}' WHERE element_id='over_time(time_of_minimum_air_temperature P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='precipitation_amount';
UPDATE element_timeoffset SET values='{PT00H,PT06H}' WHERE element_id='sea_surface_temperature';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='snow_coverage_type';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='specific_humidity';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='state_of_ground';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(boolean_clear_sky_weather(cloud_area_fraction P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(boolean_fair_weather(cloud_area_fraction P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(boolean_overcast_weather(cloud_area_fraction P1D) P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(duration_of_sunshine P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(duration_of_sunshine P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(duration_of_sunshine P1Y)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(duration_of_sunshine PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum_over_undefined_period(precipitation_amount P1D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum_over_undefined_period(precipitation_amount PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount_anomaly P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount_anomaly P1Y)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount_anomaly P3M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount_anomaly P6M)';
UPDATE element_timeoffset SET values='{PT06H,PT18H}' WHERE element_id='sum(precipitation_amount P1D)';
UPDATE element_timeoffset SET values='{PT06H,PT18H}' WHERE element_id='sum(precipitation_amount P1M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount P1Y)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount P30D)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount P3M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount P6M)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount PT12H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount PT1H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount PT3H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='sum(precipitation_amount PT6H)';
UPDATE element_timeoffset SET values='{PT06H}' WHERE element_id='surface_snow_thickness';
UPDATE element_timeoffset SET values='{PT00H,PT06H,PT12H,PT18H}' WHERE element_id='wind_from_direction';


# --- !Downs
