# --- !Ups

Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('air_pressure_at_sea_level','air_pressure_at_sea_level',null,'Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('air_temperature','air_temperature',null,'K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('beaufort_wind_force','beaufort_wind_force',null,'1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('best_estimate_mean(air_temperature 1M)','air_temperature','best_estimate_mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('best_estimate_mean(air_temperature T24H)','air_temperature','best_estimate_mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('best_estimate_mean(air_temperature_anomaly 1M)','air_temperature_anomaly','best_estimate_mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('best_estimate_sum(precipitation_amount 1M)','precipitation_amount','best_estimate_sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('boolean_clear_sky_weather(cloud_area_fraction T24H)','cloud_area_fraction','boolean_clear_sky_weather','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('boolean_fair_weather(cloud_area_fraction T24H)','cloud_area_fraction','boolean_fair_weather','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('boolean_overcast_weather(cloud_area_fraction T24H)','cloud_area_fraction','boolean_overcast_weather','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('change_over_time(surface_air_pressure T1H)','surface_air_pressure',null,'Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('change_over_time(surface_air_pressure T3H)','surface_air_pressure',null,'Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('change_over_time(surface_air_pressure T6H)','surface_air_pressure',null,'Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('change_over_time(surface_snow_amount T24H)','surface_snow_amount','change_over_time','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('change_over_time(surface_snow_thickness T24H)','surface_snow_thickness','change_over_time','m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('cloud_area_fraction','cloud_area_fraction',null,'1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('dew_point_temperature','dew_point_temperature',null,'K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('diffuse_downwelling_shortwave_flux_in_air','diffuse_downwelling_shortwave_flux_in_air',null,'W m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)','sea_surface_wave_zero_upcrossing_period','estimated_by_spectral_moments_1','s',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('from_direction_of_max(wind_speed T1H)','wind_speed','from_direction_of_max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('from_direction_of_max(wind_speed T20M)','wind_speed','from_direction_of_max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('from_direction_of_max(wind_speed T3H)','wind_speed','from_direction_of_max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('from_direction_of_max(wind_speed_of_gust T10M)','wind_speed_of_gust','from_direction_of_max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('from_direction_of_max(wind_speed_of_gust T1H)','wind_speed_of_gust','from_direction_of_max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('integral_of_deficit(mean(air_temperature T1H) T24H 0.0)','air_temperature','integral_of_deficit','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('integral_of_deficit(mean(air_temperature T1H) T24H 5.0)','air_temperature','integral_of_deficit','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('integral_of_deficit(mean(air_temperature T24H) 1M 0.0)','air_temperature','integral_of_deficit','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('integral_of_deficit(mean(air_temperature T24H) 1M 5.0)','air_temperature','integral_of_deficit','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('integral_of_excess(mean(air_temperature T1H) T24H 17.0)','air_temperature','integral_of_excess','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('integral_of_excess(mean(air_temperature T24H) 1M 17.0)','air_temperature','integral_of_excess','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)','air_temperature','integral_of_excess_interpolated','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('latitude','latitude',null,'degree_north',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('liquid_water_content_of_surface_snow','liquid_water_content_of_surface_snow',null,'kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('longitude','longitude',null,'degree_east',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('low_type_cloud_area_fraction','low_type_cloud_area_fraction',null,'1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(air_pressure_at_sea_level 1M)','air_pressure_at_sea_level','max','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(air_pressure_at_sea_level T24H)','air_pressure_at_sea_level','max','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(air_temperature 1M)','air_temperature','max','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(air_temperature T10M)','air_temperature','max','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(air_temperature T12H)','air_temperature','max','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(air_temperature T1H)','air_temperature','max','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(air_temperature T24H)','air_temperature','max','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(beaufort_wind_force T6H)','beaufort_wind_force','max','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(cloud_area_fraction 1M)','cloud_area_fraction','max','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(cloud_area_fraction T24H)','cloud_area_fraction','max','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(max(wind_speed T1H) T24H)','wind_speed','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(max(wind_speed T24H) 1M)','wind_speed','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(relative_humidity 1M)','relative_humidity','max','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(relative_humidity T24H)','relative_humidity','max','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(relative_humidity T24H)','relative_humidity','mean','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(sea_surface_temperature 1M)','sea_surface_temperature','max','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(sea_surface_temperature T1H)','sea_surface_temperature','max','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(sum(duration_of_sunshine T24H) 1M)','duration_of_sunshine','max','s',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(sum(precipitation_amount T24H) 1M)','precipitation_amount','max','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(surface_air_pressure 1M)','surface_air_pressure','max','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(surface_air_pressure T1H)','surface_air_pressure','max','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(surface_air_pressure T24H)','surface_air_pressure','max','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(surface_snow_thickness 1M)','surface_snow_thickness','max','m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(surface_snow_thickness T1H)','surface_snow_thickness','max','m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(surface_temperature T1H)','surface_temperature','max','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed 1M)','wind_speed','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed T10M)','wind_speed','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed T1H)','wind_speed','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed T20M)','wind_speed','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed T24H)','wind_speed','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed T3H)','wind_speed','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed T6H)','wind_speed','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed_of_gust 1M)','wind_speed_of_gust','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed_of_gust T10M)','wind_speed_of_gust','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed_of_gust T1H)','wind_speed_of_gust','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed_of_gust T20M)','wind_speed_of_gust','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('max(wind_speed_of_gust T24H)','wind_speed_of_gust','max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(air_pressure_at_sea_level 1M)','air_pressure_at_sea_level','mean','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(air_pressure_at_sea_level T24H)','air_pressure_at_sea_level','mean','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(air_temperature 1M)','air_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(air_temperature T1H)','air_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(air_temperature T24H)','air_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(air_temperature_anomaly 1M)','air_temperature_anomaly','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(cloud_area_fraction 1M)','cloud_area_fraction','mean','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(cloud_area_fraction T24H)','cloud_area_fraction','mean','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(dew_point_temperature 1M)','dew_point_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(dew_point_temperature T24H)','dew_point_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(max(air_temperature T24H) 1M)','air_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(max(wind_speed T1H) T24H)','wind_speed','mean','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(max(wind_speed T24H) 1M)','wind_speed','mean','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(min(air_temperature T24H) 1M)','air_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(relative_humidity 1M)','relative_humidity','mean','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(relative_humidity T1H)','relative_humidity','mean','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(relative_humidity T24H)','relative_humidity','mean','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(sea_surface_temperature 1M)','sea_surface_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(sea_surface_temperature T1H)','sea_surface_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(soil_temperature T1H)','soil_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(specific_humidity 1M)','specific_humidity','mean','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(surface_air_pressure 1M)','surface_air_pressure','mean','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(surface_air_pressure T1H)','surface_air_pressure','mean','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(surface_air_pressure T24H)','surface_air_pressure','mean','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(surface_snow_thickness 1M)','surface_snow_thickness','mean','m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(surface_snow_thickness T1H)','surface_snow_thickness','mean','m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(surface_temperature T1H)','surface_temperature','mean','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(wind_from_direction T1H)','wind_from_direction','mean','degree',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(wind_speed 1M)','wind_speed','mean','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(wind_speed T1H)','wind_speed','mean','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(wind_speed T24H)','wind_speed','mean','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(wind_speed_of_gust 1M)','wind_speed_of_gust','mean','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean(wind_speed_of_gust T24H)','wind_speed_of_gust','mean','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean_k(air_temperature 1M)','air_temperature','mean_k','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('mean_k(air_temperature T24H)','air_temperature','mean_k','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(air_pressure_at_sea_level 1M)','air_pressure_at_sea_level','min','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(air_pressure_at_sea_level T24H)','air_pressure_at_sea_level','min','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(air_temperature 1M)','air_temperature','min','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(air_temperature T10M)','air_temperature','min','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(air_temperature T12H)','air_temperature','min','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(air_temperature T1H)','air_temperature','min','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(air_temperature T24H)','air_temperature','min','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(cloud_area_fraction 1M)','cloud_area_fraction','min','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(cloud_area_fraction T24H)','cloud_area_fraction','min','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(max(wind_speed T1H) T24H)','wind_speed','min','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(max(wind_speed T24H) 1M)','wind_speed','min','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(relative_humidity 1M)','relative_humidity','min','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(relative_humidity T24H)','relative_humidity','mean','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(relative_humidity T24H)','relative_humidity','min','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(sea_surface_temperature 1M)','sea_surface_temperature','min','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(sea_surface_temperature T1H)','sea_surface_temperature','min','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(sum(duration_of_sunshine T24H) 1M)','duration_of_sunshine','min','s',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(surface_air_pressure 1M)','surface_air_pressure','min','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(surface_air_pressure T1H)','surface_air_pressure','min','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(surface_air_pressure T24H)','surface_air_pressure','min','Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(surface_snow_thickness 1M)','surface_snow_thickness','min','m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(surface_snow_thickness T1H)','surface_snow_thickness','min','m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(surface_temperature T1H)','surface_temperature','min','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(wind_speed 1M)','wind_speed','min','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(wind_speed T24H)','wind_speed','min','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(wind_speed_of_gust 1M)','wind_speed_of_gust','min','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('min(wind_speed_of_gust T24H)','wind_speed_of_gust','min','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)','precipitation_amount','number_of_days_gte','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('precipitation_amount','precipitation_amount',null,'kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('relative_humidity','relative_humidity',null,'1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sea_surface_swell_wave_significant_height','sea_surface_swell_wave_significant_height',null,'m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sea_surface_temperature','sea_surface_temperature',null,'K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sea_surface_wave_period_at_variance_spectral_density_maximum','sea_surface_wave_period_at_variance_spectral_density_maximum',null,'s',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sea_surface_wave_significant_height','sea_surface_wave_significant_height',null,'m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sea_surface_wave_zero_upcrossing_period','sea_surface_wave_zero_upcrossing_period',null,'s',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sea_water_speed','sea_water_speed',null,'m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('soil_temperature','soil_temperature',null,'K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('specific_humidity','specific_humidity',null,'1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)','cloud_area_fraction','sum','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)','cloud_area_fraction','sum','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)','cloud_area_fraction','sum','1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(duration_of_sunshine 1M)','duration_of_sunshine','sum','s',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(duration_of_sunshine T1H)','duration_of_sunshine','sum','s',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(duration_of_sunshine T24H)','duration_of_sunshine','sum','s',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(precipitation_amount 1M)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(precipitation_amount T10M)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(precipitation_amount T12H)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(precipitation_amount T1H)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(precipitation_amount T1M)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(precipitation_amount T24H)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(precipitation_amount T3H)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(precipitation_amount T6H)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(precipitation_amount T720H)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(water_evaporation_amount T1H)','water_evaporation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum(water_evaporation_amount T24H)','water_evaporation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum_over_undefined_period(precipitation_amount 1M)','precipitation_amount','sum','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum_over_undefined_period(precipitation_amount T1H)','precipitation_amount','sum_over_undefined_period','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('sum_over_undefined_period(precipitation_amount T24H)','precipitation_amount','sum_over_undefined_period','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_air_pressure','surface_air_pressure',null,'Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_albedo','surface_albedo',null,'1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_downwelling_longwave_flux_in_air','surface_downwelling_longwave_flux_in_air',null,'W m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_downwelling_photosynthetic_radiative_flux_in_air','surface_downwelling_photosynthetic_radiative_flux_in_air',null,'W m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_downwelling_shortwave_flux_in_air','surface_downwelling_shortwave_flux_in_air',null,'W m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_net_downward_radiative_flux','surface_net_downward_radiative_flux',null,'W m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_snow_thickness','surface_snow_thickness',null,'m',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_temperature','surface_temperature',null,'K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_upwelling_longwave_flux_in_air','surface_upwelling_longwave_flux_in_air',null,'W m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('surface_upwelling_shortwave_flux_in_air','surface_upwelling_shortwave_flux_in_air',null,'W m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('temperature_in_surface_snow','temperature_in_surface_snow',null,'K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('time_of_event_of_max(air_temperature 1M)','air_temperature','time_of_event_of_max','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('time_of_event_of_max(max(wind_speed T24H) 1M)','wind_speed','time_of_event_of_max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('time_of_event_of_max(sum(precipitation_amount T24H) 1M)','precipitation_amount','time_of_event_of_max','kg m-2',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('time_of_event_of_max(wind_speed T1H)','wind_speed','time_of_event_of_max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('time_of_event_of_max(wind_speed_of_gust T1H)','wind_speed_of_gust','time_of_event_of_max','m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('time_of_event_of_min(air_temperature 1M)','air_temperature','time_of_event_of_min','K',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('water_vapor_partial_pressure_in_air','water_vapor_partial_pressure_in_air',null,'Pa',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('wind_from_direction','wind_from_direction',null,'degree',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('wind_speed','wind_speed',null,'m s-1',28);
Insert into CF_ELEMENT (ELEMENT_ID,STANDARD_NAME,CELL_METHOD,UNIT,STATUS) values ('wind_speed_of_gust','wind_speed_of_gust',null,'m s-1',28);


# --- !Downs

DELETE FROM CF_ELEMENT;