# --- !Ups

Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PR','Air pressure','hPa','air_pressure_at_sea_level');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1PR','Air pressure','hPa','air_pressure_at_sea_level');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TA','Temperature','degC','air_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TA10','Temperature','degC','air_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TA25','Temperature','degC','air_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TA','Temperature','degC','air_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2TA','Temperature','degC','air_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X3TA','Temperature','degC','air_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X4TA','Temperature','degC','air_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X5TA','Temperature','degC','air_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X6TA','Temperature','degC','air_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FFB','Wind','Beaufort','beaufort_wind_force');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAM','Temperature','degC','best_estimate_mean(air_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAM','Temperature','degC','best_estimate_mean(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAMA','Temperature','degC','best_estimate_mean(air_temperature_anomaly 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR','Precipitation','mm','best_estimate_sum(precipitation_amount 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RRA','Precipitation','percent','best_estimate_sum(precipitation_amount_anomaly 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NN04','Clouds','sum','boolean_clear_sky_weather(cloud_area_fraction T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NN09','Clouds','sum','boolean_fair_weather(cloud_area_fraction T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NN20','Clouds','sum','boolean_overcast_weather(cloud_area_fraction T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PP','Air pressure','hPa','change_over_time(surface_air_pressure T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PP','Air pressure','hPa','change_over_time(surface_air_pressure T3H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PP','Air pressure','hPa','change_over_time(surface_air_pressure T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SAE','Snow','cm','change_over_time(surface_snow_amount T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SS_24','Snow','cm','change_over_time(surface_snow_thickness T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NN','Clouds','octas','cloud_area_fraction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NS1','Clouds','code','cloud_area_fraction1');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NS2','Clouds','code','cloud_area_fraction2');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NS3','Clouds','code','cloud_area_fraction3');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NS4','Clouds','code','cloud_area_fraction4');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HL','Clouds','meters','cloud_base_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HS1','Clouds','meters','cloud_base_height1');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HS2','Clouds','meter','cloud_base_height2');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HS3','Clouds','meters','cloud_base_height3');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HS4','Clouds','meters','cloud_base_height4');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TD','Temperature','degC','dew_point_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TD','Temperature','degC','dew_point_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QD','Radiation','W/m2','diffuse_downwelling_shortwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SPRTP','Waves','degrees','directional_spread(sea_surface_peak_period T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1SPRT','N/A','N/A','directional_spread(sea_surface_wave_total_energy T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SPRT','Waves','degrees','directional_spread(sea_surface_wave_total_energy T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WTM01','Waves','seconds','estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WTM01','Waves','seconds','estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WTM01','Waves','seconds','estimated_by_spectral_moments_1(sea_surface_wave_zero_upcrossing_period T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DW1','Waves','degrees','from_direction(sea_surface_swell_wave_first_mean_height T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DW1','Waves','degrees','from_direction(sea_surface_swell_wave_first_mean_height T3H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DW2','Waves','degrees','from_direction(sea_surface_swell_wave_second_mean_height T3H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1DX','N/A','N/A','from_direction_of_max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1DX_1','N/A','N/A','from_direction_of_max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DX','Wind','degrees','from_direction_of_max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DX2_1','Wind','degrees','from_direction_of_max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DX_1','Wind','degrees','from_direction_of_max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DX','Wind','degrees','from_direction_of_max(wind_speed T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DX_3','Wind','degrees','from_direction_of_max(wind_speed T3H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DG_010','Wind','degrees','from_direction_of_max(wind_speed_of_gust T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1DG_010','Wind','degrees','from_direction_of_max(wind_speed_of_gust T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DG2_1','Wind','degrees','from_direction_of_max(wind_speed_of_gust T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DG_1','Wind','degrees','from_direction_of_max(wind_speed_of_gust T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WDM1','Waves','degrees','from_direction_of_mean(sea_surface_primary_wave T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WDM1','Waves','degrees','from_direction_of_mean(sea_surface_primary_wave T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DM1','Waves','degrees','from_direction_of_mean(sea_surface_primary_wave T20M) ');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WDM2','N/A','N/A','from_direction_of_mean(sea_surface_secondary_wave T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WDM2','Waves','degrees','from_direction_of_mean(sea_surface_secondary_wave T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WDMT','Waves','degrees','from_direction_of_mean(sea_surface_wave_total_energy T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WDMT','Waves','degrees','from_direction_of_mean(sea_surface_wave_total_energy T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1DMT','N/A','N/A','from_direction_of_mean(sea_surface_wave_total_energy T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DMT','Waves','degrees','from_direction_of_mean(sea_surface_wave_total_energy T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DP1','Waves','degrees','from_direction_of_peak(sea_surface_primary_wave T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WDP1','Waves','degrees','from_direction_of_peak(sea_surface_primary_wave)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WDP1','Waves','degrees','from_direction_of_peak(sea_surface_primary_wave)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WDP2','Waves','degrees','from_direction_of_peak(sea_surface_secondary_wave T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WDP2','Waves','degrees','from_direction_of_peak(sea_surface_secondary_wave T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WDPT','Waves','degrees','from_direction_of_peak(sea_surface_wave_total_energy T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WDPT','Waves','degrees','from_direction_of_peak(sea_surface_wave_total_energy T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TG','Temperature','degC','grass_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CH','Clouds','code','high_type_cloud');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WAWA','N/A','N/A','instant_weather_type_from_instrument');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WAWA','Weather','code','instant_weather_type_from_instrument');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VSUM','Temperature','degree-day','integral_of_deficit(mean(air_temperature T1H) T24H 0.0)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VEKST','Temperature','degree-day','integral_of_deficit(mean(air_temperature T1H) T24H 5.0)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VSUM','Temperature','degree-day','integral_of_deficit(mean(air_temperature T24H) 1M 0.0)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VEKST','Temperature','degree-day','integral_of_deficit(mean(air_temperature T24H) 1M 5.0)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('GD17','Temperature','degree-day','integral_of_excess(mean(air_temperature T1H) T24H 17.0)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('GD17','Temperature','degree-day','integral_of_excess(mean(air_temperature T24H) 1M 17.0)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('GD17_I','Temperature','degree-day','integral_of_excess_interpolated(mean(air_temperature T24H) 1M 17.0)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('MLAT','Metadata','degrees','latitude');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RW','Snow','mm','liquid_water_content_of_surface_snow');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('MLON','Metadata','degrees','longitude');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CL','Clouds','code','low_type_cloud');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NH','Clouds','octas','low_type_cloud_area_fraction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PRX','Air pressure','hPa','max(air_pressure_at_sea_level 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PRX','Air pressure','hPa','max(air_pressure_at_sea_level T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAX','Temperature','degC','max(air_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAX','Temperature','degC','max(air_temperature T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TAX_12','N/A','N/A','max(air_temperature T12H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAX_12','Temperature','degC','max(air_temperature T12H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAX','Temperature','degC','max(air_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TAX','Temperature','degC','max(air_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2TAX','Temperature','degC','max(air_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAX','Temperature','degC','max(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAXD','Temperature','degC','max(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAX_24','Temperature','degC','max(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FXB','Wind','Beaufort','max(beaufort_wind_force T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NNX','Clouds','octas','max(cloud_area_fraction 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NNX','Clouds','octas','max(cloud_area_fraction T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TGX','Temperature','degC','max(grass_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FXX','Wind','m/s','max(max(wind_speed T1H) T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FXX','Wind','m/s','max(max(wind_speed T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TGNX','Temperature','degC','max(min(grass_temperature T1H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('UX','Humidity','percent','max(relative_humidity 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('UX','Humidity','percent','max(relative_humidity T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SGX','Waves','code','max(sea_state 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SGX','Waves','code','max(sea_state T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TWX','Temperature','degC','max(sea_surface_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TWX','Temperature','degC','max(sea_surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WHMAX','Waves','meters','max(sea_surface_wave_height T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WHMAX','Waves','meters','max(sea_surface_wave_height T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WHMAX','Waves','meters','max(sea_surface_wave_height T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WHMAX','Waves','meters','max(sea_surface_wave_height T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WHMAX','Waves','meters','max(sea_surface_wave_height T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WHMAX','Waves','meters','max(sea_surface_wave_height T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TMAX','Waves','seconds','max(sea_surface_wave_period T20M) ');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PWAX','Waves','seconds','max(sea_surface_wave_period_from_instrument 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PWAX','Waves','seconds','max(sea_surface_wave_period_from_instrument T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HWAX','Waves','meters','max(sea_surface_wave_significant_height_from_instrument 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HWAX','Waves','meters','max(sea_surface_wave_significant_height_from_instrument T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SDX','Snow','code','max(snow_coverage_type 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSX125','Temperature','degC','max(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSX175','Temperature','degC','max(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSX25','Temperature','degC','max(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSX75','Temperature','degC','max(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('OTX','Sunshine','hours','max(sum(duration_of_sunshine T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_24X','Precipitation','mm','max(sum(precipitation_amount T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('POX','Air pressure','hPa','max(surface_air_pressure 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('POX','Air pressure','hPa','max(surface_air_pressure T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('POX','Air pressure','hPa','max(surface_air_pressure T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SAX','Snow','cm','max(surface_snow_thickness 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SAX','Snow','cm','max(surface_snow_thickness T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TGX','Temperature','degC','max(surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2TGX','Temperature','degC','max(surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X3TGX','Temperature','degC','max(surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SLAG','Precipitation','code','max(timeperiod_weather_type_significance1 T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VVX','Visibility','meters','max(visibility_in_air_horizontal 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VVX','Visibility','meters','max(visibility_in_air_horizontal T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FF2X','Wind','m/s','max(wind_speed 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FFX','Wind','m/s','max(wind_speed 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FX','Wind','m/s','max(wind_speed T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FX','Wind','m/s','max(wind_speed T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2FX','Wind','m/s','max(wind_speed T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FX2_1','Wind','m/s','max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FX_1','Wind','m/s','max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FX','Wind','m/s','max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FX_1','Wind','m/s','max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FX','Wind','m/s','max(wind_speed T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FX_020','Wind','m/s','max(wind_speed T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FX','Wind','m/s','max(wind_speed T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FX_020','Wind','m/s','max(wind_speed T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2FX','Wind','m/s','max(wind_speed T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2FX_020','Wind','m/s','max(wind_speed T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FF2X','Wind','m/s','max(wind_speed T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FFX','Wind','m/s','max(wind_speed T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FX','Wind','m/s','max(wind_speed T3H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FX_3','Wind','m/s','max(wind_speed T3H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FX','Wind','m/s','max(wind_speed T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FGX','Wind','m/s','max(wind_speed_of_gust 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FG_010','Wind','m/s','max(wind_speed_of_gust T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2FG_010','Wind','m/s','max(wind_speed_of_gust T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FG2_1','Wind','m/s','max(wind_speed_of_gust T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FG_1','Wind','m/s','max(wind_speed_of_gust T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FG_1','Wind','m/s','max(wind_speed_of_gust T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FG_010','Wind','m/s','max(wind_speed_of_gust T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FG_020','Wind','m/s','max(wind_speed_of_gust T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FG_020','Wind','m/s','max(wind_speed_of_gust T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2FG_010','Wind','m/s','max(wind_speed_of_gust T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2FG_020','Wind','m/s','max(wind_speed_of_gust T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FGX','Wind','m/s','max(wind_speed_of_gust T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PRM','Air pressure','hPa','mean(air_pressure_at_sea_level 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PRM','Air pressure','hPa','mean(air_pressure_at_sea_level T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAM','Temperature','degC','mean(air_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAMRR','Temperature','degC','mean(air_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAM','Temperature','degC','mean(air_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TAM','Temperature','degC','mean(air_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2TAM','Temperature','degC','mean(air_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAM','Temperature','degC','mean(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAMRR','Temperature','degC','mean(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAMA','Temperature','degC','mean(air_temperature_anomaly 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NNM','Clouds','octas','mean(cloud_area_fraction 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NNM','Clouds','octas','mean(cloud_area_fraction T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TD','Temperature','degC','mean(dew_point_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TD','Temperature','degC','mean(dew_point_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TGM','Temperature','degC','mean(grass_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAXM','Temperature','degC','mean(max(air_temperature T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FXM','Wind','m/s','mean(max(wind_speed T1H) T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FXM','Wind','m/s','mean(max(wind_speed T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TANM','Temperature','degC','mean(min(air_temperature T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TGNM','Temperature','degC','mean(min(grass_temperature T1H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('UM','Humidity','percent','mean(relative_humidity 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1UM','Humidity','percent','mean(relative_humidity T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('UM','Humidity','percent','mean(relative_humidity T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('THLF','Waves','degrees','mean(sea_surface_swell_wave_from_direction_of_spectral_peak_period T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TWM','Temperature','degC','mean(sea_surface_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TWM','Temperature','degC','mean(sea_surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('THTP','Waves','degrees','mean(sea_surface_wave_from_direction_of_spectral_peak_period T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PWAM','Waves','seconds','mean(sea_surface_wave_period_from_instrument 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PWAM','Waves','seconds','mean(sea_surface_wave_period_from_instrument T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HWAM','Waves','meters','mean(sea_surface_wave_significant_height_from_instrument 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HWAM','Waves','meters','mean(sea_surface_wave_significant_height_from_instrument T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('THHF','Waves','degrees','mean(sea_surface_wind_wave_from_direction_of_spectral_peak_period T20M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SDM','Snow','code','mean(snow_coverage_type 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSM125','N/A','N/A','mean(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSM175','N/A','N/A','mean(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSM25','N/A','N/A','mean(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSM75','N/A','N/A','mean(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJM','Soiltemperature','degC','mean(soil_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJM1','Soiltemperature','degC','mean(soil_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJM10','Soiltemperature','degC','mean(soil_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJM100','Soiltemperature','degC','mean(soil_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJM2','Soiltemperature','degC','mean(soil_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJM20','Soiltemperature','degC','mean(soil_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJM30','Soiltemperature','degC','mean(soil_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJM5','Soiltemperature','degC','mean(soil_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJM50','Soiltemperature','degC','mean(soil_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SHM','Humidity','gr/kg','mean(specific_humidity 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('POM','Air pressure','hPa','mean(surface_air_pressure 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('POM','Air pressure','hPa','mean(surface_air_pressure T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('POM','Air pressure','hPa','mean(surface_air_pressure T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SAM','Snow','cm','mean(surface_snow_thickness 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SAM','Snow','cm','mean(surface_snow_thickness T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TGM','Temperature','degC','mean(surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2TGM','Temperature','degC','mean(surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X3TGM','Temperature','degC','mean(surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DDM2','Waves','degrees','mean(wind_from_direction T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DDM','Wind','degrees','mean(wind_from_direction T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FF2M','Wind','m/s','mean(wind_speed 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FFM','Wind','m/s','mean(wind_speed 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FM2','N/A','N/A','mean(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FM','N/A','N/A','mean(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FM','Wind','m/s','mean(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FF2M','Wind','m/s','mean(wind_speed T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FFM','Wind','m/s','mean(wind_speed T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FGM','Wind','m/s','mean(wind_speed_of_gust 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FGM','Wind','m/s','mean(wind_speed_of_gust T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAM_K','Temperature','degC','mean_k(air_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAM_K','Temperature','degC','mean_k(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CM','Clouds','code','medium_type_cloud');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PRN','Air pressure','hPa','min(air_pressure_at_sea_level 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PRN','Air pressure','hPa','min(air_pressure_at_sea_level T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAN','Temperature','degC','min(air_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAN','Temperature','degC','min(air_temperature T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAN_12','Temperature','degC','min(air_temperature T12H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TAN','N/A','N/A','min(air_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2TAN','N/A','N/A','min(air_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAN','Temperature','degC','min(air_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TAN_12','N/A','N/A','min(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAN','Temperature','degC','min(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAND','Temperature','degC','min(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAN_24','Temperature','degC','min(air_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NNN','Clouds','octas','min(cloud_area_fraction 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NNN','Clouds','octas','min(cloud_area_fraction T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HLN','Clouds','meters','min(cloud_base_height T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TGN_12','Temperature','degC','min(grass_temperature T12H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TGN','Temperature','degC','min(grass_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TGN','Temperature','degC','min(grass_temperature T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FXN','Wind','m/s','min(max(wind_speed T1H) T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FXN','Wind','m/s','min(max(wind_speed T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TGNN','Temperature','degC','min(min(grass_temperature T1H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('UN','Humidity','percent','min(relative_humidity 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('UN','Humidity','percent','min(relative_humidity T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SGN','Waves','code','min(sea_state 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SGN','Waves','code','min(sea_state T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TWN','Temperature','degC','min(sea_surface_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TWN','Temperature','degC','min(sea_surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PWAN','Waves','seconds','min(sea_surface_wave_period_from_instrument 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PWAN','Waves','seconds','min(sea_surface_wave_period_from_instrument T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HWAN','Waves','meters','min(sea_surface_wave_significant_height_from_instrument 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HWAN','Waves','meters','min(sea_surface_wave_significant_height_from_instrument T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SDN','Snow','code','min(snow_coverage_type 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSN125','Temperature','degC','min(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSN175','Temperature','degC','min(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSN25','Temperature','degC','min(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSN75','Temperature','degC','min(snow_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('OTN','Sunshine','hours','min(sum(duration_of_sunshine T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PON','Air pressure','hPa','min(surface_air_pressure 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PON','Air pressure','hPa','min(surface_air_pressure T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PON','Air pressure','hPa','min(surface_air_pressure T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SAN','Snow','cm','min(surface_snow_thickness 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SAN','Snow','cm','min(surface_snow_thickness T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TGN','Temperature','degC','min(surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2TGN','Temperature','degC','min(surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X3TGN','Temperature','degC','min(surface_temperature T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VVN','Visibility','meters','min(visibility_in_air_horizontal 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VVN','Visibility','meters','min(visibility_in_air_horizontal T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FF2N','Wind','m/s','min(wind_speed 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FFN','Wind','m/s','min(wind_speed 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FF2N','Wind','m/s','min(wind_speed T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FFN','Wind','m/s','min(wind_speed T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FGN','Wind','m/s','min(wind_speed_of_gust 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FGN','Wind','m/s','min(wind_speed_of_gust T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DRR_GE1','Precipitation','number of','number_of_days_gte(sum(precipitation_amount T24H) 1M 0.1)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WAWA_015','Weather','code','over_time(weather_type T15M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WD1','Weather','code','over_time(weather_type_manually_observed_additional1 T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WD2','Weather','code','over_time(weather_type_manually_observed_additional2 T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WD3','Weather','code','over_time(weather_type_manually_observed_additional3 T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V4','Weather','code','over_time(weather_type_primary_significance T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V4S','Weather','code','over_time(weather_type_primary_significance_intensity T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('W1','Weather','code','over_time(weather_type_primary_significance_wmo T3H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V7','Weather','code','over_time(weather_type_quaternary_significance T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V5','Weather','code','over_time(weather_type_secondary_significance T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V5S','Weather','code','over_time(weather_type_secondary_significance_intensity T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('W2','Weather','code','over_time(weather_type_secondary_significance_wmo T3H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V6','Weather','code','over_time(weather_type_tertiary_significance T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V6S','Weather','code','over_time(weather_type_tertiary_significance_intensity T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RRVIPP','Precipitation','mm','precipitation_amount');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PH','Air pressure','hPa','qnh_air_pressure');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('UU','Humidity','percent','relative_humidity');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1UU','Humidity','percent','relative_humidity');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SG','Waves','code','sea_state');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WL','Water level','meters','sea_surface_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WL','Water level','meters','sea_surface_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WL','Water level','meters','sea_surface_height_above_lowest_astronomical_tide');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WL00','Water level','meters','sea_surface_height_above_lowest_astronomical_tide');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WL10','Water level','meters','sea_surface_height_above_lowest_astronomical_tide');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WL20','Water level','meters','sea_surface_height_above_lowest_astronomical_tide');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WL30','Water level','meters','sea_surface_height_above_lowest_astronomical_tide');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WL40','Water level','meters','sea_surface_height_above_lowest_astronomical_tide');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WL50','Water level','meters','sea_surface_height_above_lowest_astronomical_tide');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SDP1','Waves','m*m/H','sea_surface_primary_wave_spectral_density');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1SDP1','Waves','m*m/H','sea_surface_primary_wave_spectral_density');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2SDP1','Waves','m*m/H','sea_surface_primary_wave_spectral_density');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HW1','Waves','meters','sea_surface_swell_wave_first_mean_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PW1','Waves','seconds','sea_surface_swell_wave_first_mean_period');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HW2','Waves','meters','sea_surface_swell_wave_second_mean_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PW2','Waves','seconds','sea_surface_swell_wave_second_mean_period');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HM0LF','Waves','meters','sea_surface_swell_wave_significant_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TW','Temperature','degC','sea_surface_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TW','Temperature','degC','sea_surface_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2TW','Temperature','degC','sea_surface_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X3TW','Temperature','degC','sea_surface_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HMEAN','Waves','meters','sea_surface_wave_mean_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1HMEAN','Waves','meters','sea_surface_wave_mean_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('S1MEAN','Waves','degrees','sea_surface_wave_mean_steepness');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PW','Waves','seconds','sea_surface_wave_period');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WTP','Waves','seconds','sea_surface_wave_period_at_variance_spectral_density_maximum');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WTP','Waves','seconds','sea_surface_wave_period_at_variance_spectral_density_maximum');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WTP','Waves','seconds','sea_surface_wave_period_at_variance_spectral_density_maximum');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WTP2','Waves','seconds','sea_surface_wave_period_at_variance_spectral_density_second_maximum');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WTP2','Waves','seconds','sea_surface_wave_period_at_variance_spectral_density_second_maximum');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WTP2','Waves','seconds','sea_surface_wave_period_at_variance_spectral_density_second_maximum');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PWA','Waves','seconds','sea_surface_wave_period_from_instrument');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WTHMAX','Waves','seconds','sea_surface_wave_period_of_maximum_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WTHMAX','Waves','seconds','sea_surface_wave_period_of_maximum_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WTHMAX','Waves','seconds','sea_surface_wave_period_of_maximum_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HW','Waves','meters','sea_surface_wave_significant_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HWA','Waves','meters','sea_surface_wave_significant_height_from_instrument');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WHM0','Waves','meters','sea_surface_wave_significant_height_from_spectrum');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WHM0','Waves','meters','sea_surface_wave_significant_height_from_spectrum');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WHM0','Waves','meters','sea_surface_wave_significant_height_from_spectrum');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('HS1MAX','Waves','meters','sea_surface_wave_steepest_height');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('S1HMAX','Waves','degrees','sea_surface_wave_steepness_of_highest_wave');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('S1MAX','Waves','degrees','sea_surface_wave_steepness_of_steepest_wave');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WTZ','Waves','seconds','sea_surface_wave_zero_upcrossing_period');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WTZ','Waves','seconds','sea_surface_wave_zero_upcrossing_period');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WTZ','Waves','seconds','sea_surface_wave_zero_upcrossing_period');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CV','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CV147','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CV15','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CV18','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CV30','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CV40','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CV69','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CV75','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CV98','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1CV147','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1CV30','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1CV75','Current','m/s','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1CV','N/A','N/A','sea_water_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CD','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CD147','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CD15','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CD18','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CD30','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CD40','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CD69','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CD75','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('CD98','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1CD147','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1CD30','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1CD75','Current','degrees','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1CD','N/A','N/A','sea_water_to_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SD','Snow','code','snow_coverage_type');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSA125','Temperature','degC','snow_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSA175','Temperature','degC','snow_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSA25','Temperature','degC','snow_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSA75','Temperature','degC','snow_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ30','N/A','N/A','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ0','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ1','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ10','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ100','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ1000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ10000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ1100','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ120','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ1200','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ1300','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ1400','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ15','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ1500','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ160','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ1750','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ20','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ200','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ2000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ25','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ250','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ2500','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ300','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ3000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ350','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ3500','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ40','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ400','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ4000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ45','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ450','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ4500','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ5','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ50','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ500','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ5000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ5250','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ550','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ600','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ6000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ650','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ670','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ700','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ7000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ750','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ80','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ800','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ8000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ850','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ8500','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ900','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ9000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ95','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ950','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ9500','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TJ9750','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ1000','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ1100','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ120','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ1300','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ1500','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ160','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ20','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ200','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ250','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ300','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ350','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ40','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ400','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ500','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ700','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ80','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJ900','Soiltemperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJM10','Temperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJM20','Temperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TJM50','Temperature','degC','soil_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SH','Humidity','gr/kg','specific_humidity');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('EE','Field condition','code','state_of_ground');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NN04','Clouds','sum','sum(boolean_clear_sky_weather(cloud_area_fraction T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NN09','Clouds','sum','sum(boolean_fair_weather(cloud_area_fraction T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('NN20','Clouds','sum','sum(boolean_overcast_weather(cloud_area_fraction T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('OT','Sunshine','hours','sum(duration_of_sunshine 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('OT_1','Sunshine','minutes','sum(duration_of_sunshine T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('OT','Sunshine','hours','sum(duration_of_sunshine T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('OT_24','Sunshine','hours','sum(duration_of_sunshine T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR','Precipitation','mm','sum(precipitation_amount 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RRTA','Precipitation','mm','sum(precipitation_amount 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_010','Precipitation','mm','sum(precipitation_amount T10M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1RR_12','N/A','N/A','sum(precipitation_amount T12H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_12','Precipitation','mm','sum(precipitation_amount T12H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1RR','N/A','N/A','sum(precipitation_amount T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1RR_1','N/A','N/A','sum(precipitation_amount T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2RR_1','N/A','N/A','sum(precipitation_amount T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_1','Precipitation','mm','sum(precipitation_amount T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_01','Precipitation','mm','sum(precipitation_amount T1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1RR_24','N/A','N/A','sum(precipitation_amount T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR','Precipitation','mm','sum(precipitation_amount T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RRTA','Precipitation','mm','sum(precipitation_amount T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_24','Precipitation','mm','sum(precipitation_amount T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_3','Precipitation','mm','sum(precipitation_amount T3H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_6','Precipitation','mm','sum(precipitation_amount T6H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_720','Precipitation','mm','sum(precipitation_amount T720H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RRA','Precipitation','percent','sum(precipitation_amount_anomaly 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('EV_1','Evaporation','mm','sum(water_evaporation_amount T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('EV_24','Evaporation','mm','sum(water_evaporation_amount T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RRID','Precipitation','mm','sum_over_undefined_period(precipitation_amount 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_X','Precipitation','mm','sum_over_undefined_period(precipitation_amount T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RRID','Precipitation','mm','sum_over_undefined_period(precipitation_amount T24H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('PO','Air pressure','hPa','surface_air_pressure');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1PO','N/A','N/A','surface_air_pressure');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QA','Radiation','minutes','surface_albedo');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QLI','Radiation','W/m2','surface_downwelling_longwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QLI_01','Radiation','W/m2','surface_downwelling_longwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QF','Radiation','W/m2','surface_downwelling_photosynthetic_radiative_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QSI','Radiation','W/m2','surface_downwelling_shortwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QSI_01','Radiation','W/m2','surface_downwelling_shortwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QSI_010','Radiation','W/m2','surface_downwelling_shortwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QNET','Radiation','W/m2','surface_net_downward_radiative_flux');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SA','Snow','cm','surface_snow_thickness');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1TG','Temperature','degC','surface_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2TG','Temperature','degC','surface_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X3TG','Temperature','degC','surface_temperature');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QLO','Radiation','W/m2','surface_upwelling_longwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QLO_01','Radiation','W/m2','surface_upwelling_longwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QSO','Radiation','W/m2','surface_upwelling_shortwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('QSO_01','Radiation','W/m2','surface_upwelling_shortwave_flux_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TSS','Temperature','degC','temperature_in_surface_snow');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TAXDT','Temperature','Date','time_of_event_of_max(air_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FXXDT','Wind','Date','time_of_event_of_max(max(wind_speed T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('RR_24XDT','Precipitation','Date','time_of_event_of_max(sum(precipitation_amount T24H) 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('KLFX_1','N/A','N/A','time_of_event_of_max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1KLFX_1','N/A','N/A','time_of_event_of_max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('KLFX','Wind','time','time_of_event_of_max(wind_speed T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('KLFG_1','N/A','N/A','time_of_event_of_max(wind_speed_of_gust T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1KLFG_1','N/A','N/A','time_of_event_of_max(wind_speed_of_gust T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('KLFG','Wind','time','time_of_event_of_max(wind_speed_of_gust T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('TANDT','Temperature','Date','time_of_event_of_min(air_temperature 1M)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2WAWA_015','N/A','N/A','timeperiod_weather_type_from_instrument');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1WAWA_015','Weather','code','timeperiod_weather_type_from_instrument');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VV','Visibility','meters','visibility_in_air_horizontal');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SW10','Water','percent','volume_fraction_of_water_in_soil');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SW20','Water','percent','volume_fraction_of_water_in_soil');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SW30','Water','percent','volume_fraction_of_water_in_soil');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SW40','Water','percent','volume_fraction_of_water_in_soil');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('VP','Air pressure','hPa','water_vapor_partial_pressure_in_air');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('SYMBOL_NO','N/A','N/A','weather_symbol(instant_weather_type cloud_area_fraction T1H)');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WAWA','Weather','code','weather_type');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('WW','Weather','code','weather_type_manually_observed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V1','Weather','code','weather_type_primary_significance');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V2','Weather','code','weather_type_secondary_significance');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('V3','Weather','code','weather_type_tertiary_significance');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DD','Wind','degrees','wind_from_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DD06','Wind','degrees','wind_from_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DD12','Wind','degrees','wind_from_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DD18','Wind','degrees','wind_from_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DD2','Wind','degrees','wind_from_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1DD','Wind','degrees','wind_from_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2DD','Wind','degrees','wind_from_direction');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('DG','Wind','degrees','wind_from_direction_of_gust');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FF','Wind','m/s','wind_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FF2','Wind','m/s','wind_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FF','Wind','m/s','wind_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2FF','Wind','m/s','wind_speed');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X2FG','N/A','N/A','wind_speed_of_gust');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('FG','Wind','m/s','wind_speed_of_gust');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FG','Wind','m/s','wind_speed_of_gust');
Insert into KDVH_ELEMENT (ELEM_CODE,CATEGORY,UNIT,ELEMENT_ID) values ('X1FG_010','Wind','m/s','wind_speed_of_gust');

# --- !Downs

DELETE FROM KDVH_ELEMENT;
